### ISSUE TITLE
better type narrowing for initialData

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#3310]
when providing `initialData` directly on a `query`, the type of `data` is guaranteed to be `TData`, _not_ `TData | undefined`:

```
const { data } = useQuery(['test'], () => Promise.resolve('test'), { initialData: 'something' })

// 🚨 Object is possibly 'undefined'.(2532)
data.toUpperCase()
```

[TypeScript playground](https://www.typescriptlang.org/play?ssl=6&ssc=19&pln=1&pc=1#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ5wC+cAZlBCHAORToCGAxjALQCOO+VAUFwxAHap4SACZ0YdInAC8KDNlx4AFAG0qMdEKoBdADRwlAShkA+OAAVyIYBgB0tVBAA2AN3RL1mmFUP6kwfmAYYDonABFxOgAuakcQdBgACwCAcyoiQx4Aeiy4QF4NwAq9uAB5ACMAK3QmOBs4SFRUYFKnAipkfhF0EgD0ESpbJQAmAFYAZkHMsQlbGAgAVTAwXABhOgwjIA)

ideally, we could narrow the type when `initialData` is provided. This _only_ works for `initialData` because `initialData` is executed in the constructor of the query, and because it is synchronous. Also, it can only work on `v4` because in `v3`, `undefined` is technically still valid for the `TData` generic, so we cannot remove it from the union. In `v4`, `undefined` is illegal for successful queries, so that would now work.

Keep in mind that `initialData` can also be a function that returns `TData | undefined`, so this should also narrow if the function returns `TData`.

It does _NOT_ work for:
- `placeholderData`, because that will revert back to `undefined` when a query errors
- `initialData` being provided globally, because TS cannot know that on an instance level. It needs to be explicitly passed to `useQuery`.
- `suspense` or any other case because a query can be `cancelled` while it is initially `fetching`, in which case it will be `reset` to its initial state. `queryClient.resetQueries` also does that. Also, without network connection in the default network mode, the query will be in `fetchStatus: 'paused'` and will also not have data.

I guess we could potentially do this with another overload that has `initialData` provided and removes `undefined` from the result union, but we would also have do this for `useQueries`.
I would like to avoid having to add _another_ generic to `useQuery`, as we already have four of them.

Because this is for v4, PRs should go to the `beta` branch please.

**Comment by kettanaito** [comment]
So whenever `initialData` is provided, the returned `data` property is never undefined?

**Comment by TkDodo** [comment]
@kettanaito yes, that is correct. cached data is never removed and initialData synchronously populates the cache. Even if you programmatically remove the query and re-render, it will be recreated with initialData. Even if the query errors, the data is still kept.

I see no scenario where data can be undefined if initialData is provided :)

**Comment by TkDodo** [comment]
Correction: `select` can give you undefined, but that's a separate generic. So it correctly should mean that the `TQueryFnData` generic can never be undefined. `TData` defaults to `TQueryFnData` and is only different if select is provided.

**Comment by henribru** [comment]
> I see no scenario where data can be undefined if initialData is provided :)

You can still pass a function to `initialData` that returns `undefined`, I assume? E.g. if it gets the initial data from cache you might not have what you need in the cache. So this narrowing shouldn't apply in that case, right?

**Comment by TkDodo** [comment]
@henribru yes, but I don' see a difference between:

```
initialData: undefined
initialData: 'foo'
```

and

```
initialData: () => undefined
initialData: () => 'foo'
``´

as the signature for `initialData` is:

```
initialData?: TData | (() => TData | undefined)
```

so, yes, to be absolutely correct: As long as `initialData` is set to a value of type `TData` or a function that returns `TData`, you will always have a value in the cache.

I think we would need to look at the type of `initialData`, and if it's a function, look at the `ReturnType` instead. If that does not contain `undefined` in the union, we can perform the narrowing on the result.

**Comment by prateek3255** [comment]
@TkDodo I'd like to work on this issue

**Comment by yss14** [comment]
> I guess we could potentially do this with another overload that has initialData provided and removes undefined from the result union, but we would also have do this for useQueries.
I would like to avoid having to add another generic to useQuery, as we already have four of them.

To my knowledge using an overload-based approach is not possible with typescript at the moment (see this [playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIoFdoE8DyAHMYAexAGcAeAFQD4BvAKGSeSIIEYB+ALmRHQFsARtEbNWYAEzdkpMFFABzUU1DBCcADYA1TZmmV6AX3r1QkWIhQZs+QiVIB1NQAsAkiDXBNOjZgAiEDCgEAAmVHTKLOzSfEIizFGS0rLyIEoJqurauhA8Bsam4NDwSGiYUFgAShCk6Bpg4QwJIXBgcHnIAD7I6CAhgcEhRiZmxZZl2NW19U5gzn6tcAFBIKGNkS1tecP0ML0IdiA9pBDWFeEAFOKk0me4BMRk4QCUPHdTdQ00u-uHx6flLCXa63QG2R6OFzuTzeHLLQYvN6Aj4zFwLNrw1Zhb57EAHR7-O7Agg3JE2B72cJdCYVcH2WZuDxZHz+AZYxE0qo1T5U7rvbmoubopZstY0JrMKAQMDoKBHPgaDTIOCkZUgLA7BD2MDIWibdrIfVsQzIAC8hMB5BSimoF2e9AA9A7kM5oCh9RIZM4iHUQshhMgAETWtKBtV+kBEHXBuSKam9forUKB+hasg6vWLHgek3m9AnIkhhS22iZLzZXy5IOuxVEZAAdyIUA0IUDhmeQA)). A return type of a function can not be inferred based on whether a certain object property is set or not. This can only be solved by introducing a generic for the query options and using conditional types based on that generic for the function return type.

But maybe some typescript guru can prove me wrong :)

**Comment by prateek3255** [comment]
@TkDodo Update here, I was trying to do it via conditional types with generic but that wasn't working as expected. So I have asked a [question for it on StackOverflow](https://stackoverflow.com/questions/71892746/typescript-make-function-output-dependent-on-whether-an-input-parameter-is-undef). And as mentioned by @yss14 even the overload based approach also doesn't seem to be working as expected. Do you have any other ideas on what else we can try out here?

**Comment by yss14** [comment]
@prateek3255 I answered your SO question :)

Here is my working [playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRQK4FMoE8DS6sA0cAqgM7pqZYDyYMwEAdqUWRRtgErqmoA2MIpWwAxVIwDG9JnAC+cAGZQIIOACIo6AIZSAtAEcOWNQG4AUGeCMYmBTvQlyURGbhxgAEwBccRqhAARpjmboxaIOg+pDBQVgDm5rIWMFhgDmzCWNy8AgAiWjBauegKVugeADwAKvmFRFUAolDKUAB8cAC8cNQgwDAVGUbZ-P01BVr1TS2tRGoe42rtAGQubvOFPmOFieYpaXAAygAWEPweAELoxaWM5Z2O7FTDeePXZZVsUETiANaMEAB3RitADacwWAF1dqkHMdTnwLuhaNIwnx7oMnjwRgMnN9GH9AcCwestGoockYQ9MsiGMwAJKMPrALR8WpFErvCquOBVTIiRhsgjcxrNaBCtxbCbCzJ4LBwdAADxsjA8pBQRllZnaXR6fRxj2wNKYpGqfIF40moq+PMFPJl+Bm6isTJZbMWcBWCG5zvorvGmzNbJ2FkVkFginEUlpcFQ5EyXIlgfG91+-yB4p5U2gKfxacYGcl915Rn5gulGvw8qV6BVavtcq69YL1LoasVytVVKMRuYppL5rqmat9Vtxaosu1XaoPZN3MT-bLbglWa+c5tFrXY+wmrcrS1AApuRA6LTSAHu62zABKc-T1tVjtqjGGk-Ghku1mvDm3SpbrCli0hxaEdAL-CduQAfinLgsReQo3h-apRxXPc3B8Z8slg0ZkKtVpzFDaB4AUSMURjOMjATO0F2TLpU0JAsVxzAl02FNkiyTOpy3HSt2xrTt63uJsuJfGA22rWtoJoV9ez-ADBxFYD13k+tJwwmdKPnKg5KlJcgLFTdFyXMD8G5PdWkPNxDG4rBb23fAM2PFFSAg2ypNEuAAHoPLgAABGAIA8CA4C0DwPDgFQ+jgKy7LlLQ4i0Kxr1c5ExMfSSZ3fX1P3g79yj7LSBwmPTrUleoVMgyTnhgNkELy0ritQuB0PIzEcmw0CUPwhUwyIkjo1jA0sEo2TCqYvMGKtMb6NYmiqIKwzjLlXiJIExsK0IYS3NSvinxakTT3y0RCstRT6sW1S9rcg7Nw4nSjJXDMJUMzSYtMg9uWi3B8Fc2UM0+-kfD5PqmEO-9jrmmKZiPaTnOS+8vN8-zAuC0Lwt6eBPtlYKVSi-tgvixKbwhraHx29KYcy5lsvZG46tuk6xSUorzoqjCqpq3Lfxw6ZuWawaqqQjrcK6nqI0kUiBvjTbtIm4CZsKdjqM4l6vqW8T+PWwT1ubC93OWzs1Jh0GZeKkDlPWi7BvUm6lbu5dhwMjddMWt7zO5LQoDiABGH7KwAH2JlKMw9uIACYXPVLTgcYY3wfOuAA7-IP3c9gBmCOk8vInM719XdqtinGSyjnad-enTaZsqLdZy72a-UvBfklDecqrDG+ZlDVjgTQYFQKBGF8fg0S0NUtEYLBEgsBGqh4GAzAkY14DidAYE+e59yJteOnafckE8HwvdT1OAHYiDCCIfDUbgdHgTI1DkK9zHnxfcdakY2ThM5LlqsLaMu-cwQDSgGoIgXsIREA3p0doy9V5OA3kQL0bgfRUzZD4Pe3g4AABZQ5n3CJEdQAAJdAfA+BBQAOrQARPfWQQpZCPzMHsBwM9ohe3uIwiAChX4wTah-E4X8ric2JJCEwnlvJVEpMAfOUAzCfTroUT+CJv6cwAHQklETyCRUiLAL2YBjIYWFeHwkRD2FkKZ-6AKcCAuAYCIFXigXAGBnwN70MYTyWeoc2Ewg4VwzCPDxgKOMdJFkQjChkhEdPTRDxnAB3EB4TmMj9F+PkXwxRSIgl8FUcmCJ+xJFRITjGFU8SgA) for the `useQuery` hook.

**Comment by prateek3255** [comment]
Thanks @yss14. Will check it out 🙌

**Comment by TkDodo** [comment]
`initialData` can be a function as well, but apart from that, the playground seems to work well 👍 . It can also be a function that returns `undefined` - not sure if that makes it more complicated?

**Comment by CoLdAs1cE** [comment]
Question not relate or related?
But when using suspense globally 
Data type is of `Type | undefined`,
But shouldn't data be of `Type` only?
Since if error it will trow to error boundary, so it cannot be undefined if my type does not allow undefined?

(i just started using react-query so i am not well know about how it works, was searching issues and this was the closest related to my problem 😄 )

**Comment by TkDodo** [comment]
Doesn't work. You can always say `enabled: false` and you won't have data. Also networking offline might put you in paused state. Also the edge case about cancelQueries I mentioned in the issue description.

**Comment by prateek3255** [comment]
So I tried using the solution by @yss14 but the type narrowing still doesn't seem to be working as expected when I try using it with the basic-typescript example. Also I get a few type errors due to the return `useBaseQuery` hook because of the conditional types we added, and we I try to fix that by updating the types for `QueryObserverResult` as well then it starts causing type errors at a bunch of other places, so avoiding updating the types at all those places for now, by using a ts-expect-error in `useQuery` for now.

I have also updated the basic-typescript a little bit to test the changes. Opened a draft PR with #3557

**Comment by prateek3255** [comment]
I tinkered a little bit more and was able to fix the type errors and get one of the overloads working that @yss14 demonstrated with the playground, have pushed the updated code in the same PR, but now the problem is that one of a few other overloads are not working at all, and breaking the existing types.

For instance the `useQuery` overload where it just takes one argument which are all the options, returns `unknown` as the type for data when I make the generic changes to the options. Here is the [same playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRQK4FMoE8DS6sA0cAqgM7pqZYDyYMwEAdqUWRRtgErqmoA2MIpWwAxVIwDG9JnAC+cAGZQIIOACIo6AIZSAtAEcOWNQG4AUGeCMYmBTvQlyURGbhxgAEwBccRqhAARpjmboxaIOg+pDBQVgDm5rIWMFhgDmzCWNy8AgAiWjBauegKVugeADwAKvmFRFUAolDKUAB8cAC8cNQgwDAVGUbZ-P01BVr1TS2tRGoe42rtAGQubvOFPmOFieYpaXAAygAWEPweAELoxaWM5Z2O7FTDeePXZZVsUETiANaMEAB3RitADacwWAF1dqkHMdTnwLuhaNIwnx7oMnjwRgMnN9GH9AcCwestGoockYQ9MsiGMwAJKMPrALR8WpFErvCquOBVTIiRhsgjcxrNaBCtxbCbCzJ4LBwdAADxsjA8pBQRllZnaXR6fRxj2wNKYpGqfIF40moq+PMFPJl+Bm6isTJZbMWcBWCG5zvorvGmzNbJ2FkVkFginEUlpcFQ5EyXIlgfG91+-yB4p5U2gKfxacYGcl915Rn5gulGvw8qV6BVavtcq69YL1LoasVytVVKMRuYppL5rqmat9Vtxaosu1XaoPZN3MT-bLbglWa+c5tFrXY+wmrcrS1AApuRA6LTSAHu62zABKc-T1tVjtqjGGk-Ghku1mvDm3SpbrCli0hxaEdAL-CduQAfinLgsReQo3h-apRxXPc3B8Z8slg0ZkKtdovTcTQYFQKBGF8fg0S0NUtEYLBEgsAB6eieR4GAzAkY14DidAYE+e59xvB5nA6dp9yQTwfAARgAZikgB2IgwgiHw1G4HR4EyNQ5Cvcw2I4uBDExHIYDZOEzkuBC7i6WMDSwUT9IrLAfDBayoDUIgJIhIgDNERgfH4zp2i4ninH42RtLMbzMKMkyTjMq5v3KAA6Ek4EYnlKWANVU0JRRs1IFQHE0SimDMIA) that @yss14 shared which uses the overload that returns `unknown` type for the data.

Although there are some other type errors within, the tests as well with this approach, but we'll be able to figure them out, once we figure out what's causing this issue. @TkDodo @yss14 Do you have any idea on what's wrong with the above playground?

**Comment by mattpocock** [comment]
Likely a naive attempt here:

https://github.com/TanStack/query/pull/3834

**Comment by alexandraseri** [comment]
I wonder why `placeholderData` doesn't behave the same as `initialData`? 
From what I understand, placeholder data also guarantees the data being of the TData type, isn't not?
