### ISSUE TITLE
Unable to invalidate infinite query data in react native app

### ISSUE THREAD

**Issue by sohamad** [TanStack/query#3718]
### Describe the bug

I have implemented infinite scroll in react native app using flatlist and infinite query of react query. When i move to different screen, i make changes and invalidate the infinite query. it doesn't work. My dom still renders the same old data. I was checking we can refetch as well tried but it didn't seem to be working as well. Is there a solution for it. Can anyone provide refetching code pointer. Code sample to refetch a single page of infinite query data but on different screen after mutation.

### Your minimal, reproducible example

can't publish code

### Steps to reproduce

i haven't published code as of now 

### Expected behavior

i want to update dom after invalidating the data.

### How often does this bug happen?

Every time

### Platform

android

### react-query version

3.19.1

**Comment by TkDodo** [comment]
> can't publish code

you can try to come up with a minimal example that fails. you don't have to show your code, and you don't have to connect to your api. The template is very clear that we cannot invest time if you don't invest the minimum time of reproducing the issue. The chances are high that there is an issue with your setup rather than with react-query.

Feel free to reopen once you have a reproduction.
