### ISSUE TITLE
setState in onSuccess is not working first time with suspense

### ISSUE THREAD

**Issue by Einere** [TanStack/query#3784]
### Describe the bug

With `Suspense`, calling `setState` in `useQuery.onSuccess` is not changing state.
I found that this issue would be fix turning off `refetchOnWindowFocus`. but it still no good UX (require at least 1 re-rendering)

### Your minimal, reproducible example

https://codesandbox.io/s/react-query-example-f5od07

### Steps to reproduce

1.  make `queryClient` with option below.
```
{
  suspense: true,
  refetchOnWindowFocus: false,
}
```

2. call `useQuery` in child component
3. call `React.setState` function in `onSuccess`
4. wrap child component with `Susepnse` width `fallback`

### Expected behavior

1. only once query call after component mounted
2. successfully changing state
3. unless user hard-refreshing browser, react-query don't send query.

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Browser: Chrome v103

### react-query version

v3.38.0

### TypeScript version

v4.6.3

**Comment by TkDodo** [comment]
calling setState from onSuccess is often an anti-pattern, as you can achieve the same thing with deriving state.

That being said, I think this is just how suspense works: suspense unmounts your component and shows the error boundary. Then, when the fetch succeeds, we call `onSuccess`. You call `setState` on a component that is no longer there, and then react re-mounts your component with a fresh `useState`.

if you really want to sync state, prefer an effect:

```
const [ip, setIp] = useState("");

const { data } = useQuery(...)

useEffect(() => {
  if (data) {
    setIp(data.ip)
  }
}, [data])
```

**Comment by Sangminnn** [comment]
@TkDodo hello, i have one more question :)

first. would you check me understand correctly?

In anti-case i think that works like below flow 
`suspense work -> component unmount -> query success -> onSuccess with setState -> component re-mount`
in onSuccess Status, setState in unmount component isn't work well. ( can't re-render component ) 
because that watch unmount component's state(setState)

but, in using useEffect case,
`suspense work -> component unmount -> query success -> onSuccess without setState -> component re-mount  -> setState in useEffect`
in this case, setState in useEffect work well. (can re-render component)

i know useEffect(with dependency) work in both first mount and dependency change, 
So that case(using useEffect case), Is useEffect work with cached query data in first mount?

**Comment by Einere** [comment]
@TkDodo 
I has tested your solution, it work fine. Thank you for detail explanation! 👏
I just thought that "what difference `onSuccess` and `useEffect`?" "isn't the same thing?".
Now I learned new things. thanks.

**Comment by Einere** [comment]
@Sangminnn

It's not accurate, but I'm guessing `Suspense` working like below.
1. `<Suspense>` is mount.
2. child component is mount.
3. call asynchronous call. (like `useQuery`)
5. `<Suspense>` observe child component's asynchronous call, and unmount it, replace it with fallback component.
6. at this time, `useEffect` not called. because child component is unmounted.
7. when asynchronous call returns some result, `<Suspense>` unmount fallback component, replace it with the child component.
8. at this time, `useEffect` is called, the `data` is exist. so user can see smooth web page.

I'm curious why `data` is already exist at step 8. 🤔
anyway, `useEffect` with `useQuery` is work well.

**Comment by TkDodo** [comment]
@Einere is right, that is how it works.

> I'm curious why data is already exist at step 8. 🤔

Because `useQuery` reads from the cache when the component renders, and `data` is in the cache.

With `onSuccess`, it goes like this:

1. Suspense mounts
2. child component mounts
3. usQuery throws the Promise
4. component unmounts, is replaced by suspense fallback
5. onSuccess is called, tries to setState on an unmounted component, which does nothing
6. promise completes, fallback unmounts, component mounts again
7. useState re-initializes with the default value
