### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by mbret** [TanStack/query#3804]
### Describe the bug

Assuming a scenario where the child component call a parent callback prop after a mutation is finished which make some change in the parent and as a result render a different child.

Calling a function which trigger a re-render in the parent from `onSuccess`, `onSettled`, etc will result in a warning

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

Even tho everything happens in the same tick and synchronously react seems to be un-mounting the child component between two synchronous call, resulting in the warning

I do realize the example I put in the sandbox might look silly but it's a simple way to showcase the error that affect us (for a less silly reason)

### Your minimal, reproducible example

https://codesandbox.io/s/broken-wave-kg5xng?file=/src/Test.js:0-741

### Steps to reproduce

Just open the console to see the warning

### Expected behavior

I was expecting the callback to run in the same unmounted context during the same tick.

I made the same example using react 18 https://codesandbox.io/s/throbbing-paper-3sf88c?file=/src/Test.js. It seems to be working as expected, probably due to the recent changes related to rendering queuing / batching.

### Platform

web

### react-query version

3.39.1

**Comment by TkDodo** [comment]
This warning was completely removed in React 18, because it was misleading. Have a read here:

https://github.com/reactwg/react-18/discussions/82

Also, if you want conditional callbacks, use the callbacks on the `.mutate` function. Those are called conditionally. The ones on `useMutation` are always called. I'm covering this in my blog here:

https://tkdodo.eu/blog/mastering-mutations-in-react-query#some-callbacks-might-not-fire

and it's also in the docs here:

https://tanstack.com/query/v4/docs/guides/mutations#mutation-side-effects
