### ISSUE TITLE
Inactive useInfiniteQuery doesn't complete

### ISSUE THREAD

**Issue by kyles450** [TanStack/query#3819]
### Describe the bug

From the docs:

> By default, queries that unmount or become unused before their promises are resolved are not cancelled. This means that after the promise has resolved, the resulting data will be available in the cache.

I've got a Component that mounts and is using a `useInfiniteQuery` hook. If I unmount the component while the query is still loading I can see that the request finishes successfully in the network tab, but React Query Devtools doesn't get the data. And if I mount the Component again, it starts the request again. In fact, if I do this while the request is still in progress it will create multiple, simultaneous requests.

Maybe I'm misunderstanding how this is supposed to work?

### Your minimal, reproducible example

https://codesandbox.io/s/crazy-varahamihira-9zg918?file=/src/index.js

### Steps to reproduce

1. Open the console
2. Click "Mount component"
3. Click "Unmount component" BEFORE it completes (it takes 5 seconds)
4. After 5 seconds, you should see `"Promise completed!"` in the console.
5. If you re-mount the component, there is no cache and it will refetch.

### Expected behavior

As a user, I expected the unmounted request to complete and get cached.

### How often does this bug happen?

Every time

### Platform

- OS: Mac
- Browser: Chrome
- Version: 3.39.1

### react-query version

v3.39.1

**Comment by TkDodo** [comment]
I think we fixed this in v4. Here's your codesandbox with v4 beta23: https://codesandbox.io/s/magical-breeze-csj5f1?file=/src/index.js

the query now stays in fetching state until it finished, even if you unmount, unless you consume the abort signal, in which case it will be cancelled. This is in-line with how useQuery works.

**Comment by kyles450** [comment]
Great, thanks!

**Comment by Jinmo-K** [comment]
Leaving this here in case anyone else comes across this issue

We're using the useAppQuery example found on twitter and passing the query function context to the queryFn by spreading it 

```
useQuery({
  ...
  queryFn: (queryFnContext) => {
     ...
     return queryFn({
        ...queryFnContext,
        ...otherParams
     })
  }
})
```

There's [code](https://github.com/TanStack/query/blob/53813e45e126dcd8f846addf69c5b78322f868b8/packages/query-core/src/query.ts#L377) here for deciding when a signal has been consumed (the doc could probably be clearer about what that word means).

Getting around the issue by passing queryFnContext directly as a param instead of spreading the values
