### ISSUE TITLE
Brutal deprecation

### ISSUE THREAD

**Issue by fzaninotto** [TanStack/query#3917]
## Problem

The previous version or react-query is deprecated on npm: https://www.npmjs.com/package/react-query. The package doesn't even have a readme. 

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/99944/180778352-9aa57840-22bc-4788-9cda-23edea64e41e.png">

The documentation for react-query v3 isn't available when going to https://tanstack.com/query

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/99944/180790153-9166e99f-dbac-4c0e-bb11-ddd7dbad08ac.png">

Since it's deprecated, I believe react-query v3 will no longer receive any updates.

This "deprecation" is super brutal for existing react-query users, who simply can't continue maintaining their existing apps. 

I understand that moving to tanstack query is the way to go, but if that package disappears the same way react-query disappeared, I'm not sure I want to upgrade. 

## What Would Be Better

- Keep the readme on react-query v3 on npm
- Add a version selector to the react-query home page & documentation
- Continue maintaining react-query v3 for some time (at least 6 months)

## Context

We've built [react-admin](https://github.com/marmelab/react-admin) on top of react-query 

### Your minimal, reproducible example

https://tanstack.com/query/v4

### Steps to reproduce

Go to https://tanstack.com/query/v4

### Expected behavior

See how other libraries do:

- MUI
<img width="354" alt="image" src="https://user-images.githubusercontent.com/99944/180790504-42d07950-e68d-4fcf-892f-252b424cce15.png">

- react-admin
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/99944/180790612-2170f4b3-2cd6-435a-acfa-f698be327700.png">

- react-router
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/99944/180790774-f01a05ad-8519-47a2-97fc-19d73095c59c.png">

### Platform

all platforms

### react-query version

v3

**Comment by idrissakhi** [comment]
Agree

**Comment by TkDodo** [comment]
let me clarify what happened:

- we released v4 as `@TanStack/react-query` v4. That is also what you see when you go to the TanStack docs.
- `react-query` on npm was always meant to stay on 3.x, however, something went wrong with the release and we inadvertently also released a version 4.0.0 of react-query.
- we tried to unpublish that release, but it lead to even more troubles. So we just marked it as deprecated.

Note that the message explicitly states that you should use `@TanStack/react-query` for version 4. You can still install version 3 normally, it's not deprecated and also not "not supported".

If you go to the old docs link, which is https://react-query.tanstack.com/, you will be redirected to the new docs, but you'll see a banner with a link that takes you to the new location of the v3 docs, which is https://react-query-v3.tanstack.com/.

![Screenshot 2022-07-25 at 17 48 18](https://user-images.githubusercontent.com/1021430/180820532-5a8a1b5c-72d6-4a61-94f2-e19e7cf0f4ad.png)

As for the documentation improvements - I agree that they can be improved, but for that, please open an issue in the tanstack.com repo (https://github.com/TanStack/tanstack.com) because that's where the docs are created.

**Comment by fzaninotto** [comment]
Thanks for the clarification! And for the reassurance. 

So the heart of the problem is that the npmjs.org message is misleading. Can't you remove the 4.0 release instead of deprecating it? The npm folks should be able to help. 

Otherwise, please add an explicit readme in the release explaining that react-query is NOT deprecated.

**Comment by TkDodo** [comment]
> Can't you remove the 4.0 release instead of deprecating it? The npm folks should be able to help.

@tannerlinsley is in contact with them as far as I know.

**Comment by fzaninotto** [comment]
Any updates? The npm package pages still mentions nothing...

**Comment by tannerlinsley** [comment]
NPM support is still unresponsive. 🤷‍♂️

**Comment by TkDodo** [comment]
the `latest` tag now points again to 3.39.2.

https://twitter.com/TkDodo/status/1558147386442121217

It's all back to normal if you go to: https://www.npmjs.com/package/react-query
