### ISSUE TITLE
useQuery isLoading shouldn't be true unless the enabled condition is matched

### ISSUE THREAD

**Issue by sonjoydatta** [TanStack/query#3925]
### Describe the bug

`useQuery` has a key called enabled. If you pass `enable: false`, `isLoading` is stuck to the value `true`. I think it should be false because the API didn't meet the condition.

### Your minimal, reproducible example

https://codesandbox.io/s/busy-sea-xnnm8r

### Steps to reproduce

1. Configure ReactQuery with a fresh project
2. Make an API call and pass `enabled: false`
3. Destructure `isLoading` and console log it

### Expected behavior

I expect `isLoading` should be false as it didn't meet the condition.

### How often does this bug happen?

Every time

### Screenshots or Videos

![Screenshot 2022-07-26 at 2 11 48 PM](https://user-images.githubusercontent.com/49079726/180957213-5b7fe465-3979-4995-949f-f566ea661f23.png)

### Platform

- macOS Monterey - version: 12.5
- Google Chrome - 103.0.5060.134 (Official Build) (arm64)
- React -version: 18.1.0

### react-query version

4.0.5

### TypeScript version

4.6.3

**Comment by DamianOsipiuk** [comment]
I think You should actually use `isFetching`  in combination with `isLoading`

```ts
if (isFetching && isLoading) {
  return <p>Please wait...</p>
}
```

This should show only during initial fetch, not on refetches

https://tanstack.com/query/v4/docs/guides/queries#why-two-different-states

> So keep in mind that a query can be in `loading` state without actually fetching data. As a rule of thumb:
  The `status` gives information about the `data`: Do we have any or not?
  The `fetchStatus` gives information about the `queryFn`: Is it running or not?

**Comment by TkDodo** [comment]
⬆️  this is the correct answer. I'm aware that it might come across as confusing, because `loading` was, until now, always tied to the initial fetch, like showing a "loading spinner" when you are "loading". And while this is enough for most of the cases, there are edge-cases where you now can be in loading state without actually fetching data (being offline, having a disabled query). This is still better than the previous `idle` state, which was an exception and could lead to impossible states with the new features we added in v4 (network mode), so it had to go.

I briefly considered renaming `isLoading` to `isPending` because from a promise perspective, it represents that better. I also wrote about this on twitter:

https://twitter.com/TkDodo/status/1550541281520193537

pending means "no data yet"
success means "data available"
error means "error available"

this status doesn't tell you anything about if you should display a spinner to the user or not. you can be in success state and be fetching, or in error state and fetching, or in pending (loading) state and _not_ fetching. There are lots of possibilities :)

Most problems will come from having `enabled: false`. If you have a conditional enabled option because of dependent queries, you are likely fine to display the spinner, because you'll likely want it until both queries have finished fetching. But going full-blown `enabled: false` means you actually had to previously check for the `idle` state, which doesn't exist anymore. The example you posted would, in v3, actually show `no data found`, which is likely also incorrect.

Anyways, this is not an issue but works as designed :)
