### ISSUE TITLE
MutateAsync is not resolving when no internet connection is available

### ISSUE THREAD

**Issue by sandergo90** [TanStack/query#3945]
### Describe the bug

Hi,

We already implemented offline support using the beta versions of v4, after upgrading now to the latest v4 version, it doesn't seem to work anymore.

Kind regards,
Sander

### Your minimal, reproducible example

Code inside bug report

### Steps to reproduce

Our network mode is the default "online" mode and the onlineManager is set correctly to offline.  Let's take the following example:

```
const useCreateShoppingList = () => {
  const { setError } = useErrorStore();
  const { graphQLClient, withDefaultHeaders } = useGraphQLClient();
  const queryClient = useQueryClient();
  const mutation = useCreateShoppingListMutation<
    ClientError,
    { previousShoppingLists?: GetShoppingListsQuery }
  >(
    graphQLClient,
    {
      onMutate: async variables => {
        await queryClient.cancelQueries([
          SHOPPINGLISTS_QUERY_KEYS.list(variables.id),
          SHOPPINGLISTS_QUERY_KEYS.lists,
        ]);

        const previousShoppingLists = queryClient.getQueryData<GetShoppingListsQuery>(
          SHOPPINGLISTS_QUERY_KEYS.lists,
        );

        const newList: List = {
          ...variables,
          updatedAt: new Date().toISOString(),
          totalItems: 0,
          items: [],
        };
        cacheActions.createShoppingList(queryClient, newList);

        return { previousShoppingLists };
      },
      onError: (error, _, context) => {
        queryClient.setQueryData(SHOPPINGLISTS_QUERY_KEYS.lists, context?.previousShoppingLists);
        setError({ error });
      },
      onSuccess: () => {
        Analytics.trackEvent({
          event_name: 'list creation',
          list_name: 'user shopping list',
        });
      },
      onSettled: () => {
        queryClient.invalidateQueries(SHOPPINGLISTS_QUERY_KEYS.lists);
      },
    },
    withDefaultHeaders(),
  );

  const handleCreateShoppingList = async (name: List['name'], subType?: ListSubType) => {
    const id: List['id'] = uuidv4();
    await mutation.mutateAsync({
      id,
      name,
      subType: subType ? subType : ListSubType.Transversal,
      createdAt: new Date().toISOString(),
    });

    console.log('NOT REACHING THIS POINT');

    return id;
  };

  return handleCreateShoppingList;
};

export default useCreateShoppingList;
```

You can see a console log, this log is not reached when you are offline. So the mutateAsync is never resolved? 

### Expected behavior

MutateAsync to be resolved.

### Platform

- iOS 15
- React native 0.67.2

### react-query version

4.0.10

**Comment by TkDodo** [comment]
we haven't changed anything code-wise between `beta` and the stable versions - all that changed were the imports.

if your `networkMode` is `online` (the default), and you start a mutation while you are already `offline`, the mutation will immediately go into the `isPaused: true` state. It will continue once you go online again.

I see nothing in your code that changes this default behaviour. Please show a runnable codesandbox example where we can see what is not working, and also state which beta version is working. At best, you would provide the same example in two sandboxes: one not working with v4 and another working one with the beta release.

> Expected behavior
MutateAsync to be resolved.

resolved with what? Since the mutation doesn't fire, there wouldn't be data to resolve it with ...

**Comment by sandergo90** [comment]
When the user is offline, the user is able to add a shopping list. Executing this mutation will run the `onMutate` function which will add this shopping list to the react-query cache. When the user will come back online, it will execute the network call. 

Right now, code after the `mutateAsync` function is never executed, because the `await mutateAsync` is never resolved. I thought that it would just resolve the function and when the user would come back online, the `mutationDefault` for this mutationKey would execute.

**Comment by TkDodo** [comment]
`onMutate` will run, yes, and then we try to execute the mutation, which will be immediately paused because you have no network. At no point in time in the `beta` versions did `await mutateAsync(...)` resolve while you are offline with the default `networkMode`.

So unless you can show a running example that had this behaviour, all I can say is it works as expected.

What you can and probably should do is to use `mutate` instead and rely on the `onSuccess` / `onError` callbacks. In your  `handleCreateShoppingList` example, I don't even understand why you would be awaiting the mutation if you are not using the result in the first place ...

**Comment by sandergo90** [comment]
Alright, clear, thanks 👌
