### ISSUE TITLE
useQuery return always isLoading with true when enabled is false

### ISSUE THREAD

**Issue by aXenDeveloper** [TanStack/query#3975]
### Describe the bug

When I created `useQuery` with `enabled: false` option, `isLoading` variable is always `true`.

### Your minimal, reproducible example

https://codesandbox.io/s/react-query-enabled-7u58d5-7u58d5

### Steps to reproduce

1. Create simple query by use `useQuery`,
2. Add `enabled: false` into options,
3. Check state for `isLoading`.

### Expected behavior

State `isLoading` is `false`.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/58148176/182569615-8173e0e3-3a77-406d-ae9a-68f0b1ec8eb4.png)

### Platform

- OS: Windows 11 22H2,
- Browser: Chrome
- Version: 103

### react-query version

4.0.10

### TypeScript version

4.7.4

**Comment by aXenDeveloper** [comment]
Ok, I see this https://tanstack.com/query/v4/docs/guides/disabling-queries
Its very strange...

**Comment by aXenDeveloper** [comment]
Ok, I see this https://tanstack.com/query/v4/docs/guides/disabling-queries
Its very strange...

**Comment by egorovsa** [comment]
I faced the same! 
react-query version
4.0.10

```
  const { isLoading } = useQuery(
    ['currentUser'],
    () => Promise.resolve(),
    {
      enabled: false, // always false just for test
    }
  );

// isLoading is always true 
```

It seems to me I have to downgrade till it's fixed

**Comment by TkDodo** [comment]
Yes, in hindsight, I also think that pending / success / error would be the better naming for the states. We thought about it, but decided that it would break too many cases / cause troubles upgrading.

If you have previously checked for the `idle` state explicitly, you now have to combine two checks. We can talk about exposing an extra derived flag if we find a good name for it.

often, you can:
- check for data availability over checking statuses, as this will make your behavior more predictable. I have a blogpost on that topic: https://tkdodo.eu/blog/status-checks-in-react-query
- for dependent queries, it is often good enough to keep checking the loading state, because if you're interested in data for the second query, you need to wait for it anyhow.

Maybe you can show your use-case and we can try to come up with the best way of handling it without checking both flags combined.

Lastly, v4 was in alpha / beta for about 6 months. Feedback on api changes is most effective during that time, before we released v4.0. "Are you serious?" comments when it's too late to change something are not helpful. So yes, I'm serious.

**Comment by TkDodo** [comment]
> A flag that tells us when to show the loader in these cases would be a lot cleaner than having to check if fetchStatus is not idle and if it's loading, or if there's no data present

showing data if data is there might be the best way, as this will prevent data unmounting if e.g. a background update yielded an error. 

I mean, you could also _not_ mount the current thread component if no thread is selected? 

However, I'm happy to add that flag if we can find a good name for "isLoading and isFetching" ... `isHardLoading` ?

> The right side should show an empty state when no thread is selected, and a loader once a thread has been selected and is fetching the data for that thread.

Just for my understanding: how did you implement this in v3? With an explicit `isIdle` check? Or did you just fall through all other cases and rendered null?

**Comment by parkm** [comment]
> Just for my understanding: how did you implement this in v3? With an explicit isIdle check? Or did you just fall through all other cases and rendered null?

So I have two queries, one for the thread list on the left, and one for the current thread. The current thread query is disabled until a thread has been selected.

So my logic was:
```
if (currentThreadQuery.isLoading) {
   showLoader()
} else if (!currentThreadQuery.data) {
   showEmptyState()
} else {
   showCurrentThread()
 }
```

Now I just have to change that first line to `currentThreadQuery.isLoading && currentThreadQuery.fetchStatus !== 'idle'` which isn't the end of the world, just a bit bulkier.

**Comment by egorovsa** [comment]
@TkDodo I am sorry for the sharp expression like ""Are you serious?"  at the same time I am not alone with this issue that faced a bug after update and was very upset after that.

Ok now about my case. This case is extremely simple 

```
const { isLoading, data: currentUser, refetch, error } = useQuery(
    ['currentUser'],
    () => UsersApi.getCurrentUser(),
  );

  const { isLoading: isTokenLoading } = useQuery(
    ['tokenCoreApp'],
    () => UsersApi.getToken(),
    {
      enabled: Boolean(currentUser),
      onSuccess: handleTokenSuccess,
    }
  );

  const loading = isLoading || isTokenLoading;
```

First of all I have to get a current user data and token's query is depending on the current user.
it means that it's possible that it will never be fired because the current user is 401.

Just why `isTokenLoading` should be true whenever this is switched off at all.

So now I just have to add an additional condition to have a common isLoading like this

`isLoading || (isTokenLoading && Boolean(currentUser))`

and I feel it looks ugly. 

So it's confusing even in very simple example.
BTW. about alpha and beta to my mind this is not an argument. I am not sure many people would test it on the projects those have already been in production for instance. 

Have a good time. Thanks for your answers!

**Comment by diegocasillas** [comment]
@TkDodo we have also found issues with this new behaviour of `isLoading`.

> If you have previously checked for the idle state explicitly, you now have to combine two checks. We can talk about exposing an extra derived flag if we find a good name for it.

What about including a new boolean flag `isDisabled`? Then `isLoading` would be `false` in cases where the query is disabled. In my opinion, it's a bit counter intuitive that a disabled query will return `isLoading` as `true`, because I'm not expecting it to load 😅

**Comment by TkDodo** [comment]
> What about including a new boolean flag isDisabled? Then isLoading would be false in cases where the query is disabled. In my opinion, it's a bit counter intuitive that a disabled query will return isLoading as true, because I'm not expecting it to load 😅

a query itself cannot be disabled. disabled on useQuery only means that _this observer_ does not fetch data for itself. you can have two observers - on enabled one disabled, then the query will be fetching.

you can also have `data` on a query, because you prefetched it, hydrated it, restored it from localstorage or passed it as `placeholderData`/ `initialData`. in all these cases, the query would be in `success` state instead of `loading`.

---

I think it's mostly a mindset problem. I've tried to outline it in the docs as well: Think of loading / success / error as states that describe / discriminate the `data` property. If you think about a promise, it can be pending / fulfilled / rejected. That's the same concept. `loading === pending` - it just means "data is not here yet". It doesn't mean we're actually firing the queryFn to get the data _right now_ - that's what the fetchStatus is for.

---

I think the best we could do is expose another flag that combines `isLoading && !isFetching`, which would be equivalent to the previous `idle` state. Finding a good name is the hardest part probably

**Comment by diegocasillas** [comment]
Thanks for your quick response! ✨  It makes a lot of sense and I agree that it's a mindset problem in our case. I'm still not sure what would be the best way of helping developers understand this change and migrate to this new version while keeping the behaviour we had previously with `isLoading`. I have a gut feeling that more people will find this an issue before they understand the underlying concept 🤔 

> I think the best we could do is expose another flag that combines isLoading && !isFetching, which would be equivalent to the previous idle state. Finding a good name is the hardest part probably

I wanted to be Captain Obvious here and suggest to name it `isIdle`, but I understand that it can't be "idle" if it is loading 😅 

Thanks again ✌️

**Comment by TkDodo** [comment]
> I have a gut feeling that more people will find this an issue before they understand the underlying concept 🤔

I understand, and by now I think we should've just renamed `loading` to `pending` to make it more obvious, and maybe keep the `isLoading` flag around that also includes `isFetching`. But yeah, more feedback on the beta would've been good. Now it's too late :(

We can do: `isInitialLoading: isLoading && isFetching` but then you'd still need to check for that. It's the best I can come up with right now.

> I wanted to be Captain Obvious here and suggest to name it isIdle, but I understand that it can't be "idle" if it is loading 😅

ha, I pondered about keeping the `isIdle` flag. The problem is that we also have a `fetchStatus === "idle"` and it would also be confusing if `isIdle` is _not_ derived from that, like `isPaused` is derived from `fetchStatus === "paused"`

**Comment by anglee** [comment]
I found this issue after running into the same issue and spending time debugging it. And tbh, I also had the same 'are you serious?' thought.

For a breaking change like this, I didn't find the word 'enabled' used in the doc [Migrating to React Query 4]( https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4). It would be helpful to include explicit instructions about how to migrate code with `enabled: false` in the guide.

**Comment by TkDodo** [comment]
>  It would be helpful to include explicit instructions (e.g. a before&after code example) about how to migrate code with enabled: false in the guide.

It really depends on how you've checked for the `idle` state before. Did you use the `isIdle` flag`? Did you use `status === 'idle'` ? Did you check for data availability and then fall back to rendering `loading...` if there is no data or error?

**Comment by paustint** [comment]
Our team has been struggling with this as well and had had to work around this - normally by doing something like `(isLoading && isEnabled)` when deriving the true is loading state.

We have not looked into all the other properties to see if there is an easier way - but we were caught off guard that a disabled query shows up in a loading state and would love a simple boolean that we can use to know if a query is truly enabled and loading.

Maybe a name could be `isEnabledAndLoading` (that is at least how I think about things)

**Comment by missing1984** [comment]
Came across this one too. I agreed this is a mindset problem but mindset can be framed either way. most of our use case around `enabled` is to make a query run on a condition -- there's no guarantee that dependent query will always run. 

Where the new behavior is more like -- dependent query will eventually run but it just don't have data yet and therefore is still consider as loading.  

These are 2 different mental models and use cases. It's a bit unfortunate we made it as a breaking change.

**Comment by tomskopek** [comment]
Just want to double check, since thinking about this stuff sometimes makes my head hurt.

Is the closest replacement to the previous behaviour of `isLoading`: `isLoading  && fetchStatus !== 'idle'`?

ie:
```js
import { useQuery } from '@tanstack/react-query' // react-query v4

const { isLoading, fetchStatus } = useQuery( ... )
const isLoadingV3 = isLoading && fetchStatus !== 'idle'
```

**Comment by TkDodo** [comment]
Yes

**Comment by tomskopek** [comment]
Long term, obviously I need to refactor my code to match the new `isLoading` mindset. On the one hand I don't want to create new variables called `isLoading` that are basically aliases for `isLoading && fetchStatus !== 'idle'`, because that's confusing to have two meanings for `isLoading` and keep both in my mental model. On the other hand, I don't want to write out `isLoading && fetchStatus !== 'idle'` everywhere because it's not great for readabliity, and it's easy to forget that you also need to check that fetchStatus.

@TkDodo you seem receptive to adding a new variable to the return to capture the concept discussed above, if we can come up with a good name.

I had a look at the [v3 documentation](https://react-query-v3.tanstack.com/reference/useQuery) for the `status: loading` description. `loading - if the query is in a "hard" loading state. This means there is no cached data and the query is currently fetching, eg isFetching === true`

I'd like to throw another couple ideas into the ring:

`isWaiting`, or the more explicit `isWaitingForData`. This conveys appropriately that data has been fetched, but there is no data yet.

or:

`initialFetchStatus`. This would be the fetchStatus of the first fetch, but not subsequent ones. This one I am less sure about because of how caching works, someone more familiar with the library would have to ensure this makes sense.

or a variation of this, that would return a boolean (my preference):

`isInitialDataLoading`. I believe this fits the spirit of the v3 `isLoading` description? `This means there is no cached data and the query is currently fetching`

or:

`isHardLoading`. Simply because this is how v3 docs described it. Althought I don't find it terribly descriptive.

I also think @paustint 's suggestion of `isEnabledAndLoading` is not bad, although it's not quite the same as `isLoading && fetchStatus !== 'idle'`, I think it's similar? Even if this is not a chosen direction, it would be useful to have an `isEnabled` boolean flag exposed in the return, so that we can standardize our queries.

Thoughts?

**Comment by Shaddix** [comment]
Personally we are deferring an update to v4, hoping that some name for this state will emerge and we could just use it everywhere (just like we use `isLoading` now, and it works in 99% of the cases that we have).

**Comment by TkDodo** [comment]
So I think I have up my mind for what I want to do for the next major version. Believe me, I am terribly sorry that I didn't do this with v4 already. No one regrets this more than me. The plan is to:

1. rename `status: 'loading'` to `status: 'pending'`
2. rename `isLoading` to `isPending` (a simple derived state from the status, like isSuccess and isError)
3. re-introduce `isLoading` as derived value from: `isPending && isFetching`

That would allow our main status field to remain intact and describe `data` (pending/success/error), while also having a good `isLoading` boolean that works like in v3. The breaking thing would be that `status === 'loading'` wouldn't exist anymore, as you would have to change it to `status === 'pending'`. 

---

The thing is, if we introduce something now that combines the two like `isInitialDataLoading` or whatever, it wouldn't actually be needed, as it would be `isLoading` as described above.

With that in mind, yes, I think we can:
- introduce a new field that combines `isLoading && isFetching` now.
- dot the proposed changes in v5
- deprecate the new field in v5 and "alias" it to the then good `isLoading`
- remove it in v6.

Please drop more name suggestions, and I'll also run this proposal by @tannerlinsley

**Comment by TkDodo** [comment]
`isInitializing` would be my currently favoured name for `isLoading && isFetching`. Thoughts?

**Comment by tomskopek** [comment]
@TkDodo This proposal makes a lot of sense to me 😃 
One clarification:

> deprecate the new field that we introduce now in v5 and "alias" it to the then good isLoading

What is the new field you are talking about deprecating?

> isInitializing would be my currently favoured name for isLoading && isFetching. Thoughts?

I like it! I also like `isPending` 🙂

**Comment by TkDodo** [comment]
> I like it! I also like isPending 🙂

That wouldn't work as we'd want to use `pending` as per my proposal for the 3 main states (pending / success / error), because then `isPending` would mean something else and would likely create more confusion.

**Comment by tomskopek** [comment]
Ah yes, good point

**Comment by tomskopek** [comment]
As for release plan - any issues with just jumping straight to the desired v6 state that you proposed, directly with a v5 major version breaking change release (that would happen sooner than you probably expected)?

**Comment by Shaddix** [comment]
> `isInitializing` would be my currently favoured name for `isLoading && isFetching`. Thoughts?

I suppose most developers discover API via intellisense/IDE suggestions, and for this scenario they would start typing with something like `loading`, so properties like `isInitialLoading`/`isLoadingAndFetching`/`isHardLoading` are discovered easier.

These names are a bit ugly, but if there are plans to deprecate and remove them, it might even be a good thing (no one will argue for keeping them and adopting their mental model to it, which might happen with `isInitializing`).

Also, `isInitializing` is really a good name, and I imagine it might be really used for some behavior in the future, which would cause confusion.

(this is just to share non-obvious 'pros' for the ugly names :))

**Comment by alexnault** [comment]
> 1. rename status: 'loading' to status: 'pending'
> 2. rename isLoading to isPending (a simple derived state from the status, like isSuccess and isError)
> 3. re-introduce isLoading as derived value from: isPending && isFetching

This is music to my ears ❤️

**Comment by TkDodo** [comment]
please see:
- https://github.com/TanStack/query/pull/4244

**Comment by Kaizer69** [comment]
> > What about including a new boolean flag isDisabled? Then isLoading would be false in cases where the query is disabled. In my opinion, it's a bit counter intuitive that a disabled query will return isLoading as true, because I'm not expecting it to load 😅
> 
> a query itself cannot be disabled. disabled on useQuery only means that _this observer_ does not fetch data for itself. you can have two observers - on enabled one disabled, then the query will be fetching.
> 
> you can also have `data` on a query, because you prefetched it, hydrated it, restored it from localstorage or passed it as `placeholderData`/ `initialData`. in all these cases, the query would be in `success` state instead of `loading`.
> 
> I think it's mostly a mindset problem. I've tried to outline it in the docs as well: Think of loading / success / error as states that describe / discriminate the `data` property. If you think about a promise, it can be pending / fulfilled / rejected. That's the same concept. `loading === pending` - it just means "data is not here yet". It doesn't mean we're actually firing the queryFn to get the data _right now_ - that's what the fetchStatus is for.
> 
> I think the best we could do is expose another flag that combines `isLoading && !isFetching`, which would be equivalent to the previous `idle` state. Finding a good name is the hardest part probably

Also for me is most useful having a state "isDisabled".
isInitialLoading is a wrong term because it has same meaning of isFirstLoading, but when I enable the query, it can be a isSecondLoading, isThirdLoading, is*Loading.
"Initial" word for me is only the first time, not the first time you do a query that will be executed a lot of time.

**Comment by mnieber** [comment]
>> a query itself cannot be disabled. disabled on useQuery only means that this observer does not fetch data for itself. you can have two observers - on enabled one disabled, then the query will be fetching.

I think the docs should be updated to clarify this, since it says

```
This is technically true, however, since we are not currently fetching any data (as the query is not enabled), it also means you likely cannot use this flag to show a loading spinner.
```

I think it should say something like

```
This is technically true, however, since we are not necessarily fetching any data (as the caller did not enable the query), it also means you cannot use this flag to show a loading spinner.
```

**Comment by minut-shan** [comment]
I know this thread is closed since long, I just have one question. Is there any benefit of using `isLoading` over `isInitialLoading`? 

I tried reasoning about it, but currently I can't see any reason why I can't just always use `isInitialLoading`

**Comment by TkDodo** [comment]
> I tried reasoning about it, but currently I can't see any reason why I can't just always use isInitialLoading

`isInitialLoading` doesn't type-narrow `data` like `isLoading` does. That's because it's a derived flag. It will also be `false` if you want to fire a query for the first time, but the user has no network connection. So if you do something like that:

```
if (isInitialLoading) return 'Loading...'
if (isError) return 'Error...'

return <div>{data.someProperty}</div>
```

your code might die at runtime in edge cases like no network, or, if you are using the persister plugins, while restoring from an external storage.

Again, it's a tradeoff. States are complex and we can't have everything :)

**Comment by ElJijuna** [comment]
El problema suele pasar porque el componente no a terminado de renderizar.

puedes solucionarlo:

```javascript
await expect(findByText('algo')).resolves.toBeDefined();

// y listo
````

**Comment by ryanparker-st** [comment]
Has there been some documentation around what the plan for isLoading is and if we're going to get a prop that returns true when the request is in transit but false if the request is disabled? This seems to me like a common use case.

As of v5, the docs no longer reference isLoading, instead they reference isPending. However isLoading is still available in the API and is not flagged for deprecation.

It would be really helpful if isLoading could be `isLoading = isPending && enabled`

**Comment by paustint** [comment]
v5 docs do mention this:
https://tanstack.com/query/latest/docs/framework/react/reference/useQuery

```
isLoading: boolean
Is true whenever the first fetch for a query is in-flight
Is the same as isFetching && isPending
```

If the query is disabled, this will be false.

> As of v5, the docs no longer reference isLoading, instead they reference isPending.
for `useMutation`, `isPending` is available to indicate in-progress, but `isLoading` was removed
