### ISSUE TITLE
useQueries not inferring type correctly, when using onSuccess and select

### ISSUE THREAD

**Issue by plotka** [TanStack/query#3994]
### Describe the bug

When using `useQueries()` with typed individual queries, the data type is not inferred when using `onSuccess` or `select` methods, and we get an error
`Parameter 'data' implicitly has an 'any' type.`

With `useQuery()` it works fine and we can see the `data`'s type:
`(parameter) data: number`

### Your minimal, reproducible example

https://codesandbox.io/s/wizardly-ride-w58pio?file=/src/App.tsx

### Steps to reproduce

1. Go to sandbox - https://codesandbox.io/s/wizardly-ride-w58pio?file=/src/App.tsx
2. Check `onSuccess` in `useQuery()` options,  it works fine.
3. Check `onSuccess` and `select` in `useQueries()` options, it has an error.

### Expected behavior

It is expected to have the inferred type also in `useQueries()`

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/6666010/183449736-c64e094d-d698-4f73-8c1a-062cd607d8e2.png)

### Platform

- OS: mac OS
- Browser: Opera

### react-query version

v4.0.10

### TypeScript version

v4.7.4

**Comment by TkDodo** [comment]
@artysidorenko maybe you can look into this?

**Comment by artysidorenko** [comment]
Hi @plotka,

This is a limitation of the current type logic I’m afraid. You'll need to give TS a hint by explicitly typing the callback param.

e.g. 

```typescript
select: (data: number) => console.log(data)
```

It's not quite as gung-ho as casting, and can still help you maintain type safety: if you were to give it a `string` type it will complain at you as expected. It just can’t do the inference upfront.

**Background**: `useQueries` is using a recursive conditional type to manually unwrap the array and infer the different data types of each array item one at a time. It’s not very friendly with context sensitive parameters such as callback params, because the latter also requires TS to do multiple rounds of inference before it knows what is the right candidate. So it gets stuck down the wrong path. With `useQuery` it works, because there's no `queries` array that TS needs to make guesses about, so it can get a definite candidate for the data-type after a single pass.

[Another example in the repo tests](https://github.com/TanStack/query/blob/v4.1.3/packages/react-query/src/__tests__/useQueries.test.tsx#L676-L719)

**Comment by plotka** [comment]
Thanks for the detailed response @artysidorenko. Although, what you mentioned works with `select` but not with `onSuccess`, as can be seen here:
![image](https://user-images.githubusercontent.com/6666010/184616648-2f3a7718-d3f2-4c30-8344-1292e01a725c.png).

As a workaround, in my code, I  am typing the `UseQueryOptions` explicitly, but still need to type it in the `select` and `onSuccess`,  like so:
```js
  useQueries<UseQueryOptions<ResponseType, ErrorType, DataType>[]>({queries: [{
    queryKey: 'key',
    queryFn: () => fetch(),
    select: (resp: ResponseType) => resp.data,
    onSuccess: (data: DataType) => console.log(data),
  }]})
```
and it doesn't complain if I type it to the wrong type.
Also, it only works if all the queries return the same type. I think there should be a better way to do this.

**Comment by TkDodo** [comment]
Closed as known limitation.
