### ISSUE TITLE
useQuery fires refetch even If the query key did not change

### ISSUE THREAD

**Issue by SzabKel** [TanStack/query#4088]
### Describe the bug

I am building a page, where I load different components on menu clicks (tabs). I noticed that If I change tabs, react query fires the network request each time I change tabs and come back. The component is not rendered when I am on a different tab, so when I change back and it gets mounted, a network request fires. Even If the query key is just a single string (and did not change).

I changed the `refetchOnMount` option to false on the query, but now it won't fire the first time or even If I change query key.

I tried to change the `staleTime` as well, with a number > 0, it also won't ever fire the query.

### Your minimal, reproducible example

https://codesandbox.io/s/usequery-not-firing-onmount-cv1wkp?file=/src/App.tsx

### Steps to reproduce

Change tabs between 1 and 2. The data is refetched each time to you change it to tab 1. The `["test-query"]` query key does not changes.

### Expected behavior

I expected the query to fire the first time the component mounts and each following time it mounts again, It should not start a query until the query key changes.
I set the cacheTime so the data should be cached and I am using the same query key. Shouldn't it survive a component remount?

### How often does this bug happen?

Every time

### Platform

Windows. Firefox and Chrome.

### react-query version

4.2.2

### TypeScript version

4.4.2

**Comment by TkDodo** [comment]
This is what `staleTime` is for. It tells react-query to treat data in the cache as "fresh" for a specific amount of time, so that no background refetch happens.

Your problem comes from combining `staleTime` with `initialData`, as `initialData` is put into the cache and is treated as valid data - just as if you had fetched it. So by setting `initialData` to an empty array, this will be put into the cache. And because you set stale time, that empty array is considered fresh for that time, so no real fetch is happening. That is per design. What you are looking for is likely a combination of `staleTime` and `placeholderData`.

Here is a fork with:
- `staleTime: Infinity`
- `placeholderData: []`

https://codesandbox.io/s/usequery-not-firing-onmount-forked-5zovq2?file=/src/App.tsx

Also, have a look at my extensive blog post on that topic: https://tkdodo.eu/blog/placeholder-and-initial-data-in-react-query
