### ISSUE TITLE
invalidateQueries doesn't work when my query have one item

### ISSUE THREAD

**Issue by soheilhassanjani** [TanStack/query#4091]
### Describe the bug

hi , i have some problem with invalidateQueries . i mutate and after successfully , invalidate queries . when my target query have more than one item , it is work ( query fresh ) but when my query have one item it not work and query status change to stale instead of fresh . 

### Your minimal, reproducible example

.

### Steps to reproduce

.

### Expected behavior

.

### Platform

macOS

### react-query version

4.1.0

**Comment by soheilhassanjani** [comment]
why closed ?

**Comment by TkDodo** [comment]
you basically violated every rule of opening an issue. It looks like you have a question about your specific situation, not a general bug in react query. Every bug report needs a reproducible example. If you have one, feel free to re-open. Otherwise, open a discussion. But even for a discussion, there isn't much to go on without showing code...
