### ISSUE TITLE
MutationFunction optional parameters

### ISSUE THREAD

**Issue by LoganAtCrypto** [TanStack/query#4264]
### Describe the bug

`useMutation` does't not persist the signature of `MutationFunction`. is it make sense and possible to persist MutationFunction optional parameters in muration.murate?

```typescript
import { useMutation } from '@tanstack/react-query';

const updateRecord = async (arg1?: number) => {
  return arg1;
};

const mutation = useMutation(updateRecord);

mutation.mutate(); // type error
mutation.mutate(undefined); // ok
```
feel redundant that i have to write `mutation.mutate(undefined);` instead of just `mutation.mutate()`.

<img width="613" alt="Screen Shot 2022-10-05 at 15 21 31" src="https://user-images.githubusercontent.com/80801525/194003414-796009c3-6216-4be7-b166-7fbb83a13c5d.png">

<img width="869" alt="Screen Shot 2022-10-05 at 15 21 38" src="https://user-images.githubusercontent.com/80801525/194003443-7e020a58-26cd-4456-972b-70c02cdcdf46.png">

### See also
[Treating undefined parameters as optional](https://github.com/microsoft/TypeScript/issues/12400)

### Your minimal, reproducible example

https://codesandbox.io/s/zen-fire-9iu1er?file=/src/App.tsx

### Steps to reproduce

--

### Expected behavior

See above

### Platform

- MacOS

### react-query version

4.9.0

### TypeScript version

4.7.4

**Comment by TkDodo** [comment]
plase make sure to _save_ the sandbox. It's empty when I open it!

**Comment by TkDodo** [comment]
so this works:

```
arg1?: number | void
```

https://codesandbox.io/s/thirsty-andras-iw67ud?file=/src/App.tsx:105-125

**Comment by LoganAtCrypto** [comment]
Thanks for your reply, `arg1?: number | void` works. But change the type of `updateRecord` may not always be possible. for example, if `updateRecord` lives in a third party library.

**Comment by LoganAtCrypto** [comment]
honestly, at this point i'm not sure what's the difference between declaring a function parameter as optional and declaring a function parameter as void


```typescript
function fa(a?: number) {
  return a;
}

function fb(a: number | void) {
  return a;
}

fa(); // ok
fa(undefined); // ok
fb(); // ok
fb(undefined); // ok
```

**Comment by TkDodo** [comment]
yeah I get that. I think right now, `variables` need to be required and we work around this with the `void` type as the default for the `TVariables` generic:

https://github.com/TanStack/query/blob/f715b305dedca12ac22812145fa29e42dbd6dfa1/packages/react-query/src/types.ts#L100

The function is then constructed like so:

https://github.com/TanStack/query/blob/f715b305dedca12ac22812145fa29e42dbd6dfa1/packages/react-query/src/types.ts#L102-L104

I think mutations without variables are the exception - a DELETE request comes to mind. I haven't seen one with only one optional parameter though.

What you can do is wrap and unwrap it in an object if you can't change the type of the function that make the request itself:

```
const mutation = useMutation((params: { arg1?: number } | void) =>
  updateRecord(params?.arg1)
);

mutation.mutate(); // ok
mutation.mutate(undefined); // ok
mutation.mutate({ arg1: 5 }) // ok
```

see: https://codesandbox.io/s/summer-monad-w3isyh?file=/src/App.tsx

it takes away the option to just call `.mutate(5)` but I think it's a good tradeoff.

Otherwise, if you or someone else  wants to take a stab at improving the types, PRs are welcome.

**Comment by LoganAtCrypto** [comment]
I tried something like this:

``` typescript
export type MutateFunction<
  TData = unknown,
  TError = unknown,
  TVariables = void,
  TContext = unknown,
> = TVariables extends undefined ? {
  (
    variables: TVariables,
    options?: MutateOptions<TData, TError, void, TContext>,
  ): Promise<TData>
} : {
  (
    variables: TVariables,
    options?: MutateOptions<TData, TError, TVariables, TContext>,
  ): Promise<TData>
}
```
But got few type errors in other files. i'm just get started with react-query and don't know how to resolve those type errors.

@TkDodo thanks for you quick reply ❤️

**Comment by LoganAtCrypto** [comment]
intuitively, `TVariables` should be an optional parameter in `MutateFunction`. If `TVariables` is optional, then we don't need to write `mutation.mutate(options)` instead of `mutation.mutate(undefined, options)`. you just mention that `mutations without variables are the exception `.  the statement may not be true when building a library that uses `react-query` as the underling layer for async state management.

**Comment by TkDodo** [comment]
> If TVariables is optional, then we can write mutation.mutate(options)

This would need overloads and runtime checks that we cannot do because we are not in control of the variables.

What would a call to:

```
mutate({ onSuccess })
```

be at runtime? Is this no variables + options, or is it just variables, no options? It's ambiguous.

For useQuery, the overloads only work because we know that the key is always an array, and that the queryFn is always a function, and that options are always an object (at runtime). And still, we want to move away from overloads.

So no, I don't see a good way to make that work.
