### ISSUE TITLE
useQuery does not work well with suspense and initialData

### ISSUE THREAD

**Issue by carlossluzala** [TanStack/query#4297]
### Describe the bug

This small example shows how useQuery seems to get stucked on initialData when using suspense and initialData together:

https://codesandbox.io/s/beautiful-cannon-uxm56f?file=/src/App.tsx

The page and query key updates but fetchData is not called.

I've read the docs and could not found any warning about using them together. The example shows a paginated query but it happens with a single data query too. 

### Your minimal, reproducible example

https://codesandbox.io/s/beautiful-cannon-uxm56f?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/beautiful-cannon-uxm56f?file=/src/App.tsx
2. Click on next page

### Expected behavior

Query calling fetchData when changing page.

### Platform

- OS: MacOS and Windows
- Browser: Google Chrome
- Version: 106.0.5249.91

### react-query version

3.39.2

**Comment by TkDodo** [comment]
I think I know what's going on:

`initialData` is written to the cache, so your query will be in `success` state. Then, because you mount a new observer and `refetchOnMount` is on per default, the query will make a background refetch if the query is stale.

The problem with `suspense` is that we need a small `staleTime` set because suspense unmounts our component. With a `staleTime` of zero, we would immediately fetch again when the component re-mounts. This happens internally:

https://github.com/TanStack/query/blob/34ca5581217dae4133046f6cfbc746a22be14dd9/packages/react-query/src/useBaseQuery.ts#L61-L67

That has the unwanted side-effect that combined with initialData, you won't get an initial fetch.

What you can do is use `placeholderData` instead. It seems like conceptually, this is also what you want: show a placeholder until the fetch has completed.

I've described the differences between `placeholderData` and `initialData` here: https://tkdodo.eu/blog/placeholder-and-initial-data-in-react-query

**Comment by carlossluzala** [comment]
Thank you for responding so quickly @TkDodo!

Okay, but one thing does not make sense to me: in case of pagination I change the query key every time the page changes so the initialData should not be replaced? I tried to set a small staleTime but only worked with 0.

**Comment by TkDodo** [comment]
initialData works for every cache entry, and if you do pagination where the query key changes, initialData will be done for every one of those entries. You'd need to conditionally set initialData depending on the query key where you would like to set it on ...

**Comment by carlossluzala** [comment]
Nice, thanks so much for the big help!
