### ISSUE TITLE
isFetched is true before the query is fetched when using query cache

### ISSUE THREAD

**Issue by zlanich** [TanStack/query#4301]
### Describe the bug

In developing one my Expo React Native apps, I was relying on the statuses and boolean flags to try to determine when a fresh object was loaded (not from cache), and I noticed that the isFetched query boolean is true before the query ever enters a fetching status, but it appears to only happen when using QueryCache (which I'm using with @tanstack/query-async-storage-persister). See the log progression here: 
![useQuery](https://user-images.githubusercontent.com/1522665/194964284-5fe07075-0c4a-4aaa-a0f5-4511389d5c40.png)

In order, the progression is as follows:
- 1. App hasn't yet let RQ know about the online state (idle)
- 2. App is pinging the outside world to determine if the internet is reachable, so RQ thinks it's offline (paused)
- 3. RQ pulls from cache and starts fetching, but isFetched is true prematurely (isFetching is also true here)
- 4. Fetch is done (idle)

This seems very misleading to me and doesn't seem intentional. It also doesn't match up with the fetch statuses. Can someone speak to this?

I'm currently on 4.2.3

### Your minimal, reproducible example

https://snack.expo.dev/@wecreatedev/usequery-bug

### Steps to reproduce

I'm unable to reproduce this in Expo Snack for some reason, even with query cache.

### Expected behavior

isFetched shouldn't be true until the query has finished fetching

### Platform

React Native

### react-query version

4.2.3

### TypeScript version

4.8.2

**Comment by TkDodo** [comment]
so when the query is in:

`status: success, isFetched: true, fetchStatus: fetching` 

(line 7 in your screenshot), we can see that the initial fetching has finished already - `user` is no longer `null`.

`fetchStatus` being `fetching` could be for another reason, for example, because another component picks up the query and a background refetch is happening due to the default staleTime of zero.

Looking at the reproduction:
- if you use persisters in react, please us the [PersistQueryClientProvider](https://tanstack.com/query/v4/docs/plugins/persistQueryClient#usage-with-react)

**Comment by zlanich** [comment]
Thanks @TkDodo! It does appear that I had another instance of that hook elsewhere, but I think my issue with not being able to rely on isFetched had to do with me accidentally forgetting to use PersistQueryClientProvider. I swapped this in and it "appears" to be working now, even though I can't get the example to run with the same setup I have working in my app (No QueryClient set) for some reason - maybe I'm blind).

I'm closing this, since I don't think there's an actual issue with react-query. Thank you!
