### ISSUE TITLE
Cache Eviction Freezes Browser

### ISSUE THREAD

**Issue by arlyon** [TanStack/query#4500]
### Describe the bug

This PR https://github.com/TanStack/query/pull/2851 introduced a change that attempts to deal with `QuotaExceededError` when using the persisting query client. To be clear, it's a great first step, and I'm grateful for the work that went into it. However, the problem is, it tries to naively remove the oldest item and persist again and again. Persisting can take on the order of tens of milliseconds for large caches (also a problem), but the issue is that if a user visits multiple pages with abnormally large queries compared to the rest of the app, a large number of naive LRU evict-and-persist cycles happen to attempt to accommodate it. This materializes as a freeze, as the app re-serializes a marginally smaller and smaller json blob again and again. 

I am wondering if there is a better way.

The first step should be to keep a track of the persisted size of a query such that the eviction procedure can determine which queries to evict _without_ having to do a costly persist cycle for each attempt. That way we simply count up the data and perform a single eviction. I believe this will pretty much solve the issue, however the overall design seems like it could be improved further. I have a calendar app with fairly heavy requests from google calendar, and the cache gets full after just a handful of navigations due to the meager size of localstorage.

Since the cache is only read on first load of a page, it makes sense attempt to reduce the write overhead and restructure this to a write-ahead-log type approach where individual queries to be persisted are queued up to a web-worker, who then handles the persisting away from the main thread. At larger cache sizes, this is critical. Web workers cannot access localstorage, however they _do_ have access to indexeddb which we could use instead. This also comes with a significantly increased quota, from around 5MB in localstorage to 10GB on my machine in firefox, and 300GB (limited only by disk space) in Chrome.

The bottleneck at this point (10s or 100s of MB) becomes JSON serialization speed, but at least it doesn't block the main thread.

### Your minimal, reproducible example

N/A

### Steps to reproduce

- load a number of expensive queries into cache
- observe large freezes as it attempts to evict

### Expected behavior

Better performance

### How often does this bug happen?

Sometimes

### Platform

Fedora, Firefox Developer Edition 106.0b2

### react-query version

3.39.2

**Comment by TkDodo** [comment]
We've basically fixed this with a different approach in v4, which is [retries](https://tanstack.com/query/v4/docs/plugins/createSyncStoragePersister#retries). In v4, per default, there is no retry specified, so you'll get an error on persistence if storage is full.

The standard behaviour of v3, which is to remove the oldest query and try again, is available under the `removeOldestQuery` function, which you can pass to `retry`:

```
const localStoragePersister = createSyncStoragePersister({
  storage: window.localStorage,
  retry: removeOldestQuery
})
```

if you don't like that strategy, you can implement your own. I'm also happy to provide more strategies from the persisters itself. It would be good if the strategies we provide would work synchronously, because sync functions can also work for the async persisters, but not the other way around.

Please understand that we will not invest in fixing this for v3, because the persisters are experimental in v3, but considered stable in v4.

**Comment by arlyon** [comment]
I don't think tagging this as v3 and closing it is appropriate as, unless I am mistaken, the same naive strategy continues to lock up the browser in v4 as well. I would have thought that this would end up as a feature request.
