### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by Ritesh175862** [TanStack/query#4506]
### Describe the bug

we are call useQuery inside usecallback and giving this error

 useFocusEffect(
    useCallback(() => {
      callQuary()//calling useQuery 
    }, [])
  );

### Your minimal, reproducible example

vsCode

### Steps to reproduce

make a function which includes useQuary
call inside useEffect or useCallback

### Expected behavior

As a user useQuary also work inside useEffect or usecallback

### Screenshots or Videos

![Uploading Simulator Screen Shot - iPhone 11 - 2022-11-14 at 12.44.28.png…]()

### Platform

MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
Processor 1.4 GHz Quad-Core Intel Core i5
Memory 8 GB 2133 MHz LPDDR3

### react-query version

3.26.0

### TypeScript version

4.8.4

**Comment by TkDodo** [comment]
this is just how hook work: you cannot invoke them in callbacks.

**Comment by TkDodo** [comment]
what's the alternative when `useState` needs to be called inside something like setTimeout?

This is likely the wrong question to ask. What's the use-case you're trying to solve, then we can figure out what the solution is. "I want to call the hook in setTimeout" is not a question, because the only possible answer is: you can't. But I'm quite certain there is a solution to the actual problem...
