### ISSUE TITLE
`useQuery` is inconsistently updating caching / re-render

### ISSUE THREAD

**Issue by jpmonette** [TanStack/query#4520]
### Describe the bug

We have been using react-query for a little while and really enjoy using the library. In the past few days, we've noticed a first scenario where `useQuery` was successfully fetching data but for some reason not updating the cache / re-rendering our component. We use the library extensively across our codebase and this was the first time we noticed inconsistent re-rendering. We didn't manage to pin point the issue, but luckily, we noticed a second scenario where this is occurring - within a unit test.

### Your minimal, reproducible example

Code available below.

### Steps to reproduce

# First Scenario - Unit test

When running the code below, this is the output we are getting in the console:

```sh
console.log("output data", hasPermission, isLoading);
// output data, undefined, true
console.log("request");
// request
console.log("response", response);
// response {...}
```

The API call succeeds, returns the expected response but doesn't propagate the value back to `PermissionWrapper`

## The React component

```tsx
export const PermissionWrapper: React.FC<PermissionWrapperProps> = ({  component, permission }) => {
  const { data: hasPermission, isLoading } = useHasPermission(permission);
  console.log("output data", hasPermission, isLoading);

  const Component = () => component({ hasPermission, isLoading });

  return <Component />;
};
```

## The hook using `useQuery`

```tsx
export const useHasPermission = (queryParams: string) => {
  const { get } = useRbacApi();

  return useQuery<boolean, Error, boolean, Array<any>>(["permissions", queryParams], async () => {
    console.log("request");
    const response = await get<PermissionsResponse>("/permissions", queryParams);
    console.log("response", response);
    return response.permissions.length !== 0;
  });
};
```

## The unit test

```tsx
import { APIProvider } from "api-client";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { BrowserRouter as Router } from "react-router-dom";
import { NewReportButton } from "./NewReportButton";

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
    },
  },
});

const Wrapper = ({ children }: React.PropsWithChildren) => (
  <Router>
    <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
  </Router>
);

describe("NewReportButton", () => {
  it("should toggle modal", async () => {
    render(
      <Wrapper>
        <PermissionWrapper
          permission={Permissions.ReportBuilder.TemplateReport.Create}
          component={({ hasPermission, isLoading }) => (
            <ButtonWithTooltip
              data-testid="report.create"
              color={"primary"}
              variant={"contained"}
              onClick={toggleModal}
              disabled={!hasPermission}
              loading={isLoading}
              tooltip={!hasPermission ? "You cannot create a new report." : undefined}
            >
              Create New Report
            </ButtonWithTooltip>
          )}
        ></PermissionWrapper>
      </Wrapper>
    );

    await waitFor(() => expect(screen.getByTestId("report.create")).not.toBeDisabled());

    fireEvent.click(screen.getByText("Create New Report"));

    expect(await screen.getByText("Choose a template")).toBeInTheDocument();
  });
});
```

# Second Scenario - Cache not updated on invalidateQuery

In our second scenario, we were using the following code to create a report & invalidate the list of reports so that it would be re-fetched when going back to our list of reports.

## Code

```diff
export const useCreateReport = () => {
  const queryClient = useQueryClient();
  const { create } = useReportLibraryApi();

  return useMutation(
    async ({
      report: reportMetadata,
      configuration,
    }: {
      report: Partial<Report>;
      configuration: Record<string, unknown>;
    }) => {
      const report = await create<Report>(`/reports/`, reportMetadata);
      return await create<Report>(`/reports/${report.id}/run`, configuration);
    },
    {
      onSuccess: report => {
        queryClient.setQueryData(["reports", report.id], () => report);
-        queryClient.invalidateQueries(["reports"]);
+        queryClient.invalidateQueries({ queryKey: ["reports"], exact: true, refetchType: "all" });
      },
    }
  );
};
```

We noticed that `queryClient.invalidateQueries(["reports"]);` was forcing to re-fetch our reports. The API call was executed, the updated data fetched but in one scenario (which we couldn't figure out how to isolate), the fetched data wasn't added to the cache / re-rendering. We tried many things and the only thing that ended up working consistently was to use `queryClient.invalidateQueries({ queryKey: ["reports"], exact: true, refetchType: "all" });` instead.

### Expected behavior

The `PermissionWrapper` should rerender once the response is returned / cache updated in our state. I tried to do the exact same thing without using react-query / useQuery and was able to successfully rerender my component & get the test to pass:

```tsx
export const useHasPermission = (queryParams: string) => {
  const { get } = useRbacApi();

  const [data, setData] = useState<boolean>();

  useEffect(() => {
    (async () => {
      console.log("request");
      const response = await get<PermissionsResponse>("/permissions", queryParams);
      console.log("response", response);
      setData(response.permissions.length !== 0);
    })();
  }, []);

  return { data };
};
```

### How often does this bug happen?

Sometimes

### Platform

- macOS 13.0

### react-query version

4.16.1

### TypeScript version

4.9.3

### Additional context

Hopefully there is something very simple that we are missing that could be figured out from looking at the code snippets. If not, I'll try to use CodeSandbox - I wasn't successful at setting all the pre-requisite to get jest + TypeScript tests running within the environment.

Thanks

**Comment by TkDodo** [comment]
yes please show a codesandbox reproduction.

also, we have to distinguish the terminology between `cache not updating` and `component not re-rendering`. You can inspect the devtools to see what's in the cache. If the data is not in the cache, that would be quite a different issue from "the component not re-rendering".

The only difference in the diff that you've shown:

```diff
- queryClient.invalidateQueries(["reports"]);
+ queryClient.invalidateQueries({ queryKey: ["reports"], exact: true, refetchType: "all" });
```

is the `refetchType`. `exact` actually matches _fewer_ things than the default, fuzzy matching. `refetchType: all` also makes sure that queries that are _inactive_ are refetched. Inactive queries are queries that have no active subscription via useQuery. The devtools also show this.

---

one thing that I am seeing is that this is a really weird anti-pattern in react itself:

```
const Component = () => component({ hasPermission, isLoading });

return <Component />;
```

because it will create a _new_, anonymous component in every render cycle, which then closures over things. That means every invocation of a render equals a mount and a re-mount, because react doesn't now that the two components are the same. For all react knows, you could be rendering a `span` in one cycle and then a `div` in the next. Components need to be referentially stable.

If you are looking for the render-props pattern, what you'd want is actually:

```
return component({ hasPermission, isLoading })
```

but then you cannot do `component={MyComponent}` - it has to be a function. So you need to decide if you want to pass a component reference or a render function.

I'm not sure if this is related to your react-query problem, but it very well could be.

**Comment by jpmonette** [comment]
@TkDodo We managed to isolate the error in a sandbox: https://codesandbox.io/s/jest-testing-react-forked-6tzgl8?file=/src/components/Button.test.tsx

We have 2 tests:

- should work with useQuery
- should work without useQuery

In the current state, the one with React-Query is failing. It seems to be related to our usage of `queryClient.clear();` when an `accountId` is changed, or on first render, that kills the request while it's being executed and never returns the result.

However, by waiting for the clear to be executed before rendering the children using a loading state, it seems to work fine for both scenarios:

```tsx
const Wrapper = ({ children, accountId }: WrapperProps) => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    queryClient.clear();
    setLoading(false);
  }, [accountId]);

  return (
    <Router>
      <ApiContext.Provider value={{ accountId }}>
        <QueryClientProvider client={queryClient}>
          {!loading && children}
        </QueryClientProvider>
      </ApiContext.Provider>
    </Router>
  );
};
```

Is this expected behaviour? If so, what would you recommend us to use when swapping accounts & ensuring that the cache has been cleared / app remains functional?

Thanks

**Comment by TkDodo** [comment]
this seems like a race condition problem: You're clearing the query cache _while_ it is fetching. The useEffect runs _after_ rendering. At that time, the `QueryClientProvider` is already rendered with new data. `clear` also doesn't inform observers about the fact that it has cleared the cache.

it works if you're doing `queryClient.resetQueries` instead, because that does inform subscribers about the clearing and potentially re-fetches:

- https://codesandbox.io/s/jest-testing-react-forked-44wnhb?file=/src/components/Button.test.tsx

it doesn't solve the problem that you are clearing after rendering. `clear` is not a side-effect of rendering - it's likely a side-effect of a user interaction (logout button clicked). So moving the clear into the event handler seems like the better move.

**Comment by jpmonette** [comment]
@TkDodo Makes sense - will use `resetQueries()` in the future and ensure it is in the handler to avoid unexpected race condition.

Thank you very much for the time reviewing this issue as well as your contribution to React-Query - our team really love using the library and it's been very helpful for our project.

**Comment by snehalbaghel** [comment]
Oof was facing the same issue, thanks a lot @TkDodo
