### ISSUE TITLE
React Query prevents the state update

### ISSUE THREAD

**Issue by palaklive** [TanStack/query#4603]
### Describe the bug

[React Example: Nextjs](https://tanstack.com/query/v4/docs/examples/react/nextjs) official demo prevents the state update on the initial click while wrapped with the usePosts hook by React Query.

### Your minimal, reproducible example

https://codesandbox.io/s/github/tanstack/query/tree/main/examples/react/nextjs

### Steps to reproduce

1. Open the [React Example: Nextjs](https://tanstack.com/query/v4/docs/examples/react/nextjs)
2. Visit the Home route and click on the show more - It will not update the state data.
3. Try to click again it'll update the data on the second or third time.
4. Try to relate the page,
5. Follow the same step.

### Expected behavior

State value should get updated with every click. 

### How often does this bug happen?

Everytime

### Screenshots or Videos

https://user-images.githubusercontent.com/26590202/206144996-c441b20b-3920-4de7-9a99-81392f8de90d.mp4

### Platform

- OS: Windows
- Browser: Chrome

### Tanstack Query version

v4.7.1

**Comment by TkDodo** [comment]
what you are seeing is caused by window focus refetch and the iframe that is used in codesandbox:

- when you click the reload button, the browser is actually not focussed because the iframe starts below
- then, you click into the window.
- the window focus event triggers and disables the button (because that is how the example is implemented):

```
<button
  onClick={() => setPostCount(postCount + 10)}
  disabled={isFetching}
>
  {isFetching ? 'Loading...' : 'Show More'}
</button>
```
- then, the button click doesn't work because the button is disabled

none of this will happen in a real application - you can just try it out by opening the codesandbox in a new tab: https://14udt5.sse.codesandbox.io/
