### ISSUE TITLE
useQueries type doesn't support a type narrowed onError

### ISSUE THREAD

**Issue by paul-sachs** [TanStack/query#4767]
### Describe the bug

We currently use a library to build a series of query options with narrowed error types (because we know exactly what error should result from the `queryFn`. `useQuery` works fine with these query options but `useQueries` does not.

This may be related to https://github.com/TanStack/query/discussions/3991 but couldn't find a related issue

### Your minimal, reproducible example

https://codesandbox.io/s/silly-sanderson-e95c55?file=/src/App.tsx

### Steps to reproduce

```tsx
const queryOptions = {
  queryKey: ["hello"],
  onError: (error: Error) => {
    console.error(error.message);
  }
};
const { error } = useQuery(queryOptions);
const [query] = useQueries({
  queries: [queryOptions]
});
```

### Expected behavior

As a user, I expected useQueries to behave similarly to useQuery and accept the same queryOptions.

### How often does this bug happen?

Every time

### Platform

Doesn't make a difference

### TanStack Query version

4.20.9

### TypeScript version

4.9.4

**Comment by TkDodo** [comment]
it's because `Error` needs to be of type `unknown`:

https://codesandbox.io/s/ecstatic-euclid-0936xe?file=/src/App.tsx

The inference trick to provide a different type for `Error` via `onError` only works when inlined.

FYI, in v5, we have moved away from `unknown` and made `Error` the default type, and we're also going to provide a way to override the Error type globally.

Sneak peak (v5 is _not_ yet available): https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5#typescript-error-is-now-the-default-type-for-errors-instead-of-unknown

**Comment by paul-sachs** [comment]
@TkDodo Yeah i expected it was something like that. Alright, thanks for the explanation.
