### ISSUE TITLE
Svelte executes queryFn on server and ignores result

### ISSUE THREAD

**Issue by ottomated** [TanStack/query#4798]
### Describe the bug

When using svelte-query with sveltekit, `createQuery` executes on the server. This causes any client-specific APIs, such as a relative fetch or `window` access, to throw an error. Furthermore, since async SSR must be done in the `load` function in sveltekit, the result of `queryFn` is dropped.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/lucid-architecture-sqwk6e?file=%2Fsrc%2Froutes%2F%2Bpage.svelte

### Steps to reproduce

1. Open the dev logs
2. Reload the page
3. Observe the error being thrown on the server
4. Observe that even though the error is caught, and the string `'error'` is returned, the client renders `undefined` until it finishes fetching

### Expected behavior

I expect `queryFn` only to be called on the client but it is called on the server.

### How often does this bug happen?

Every time

### Platform

- OS: Linux
- Browser: Firefox

### TanStack Query version

4.22.1

### Additional context

Workaround is to add
```ts
import { browser } from '$app/environment';
// ...
queryFn: () => {
    if (!browser) return null;
    // ...
}
```

**Comment by TkDodo** [comment]
@lachlancollins can you have a look?

**Comment by lachlancollins** [comment]
Hi @ottomated , thanks for posting an example- I'm on my phone at the moment but I'll have a good look later. In the meantime, have you looked at https://tanstack.com/query/v4/docs/svelte/ssr ?

**Comment by ottomated** [comment]
> Hi @ottomated , thanks for posting an example- I'm on my phone at the moment but I'll have a good look later. In the meantime, have you looked at https://tanstack.com/query/v4/docs/svelte/ssr ?

Yes, this issue is completely separate from SSR.

**Comment by lachlancollins** [comment]
Hi @ottomated , I think I've been able to track down this error. Since TanStack Query runs queries asynchronously (IDK if this is the perfect way to describe it but you don't await it in the script), the server finishes rendering its HTML, sends that to the client, and then continues running the query itself - when the client receives the HTML, it also runs the query itself. This is made obvious by using a slow endpoint such as the one in `examples/svelte/star-wars`.

This doesn't seem to be a problem with `svelte-query` to me, but rather something to be aware of when using `svelte-query` with SSR. If you're not using any load functions, the easiest solution is to run SvelteKit with `export const ssr = false`. You can use this option on a [per layout or per page basis](`export const ssr = false`). Otherwise, one of the options in [SSR & SvelteKit](https://tanstack.com/query/v4/docs/svelte/ssr) would be necessary.

I'll update the docs with this caveat shortly :)
