### ISSUE TITLE
`onError` called when `enabled: false`

### ISSUE THREAD

**Issue by alicanerdurmaz** [TanStack/query#4827]
### Describe the bug

I have `useQuery` in two different components on the same page. They both use the same `URL` and the same `queryKey`. The default value of one is `enabled: false` and it never changes.

however, `onError` is being called on both of them because it receives an error with `enabled: true`.

Is this behavior expected ? I would expect `onError` with `enabled: false` not to be called

### Your minimal, reproducible example

https://codesandbox.io/s/vigorous-feather-t4tle3?file=/src/index.jsx

### Steps to reproduce

1. Open code sandbox.
2. Check console for errors

### Expected behavior

I would expect `onError` with `enabled: false` not to be called

### How often does this bug happen?

Every time

### Platform

- OS: [macOS, codesandbox]
- Browser: [Chrome, Safari]

### TanStack Query version

4.22.0

**Comment by TkDodo** [comment]
oh yeah interesting. The callbacks are observer level callbacks, so they are supposed to be called once for each observer. Its debatable if the callbacks should be called when the query is disabled. It really depends on what you are using them for.

Looking at the linked issue, I don't think displaying toast notifications in those callbacks is a good idea, as you might also have multiple, enabled observers. The best place for those would be the [global callbacks on the queryCache](https://tanstack.com/query/v4/docs/react/reference/QueryCache#global-callbacks), because they are only called once per query. I also mention this in [one of my blogposts](https://tkdodo.eu/blog/react-query-error-handling#showing-error-notifications).

The stance about enabled is: When an observer is disable, it will _not_ fetch data **on its own**. But you're still subscribed to data / status changes if they happen from somewhere else.

The onSuccess / onError callbacks are tied to a successful or erroneous run of the queryFn. And the queryFn _did_ run - just not because of this observer.

We can fix this technically, it's pretty straight forward (it would need a check for `this.options.enabled` [here](https://github.com/TanStack/query/blob/18e65523c04e25e462000342108881cd049552a1/packages/query-core/src/queryObserver.ts#L640-L644)). I'm just questioning if we _should_ fix this.

I'd like some more opinions on this.

@DamianOsipiuk @ardeora @lachlancollins @tannerlinsley

**Comment by alicanerdurmaz** [comment]
> oh yeah interesting. The callbacks are observer level callbacks, so they are supposed to be called once for each observer. Its debatable if the callbacks should be called when the observer is disabled. It really depends on what you are using them for.
> 
> Looking at the linked issue, I don't think displaying toast notifications in those callbacks is a good idea, as you might also have multiple, enabled observers. The best place for those would be the [global callbacks on the queryCache](https://tanstack.com/query/v4/docs/react/reference/QueryCache#global-callbacks), because they are only called once per query. I also mention this in [one of my blogposts](https://tkdodo.eu/blog/react-query-error-handling#showing-error-notifications).
> 
> The stance about enabled is: When an observer is disable, it will _not_ fetch data **on its own**. But you're still subscribed to data / status changes if they happen from somewhere else.
> 
> The onSuccess / onError callbacks are tied to a successful or erroneous run of the queryFn. And the queryFn _did_ run - just not because of this observer.
> 
> We can fix this technically, it's pretty straight forward (it would need a check for `this.options.enabled` [here](https://github.com/TanStack/query/blob/18e65523c04e25e462000342108881cd049552a1/packages/query-core/src/queryObserver.ts#L640-L644)). I'm just questioning if we _should_ fix this.
> 
> I'd like some more opinions on this.
> 
> @DamianOsipiuk @ardeora @lachlancollins @tannerlinsley

Thanks for the clear explanation 🙏 .

**Comment by songhobby** [comment]
Same error, I don't think thats the expected behaviour. My case is even bizarre as the observer is evaluated to be true on the hook but false when reaching the underlying fetch

**Comment by TkDodo** [comment]
> My case is even bizarre as the observer is evaluated to be true on the hook but false when reaching the underlying fetch

I'm having a hard time understanding that. Could you show a codesandbox example showing this?

**Comment by TkDodo** [comment]
> Hmm I would not tie the callbacks only to the enabled option, cause you might have enabled: false but still invoke refetch manually.
I would expect that callbacks would run in such situation.

That's true!

> Maybe a better way would be to determine if queryFn was triggered (intention of triggering even when deduplicated) by current observer and tie callbacks to this information.
This should handle both enabled and refetch situation.

I don't think this would work, because when there's a refetch on window focus, or when you call `invalidateQueries`, we don't know "which observer" triggered the fetch. Only calling some callbacks might lead to inconsistent state, e.g. if you animate an element in `onSuccess`. In that situation, you might get new data, but if the callback isn't called, you won't get that animation. This gets worse if you use the callback to write some state to local state ...

> On the other hand if they are running always you could place a condition inside the callbacks with the same rule as you are using for enabled prop.

I agree, an additional check for `enabled` condition inside event handlers would be a good workaround.
