### ISSUE TITLE
useQueryErrorResetBoundary() does not resets errorneous useQueries()

### ISSUE THREAD

**Issue by chekrd** [TanStack/query#4874]
### Describe the bug

With useQuery, reset callback runs failed query again. With useQueries nothing happens and the error boundary fallback is unmounted.

### Your minimal, reproducible example

https://codesandbox.io/s/bold-robinson-pu7zl2?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/bold-robinson-pu7zl2?file=/src/App.js
2. Click the "Show component" button.
3. Error boundary renders fallback (correct).
4. Click the "Try again" button.
5. The query is not reset. Also, ErrorBoundary stops rendering the fallback.

You can comment out line 22 and uncomment line 20 for comparison with useQuery. UseQuery correctly resets and fetches again.

### Expected behavior

useQuery and useQueries both should reset erroneous queries when reset() is called.

### How often does this bug happen?

Every time

### Platform

Platform independent

### TanStack Query version

4.22.4

**Comment by pratik-codes** [comment]
is @TkDodo is anyone working on this I would like to work on this

**Comment by TkDodo** [comment]
I talked to @chekrd to take a look because he filed the issue, but you can also take a look if you want. Thanks 🙏

**Comment by TkDodo** [comment]
Thanks for the analysis. I agree that we should focus on fixing #4644 and then hopefully this would be fixed as a side-effect

**Comment by TkDodo** [comment]
A fix for #4644 got merged, but the provided sandbox still seems to fail with the last version (4.29.3). @chekrd FYI

**Comment by TkDodo** [comment]
yes. When the error boundary is reset, it unmounts the error boundary component and re-mounts your component instead. The `retryOnMount` flag is then responsible to decide if you want a refetch now or not. I think with `useErrorBoundary` on, you'd better not want to set that flag to false. However, we also need to flip that internally when suspense is on, due to suspense also unmounting your component. It's weird, and will hopefully get better when maybe moving suspense to a dedicated hook.

**Comment by TkDodo** [comment]
closing this because it now works as expected in `v4.29.3`

**Comment by marklanham** [comment]
Just tried this but it still doesn’t work for me.
