### ISSUE TITLE
Dependant queries: function requires parameter  - ERROR: No overload matches this call

### ISSUE THREAD

**Issue by Sandy-Garrido** [TanStack/query#4942]
### Describe the bug

Using a similar example which is displayed in the docs for Dependant Queries whereby the query options are passed in the first parameter.

https://tanstack.com/query/latest/docs/react/guides/dependent-queries this guide here specifies that it is possible

```javascript
import ky from "ky";
type ResponseData = {
  activity: string;
};
export const getBoredActivity = async (id?: string): Promise<ResponseData> => {
  return await ky
    .get("http://www.boredapi.com/api/activity?key=" + id)
    .then((res) => res.json<ResponseData>());
};
```

```javascript
export const useBoredActivity = (id?: string) => {
  // the ID parameter has to be possible undefined because it could be from an earlier query
  return useQuery({
    queryKey: ["boredActivity", id],  // Typescript error happens here
    queryFn: getBoredActivity,
    enabled: Boolean(id)
  });
};

```

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ queryKey: (string | undefined)[]; queryFn: (id?: string | undefined) => Promise<ResponseData>; enabled: boolean; }' is not assignable to parameter of type 'QueryKey'.
      Object literal may only specify known properties, and 'queryKey' does not exist in type 'readonly unknown[]'.ts(2769)
```

I would expect

### Your minimal, reproducible example

https://codesandbox.io/s/react-query-no-overload-matches-this-call-jzc9lu?file=/src/useBoredActivity.ts

### Steps to reproduce

1. Create a query with the options parameter overload
2. {queryKey, queryFn, enabled}
3. ensure your queryFn requires a parameter

Notice

### Expected behavior

I expect the first parameter to accept the options argument and be okay with the 3 specified options, queryKey, queryFn and enabled.

I expected queryFn to pass the ID parameter to the function I specify

### How often does this bug happen?

Every time

### Platform

macOS / VSCode

### TanStack Query version

^4.12.0

### TypeScript version

^4.8.0

**Comment by TkDodo** [comment]
`getBoredActivity` is a function that takes `id?: string` as input. However, if you pass that function directly to react-query via `queryFn: getBoredActivity`, this interface doesn't match, because react-query passes a [QueryFunctionContext](https://tanstack.com/query/v4/docs/react/guides/query-functions#queryfunctioncontext) to the function, which is an object. It will also not work at runtime.

So you either have to change your `getBoredActivity` to also accept that `QueryFunctionContext`, which contains the `queryKey` so you can extract the id from there, or, just use an inline function:

```
queryFn: () => getBoredActivity(id)
```
