### ISSUE TITLE
useQuery goes to infinite loop if queryFn throws error due to conditional component rendering.

### ISSUE THREAD

**Issue by igoryusha** [TanStack/query#4946]
### Describe the bug

Due to conditional component rendering, hook tries to fetch data every time.

### Your minimal, reproducible example

 https://codesandbox.io/s/infinite-loop-v4-error-fzxovz

### Steps to reproduce

v3:
1. Go to https://codesandbox.io/s/infinite-loop-v3-fine-vchjwt?file=/src/index.js
2. See NO problem.

v4:
1. Go to https://codesandbox.io/s/infinite-loop-v4-error-fzxovz
2. See THE PROBLEM.

### Expected behavior

v4 does the same as v3 - call queryFn only 2 times.

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Chrome 
- Version: 109.0.5414.87 (Official Build) (arm64)

### TanStack Query version

4.24.4

**Comment by mleister97** [comment]
Faced the same issue yesterday.

Imagine a child component is conditionally rendered using the `isLoading` variable of `useQuery` with key Q_KEY.

The child does also use `useQuery` with key Q_Key. This logic will now trigger an infinite loop.

Why? Because the child will try the request again and again changing the `isLoading` varibale of the parent.

For now I am not using the `isLoading` variable anymore and instead check for the data of the query to be `!= null`. Is this the expected behaviour?

**Comment by TkDodo** [comment]
I'm not sure why this behaves the way it did in v3, but believe it or not, the v4 behaviour makes more sense to me, considering:

- parent renders, state is `isLoading`
- `isLoading` becomes false because we are in error state, we render children
- child also uses the same query, this triggers a refetch because we have no data and are in error state, so it's considered stale immediately
  - we go to `isLoading` state because no data and fetching means a "hard loading"
- this `isLoading` state will now trigger the parent again, which unmounts the children
- when the request comes back, the children will mount again, thus repeating this procedure ad infinitum.

Timing might be different in v4 and v3 so that's why this surfaces, but I think the missing piece is "error handling". Why would you render children when you are in error state if those children will then get you straight back to loading again, unmounting themselves? This doesn't make much sense to me. Any kind of error handling (checking for `error` or `isError`, or setting `useErrorBoundary:true`) will do.

You could also set `retryOnMount:false`. From the docs:

> retryOnMount: boolean
If set to false, the query will not be retried on mount if it contains an error. Defaults to true.
