### ISSUE TITLE
isPreviousData is incorrect

### ISSUE THREAD

**Issue by vaynevayne** [TanStack/query#5017]
### Describe the bug

First loading the first page of data // log isPreviousData:false 
 then switching to the second page // log isPreviousData:true  then turn to false ❌.  correct is false turn to  true
  then to the first page, // false ❌.  correct is true

### Your minimal, reproducible example

https://j27d4s.sse.codesandbox.io/

### Steps to reproduce

maybe isPreviousData is reverse

### Expected behavior

if it is first fetch, isPreviousData is false,
if it use cacheData , isPreviousData is true 

### How often does this bug happen?

None

### Platform

macos chrome

### TanStack Query version

^4.19.1

**Comment by TkDodo** [comment]
> if it is first fetch, isPreviousData is false,
if it use cacheData , isPreviousData is true

you're misunderstanding what `keepPreviousData` does. It's not `true` if cached data is used, it's true while we're showing data from the previous queryKey while the queryKey changes, which is exactly what happens when you switch from page1 to page2.

FYI, we'll combine `keepPreviousData` with `placeholderData` in v5. Maybe it makes more sense that way:

- https://github.com/TanStack/query/discussions/4426

**Comment by vaynevayne** [comment]
```jsx 

<LoadingOverlay
            visible={isPreviousData && isFetching}
            zIndex={100}
            overlayBlur={0.3}
          />

```

Excuse me, can I meet my needs by writing like this?
I tried, and he seemed to be the behavior I expected, but I wasn't sure if there were any other problems. @TkDodo
