### ISSUE TITLE
UseQuery causes the page to loop. 

### ISSUE THREAD

**Issue by vaynevayne** [TanStack/query#5062]
### Describe the bug

when  i add useQuery currentUser ,the page is refresh,and  queryCurrentUser method  loop execute

MyHeader component is only has this useQuery,  so it caust bug
 It's hard to reproduce. Please help me to see if I use it incorrectly.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/124666577/222390727-997bc503-9a5b-4d85-83fa-96c69915c499.png">

<img width="632" alt="image" src="https://user-images.githubusercontent.com/124666577/222384162-cef06d4f-3faf-4b38-9a43-8e6cfbf8c8a1.png">

I list all the places where useQueryCurrentUser is used
<img width="757" alt="image" src="https://user-images.githubusercontent.com/124666577/222392819-b6d15b35-8f98-4bd3-802a-60ed43dcc137.png">

```jsx
// app.tsx
import { useCurrentUserQuery } from './hooks/query'
 const { data } = useCurrentUserQuery({
    enabled: false,
  }) 

// I think enabled:false allows me to get the latest data.
For example, if a request has been made elsewhere to modify the data, it will be executed again, which queryClient.getData () can't do, am I using it correctly?
```

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/124666577/222393190-aff2ed17-0db7-4963-aaf3-04f5fcad4c9a.png">

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/124666577/222393770-d07d21d3-22f9-4f7c-8f74-fc7906b427a8.png">

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/124666577/222393948-e397b382-6bcf-4593-b8d3-f3babb7e35cc.png">

finally is login page, i think I think we can get out of here

<img width="954" alt="image" src="https://user-images.githubusercontent.com/124666577/222394060-9c00012d-6d60-46b3-aa24-8b435ac93e67.png">

### Your minimal, reproducible example

https://www.typescriptlang.org/play

### Steps to reproduce

when i add queryCurrentUser to source code 

### Expected behavior

it works well 

### How often does this bug happen?

None

### Platform

macos chrome latest 

### TanStack Query version

  "@tanstack/react-query": "^4.19.1",     "@tanstack/react-query-devtools": "^4.22.0",

**Comment by vaynevayne** [comment]
queryClient is
<img width="758" alt="image" src="https://user-images.githubusercontent.com/124666577/222395873-cacffa50-8e87-4988-92e4-d83fb22e4db6.png">

**Comment by vaynevayne** [comment]
This problem can be fixed by adding stameTime, so is this caused by react-query 's bug?
```jsx
useQuery(currentUserQueryKey, () => axios.get('/currentUser'), {
    staleTime: 2000,
  })
```

**Comment by TkDodo** [comment]
please show a minimal reproduction instead of a bunch of screenshots. We can reopen once we've confirmed that there is an issue on react-query's side.

**Comment by vaynevayne** [comment]
As I said, it's hard to reproduce, if it's easy, I don't mind giving you a demo, and for open source projects, I demo all the time,
The point is: you wrote the project, you know the internal logic very well, I think by screenshots, you can also roughly know what the mistakes are
And I asked if there was anything wrong with the way I was using it, and you didn't answer

**Comment by TkDodo** [comment]
Usually with screenshots, the most important parts are missing. I don't know what's wrong in your code because I can't see it in its entirety. Why is it "hard to reproduce"? Take a codesandbox, start from scratch. Add code from your application until things break. Then you know which part is wrong. Or, remove code from your application until things work. I've even written a blogpost on this topic because it's pretty tiring: https://tkdodo.eu/blog/how-can-i#asking-good-questions

I think you're missing a lot of due diligence on your part. It's not my responsibility to debug your application for you. If you're opening an issue in an open source project, it's to let us know that we have to fix something. Everything else is a discussion. This in the [contribution guidelines](https://github.com/TanStack/query/blob/main/CONTRIBUTING.md#reporting-issues). Did you read them?

I don't really know why I'm even doing this, but what are you doing with `isFetching` in `BasicLayout`? It could be that you're just un-mounting and re-mounting components in a loop, and background refetches because of default staleTime zero will get your query into `isFetching` state again. But I'm just guessing here, because you're not showing the full picture. And no, more screenshots is not the way to go please. We've had issues about this behaviour before - did you take the time to search for closed issues or resolved discussions? like this one:

- https://github.com/TanStack/query/issues/2357
