### ISSUE TITLE
querykeys not being fuzzy matched

### ISSUE THREAD

**Issue by juliusmarminge** [TanStack/query#5111]
### Describe the bug

When filtering queries using `getQueryData`, it seems like the queryKey isn't being fuzzy matched. In tRPC, we have queryKeys like `[["post", "all"], { input: { id: 1 } }]`, and so we should be able to match this by looking for just `[["post", "all"]]`, but that doesn't seem to be the case.

This is the original issue we got: https://github.com/trpc/trpc/issues/3937

### Your minimal, reproducible example

https://stackblitz.com/edit/github-kuehgz-xevj3b?file=package.json

### Steps to reproduce

See stackblitz. The only way you seem to get the data is by looking for the key exactly.

### Expected behavior

`const getQueryData = queryClient.getQueryData(lazyKey);` should return `"hello"`, not `undefined`

### How often does this bug happen?

Every time

### Platform

macOS, Arc

### Tanstack Query adapter

react-query

### TanStack Query version

4.26.1

### TypeScript version

4.8.3

**Comment by TkDodo** [comment]
`getQueryData` doesn't do fuzzy matching - the filter is set to `exact: true`:

https://github.com/TanStack/query/blob/d2af58411fed51f3f8558e3571b7aa82c04d302f/packages/query-core/src/queryCache.ts#L179-L181

General rule of thumb:

- functions with a singular in the name (`getQueryData`) operate on one query, so `exact`
- functions with a pluralr in the name (`invalidateQueries`) operate on multiple queries, so they match fuzzily.

The reason is quite simple:

What would `getQueryData(['todos'])` return if we have the following keys in the cache:

```
['todos', 1],
['todos', { done: true }]
['todos']
```

if we match this fuzzily, it would be non-deterministic which one would be returned. Probably the one that was first inserted, but it's an implementation detail.

I'm not sure what the use-case of yours is, but you can:

- call `queryClient.getQueriesData(key)` to get an Array of all matching queries
- call `queryClieng.getQueryCache().find({ queryKey, exact: false })` but again, if you have multiple matching things, don't rely that you always get the same thing back :)

**Comment by juliusmarminge** [comment]
Alright thanks for the response! Closed our issue too :)

**Comment by juliusmarminge** [comment]
Do you have a section in the docs explaining when you do fuzzy matching? Was going to make a note in our docs about this behavior

**Comment by TkDodo** [comment]
> 
Do you have a section in the docs explaining when you do fuzzy matching? Was going to make a note in our docs about this behavior

hmm, no 🙈 . Filters are fuzzy unless you specify `exact: true`, and some functions do that under the hood. This still applies:

> General rule of thumb:

> functions with a singular in the name (getQueryData) operate on one query, so exact
> functions with a pluralr in the name (invalidateQueries) operate on multiple queries, so they match fuzzily.

If you want, you can add it to the `QueryFilters` page?
https://tanstack.com/query/v4/docs/react/guides/filters
