### ISSUE TITLE
New object reference created during setQueryData

### ISSUE THREAD

**Issue by matthewhuang97** [TanStack/query#5235]
### Describe the bug

Hi! Thanks for this amazing library. I'm running into an issue where it looks like objects being written into the cache, are returned as entirely different objects by reference:

```ts
client.setQueryData(queryKey, [file1, file2]);
client.getQueryData(queryKey);

client.setQueryData(queryKey, [file3, file1, file2]);
client.getQueryData(queryKey);
```

Between the two different calls to `getQueryData`, I'd expect that the value of `file1` stays stable. However, this seems to not be the case. Setting `structuralSharing: false` seems to fix this issue.

The use case here is a local optimistic update, that's adding a file to this query.

### Your minimal, reproducible example

https://codesandbox.io/s/headless-snowflake-5f8wr6?file=/src/App.tsx

### Steps to reproduce

CodeSandbox above!

### Expected behavior

I expected the objects I passed in to be re-used in the cache.

### How often does this bug happen?

Every time

### Platform

Chrome v111.0.5563.146, macOS

### Tanstack Query adapter

None

### TanStack Query version

4.27.0

**Comment by TkDodo** [comment]
when structural sharing is turned on, we try to keep as many references as possible from the source. for this, we step into each and every array and object. So when `file1` is compared with `file3`, we create a new object and copy things over from `file3`, recursively. Then, we compare if the copy is now the same as `file1`, so that we can keep `file1` if necessary. But if not, you'll receive the copy, which is a new instance.

If you seem some way to improve this that doesn't break anything, please let me know. You can try it out by providing a function to `structuralSharing`, so that you can do your own custom comparison if you want.

**Comment by baeharam** [comment]
@TkDodo 

I think if new `data` is plain array, it is valid to check whether a specific element is exist in old `data` array. Is it useless?

In [`replaceEqualDeep` function](https://github.com/TanStack/query/blob/main/packages/query-core/src/utils.ts#L329-L335),

```ts
...
const skippedItemIndicies = [];
for(let i = 0; i < bSize; i++) {
  const sameItem = a.find(aItem => bItems[i]);
  if (sameItem) {
    skippedItemIndicies.push({ bIndex: i, item: sameItem });
  }
}

for (let i = 0; i < bSize; i++) {
  // Find already existing reference element in old array
  const { item } = skippedItemIndicies.find(({ bIndex }) => bIndex === i) ?? {};
  if (item) {
    return item;
  }

  const key = array ? i : bItems[i]

  copy[key] = replaceEqualDeep(a[key], b[key])
  if (copy[key] === a[key]) {
    equalItems++
  }
}
...
```
