### ISSUE TITLE
Mutation data is undefined when mutate inside onSuccess of useQuery

### ISSUE THREAD

**Issue by baeharam** [TanStack/query#5264]
### Describe the bug

The scenario.

1) Query A (with suspense) requests.
2) When query A is succeeded, mutation B is called with `mutate` function.
3) Mutation B is succeeded and query C has to use response data of mutation B.

I expected above case, but it occurs unexpected behaviour.

1) Query A (with suspense) requests and succeeded so mutation B is called.
2) `data` of mutation B is always `undefined` so I cannot use response data of mutation B.

Why mutation data is `undefined` when mutation function is called inside `onSuccess` of suspended `useQuery` ?
Thanks for your reading 😃 

### Your minimal, reproducible example

https://codesandbox.io/s/mutation-with-suspense-onsuccess-hnoxym?file=/src/Test.tsx

### Steps to reproduce

You can `undefined` in console.

### Expected behavior

Mutation `data` has to be updated when mutation is succeeded.

### How often does this bug happen?

Every time

### Platform

MacOS, Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

v4.28.0

**Comment by TkDodo** [comment]
I guess this is because how suspense and useMutation work. suspense unmounts the component, then re-mounts it once fetching has completed. `useMutation` doesn't share data between instances like `useQuery` does. So when you call `useMutation` again, it's a different instance / observer. This observer never had its `mutate` method called - `mutate` was called in `onSuccess` from the "old" observer, because with `suspense`, we call `onSuccess` of the query _before_ the component actually mounts.

The solution here would probably be to move the mutation to a useEffect, because then it will happen when the component has re-mounted again, with the correct instance of useMutation:

https://codesandbox.io/s/mutation-with-suspense-onsuccess-forked-98nyju?file=/src/Test.tsx

Of course, in React18 and strict mode, effect run multiple times in development mode ...

**Comment by baeharam** [comment]
@TkDodo 

Thanks for your clear answer! I understand what u are saying. But, I think it's hard to know that `onSuccess` uses `mutate` function of **"old" observer.** 🤔 So, `onSuccess` could be buggy logic... Is it related to with [your tweet](https://twitter.com/TkDodo/status/1647341498227097600?s=20)?

**Comment by TkDodo** [comment]
no, it's not strictly related to my tweet, though if the callbacks wouldn't exist, you would need an effect and wouldn't have this problem, too.

What you have to understand is that with suspense, callbacks are invoked at a time when your component is not mounted, because react unmounts the component to show the fallback. And the way useMutation works is that it doesn't share data: A new call to useMutation is a completely new instance. That is on purpose, because you can also call `mutate()` multiple times and useMutation will only track the latest invocation.

In v5, we have a `useMutationState` hook that will give you access to the state of all mutations. This wold likely give you data in your case as well:

https://tanstack.com/query/v5/docs/react/reference/useMutationState
