### ISSUE TITLE
`Error: No QueryClient set, use QueryClientProvider to set one` with any version after 4.2.3

### ISSUE THREAD

**Issue by italodeandra** [TanStack/query#5278]
### Describe the bug

I have a Next.js 13 application which has installed a library I created myself which exports CJS (because Next.js builds a CJS version and don't allow me to export ESM).

This library exports several reusable code where I use React Query. It used to work flawless, but when I try to update React Query to any version after 4.2.3, I started getting this context error.

I saw some suggestions on Discord, here on Open/Closed Issues and also on Discussions tabs. But none worked.

### Expected behavior

I expected the app to build with any error.

### How often does this bug happen?

Every time

### Platform

Windows Chrome LTS

### Tanstack Query adapter

react-query

### TanStack Query version

Any after 4.2.3

**Comment by TkDodo** [comment]
as always, we can't do anything without a standalone reproduction.

**Comment by TkDodo** [comment]
more empathy? I could ask the same of you. Opening an issue in a library means "your library has an issue". To make such a claim, you have to show some proof. This is stated in the [contribution guidelines](https://github.com/TanStack/query/blob/main/CONTRIBUTING.md#reporting-issues). Have you read them before opening an "issue" ?

We don't have a small number of issues because we just close all of them - it's because we actively address all issues that are proven to be issues in the library. The vast majority of issues opened are either misconfigurations, or misunderstandings, or have something to do with configuration. Do you know how many times I'm asking users for a reproduction? A lot of the time, when trying to create a reproduction, people find out that it actually works in a sandbox and that the issue has absolutely nothing to do with the library. If that's the case, why should library maintainers invest time to look into it. For free nonetheless.

If you think that it's **my** responsibility to make a reproduction with next13 and a library that is built using react-query just to show you that it works, please think again. If I do this for every issue opened, I'd be doing nothing else 24/7. 

I also wrote a blogpost about situations like these: https://tkdodo.eu/blog/how-can-i#3-provide-a-minimal-reproducible-example

> But that's okay, I'll create a discussion instead, perhaps I can find someone willing to help there.

take a look at the discussions, you'll see that we attend to most of them. But your question is so generic, anyone will have a hard time investigating that. We don't know how you built your library. We don't see any code about what you are doing with the library. Have you setup peerDependencies correctly? There are so many things that can factor into this....

**Comment by italodeandra** [comment]
> We don't know how you built your library. We don't see any code about what you are doing with the library. Have you setup peerDependencies correctly? There are so many things that can factor into this....

This is just one example of how you could have answered the first time instead of just closing the issue.

**Comment by TkDodo** [comment]
> This is just one example of how you could have answered the first time instead of just closing the issue. That's what I mean by empathy. Trying to understand my issue, get more information, instead of just "not enough information"

I would have all the answers to those questions if you actually provided a reproduction. "It used to work, now it doesn't, I except it to work" is not helpful at all. It looks like you just don't want to put in the effort to create a reproduction. But you expect others to look into it

**Comment by italodeandra** [comment]
Not really. I just wanted help. I can't reproduce. Some insights would have been enough, maybe the right question would have helped me fix by looking for it. But like I said, I don't agree that I was wrong looking for help here, even though I don't have the holy grail reproduction.
