### ISSUE TITLE
Mutations can not be started from an effect in Reacts StrictMode

### ISSUE THREAD

**Issue by jakst** [TanStack/query#5341]
### Describe the bug

When firing a mutation from a useEffect on component creation the mutation get's stuck in loading state, despite the underlying request finishing. This only seems to happen in Reacts StrictMode.

If you naively do this you won't notice the bug, because this effect will fire twice in StrictMode and therefore "unstuck" the mutation when the request is sent the second time.
```typescript
useEffect(() => {
  if (isIdle) mutate()
}, [isIdle, mutate])
```
That's why the codesandbox example has a ref that keeps track on if the mutation has fired, to ensure it only runs once.

_The reason we're doing this in the first place is because we need to fire several mutations and keep track of the loading states individually, so we use components to create several mutation instances and fire the mutations on effect instead of in the original event handler._

### Your minimal, reproducible example

https://codesandbox.io/s/mutation-with-suspense-onsuccess-forked-lkmo6v?file=/src/Test.tsx

### Steps to reproduce

1. Go to attached codesandbox
2. Observe that the two loading states differ (reload if you have to)

### Expected behavior

I expect react-query's loading state to have the same value as the manually coded loading state

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Browser: Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

v4.28

### TypeScript version

v5.0.4

**Comment by TkDodo** [comment]
the problem is that your `hasFired` ref workaround seems to screw things up. working sandbox: 
https://codesandbox.io/s/mutation-with-suspense-onsuccess-forked-2gekg2?file=/src/Test.tsx

If you don't want mutations to fire twice, either don't put them in a useEffect (they should likely run in event handlers anyways), or turn off strict mode

**Comment by jakst** [comment]
> the problem is that your `hasFired` ref workaround seems to screw things up. working sandbox: 
> https://codesandbox.io/s/mutation-with-suspense-onsuccess-forked-2gekg2?file=/src/Test.tsx

Yeah but your modified example **only works** because it's firing twice. The first call gets stuck on loading, and then the second one unstucks it. Do you mean that you do not consider this a bug?

> If you don't want mutations to fire twice, either don't put them in a useEffect (they should likely run in event handlers anyways), or turn off strict mode

Yeah I would definitely prefer to run it in the event handler, but for our use case there is no way to do this with react-query AFAICT.

We want to fire an unknown amount of mutations with the same useMutation hook from our event handler, and then track each loading state individually. In some other issue thread I found your reply saying a solution was to run the mutation in the leaf component and trigger it on effect, so I figured that would be a reasonable way forward.

Is there any other pattern we could use here?

**Comment by TkDodo** [comment]
> The first call gets stuck on loading, and then the second one unstucks it. Do you mean that you do not consider this a bug?

I don't think that's true. Every time we call `mutate`, we get a new Mutation instance in the cache - that's how mutation works. In my example, if I inspect all mutations, I will see two mutations in success state. Click the button in this sandbox after it goes to `DONE`:

https://codesandbox.io/s/mutation-with-suspense-onsuccess-forked-ebm2ym?file=/src/Test.tsx

You will find two mutations, both being in `success` state. So, there is nothing stuck.

If I do the same thing in your example, there is only one mutation, and it is also in success state - but it doesn't have any observers. That's because strict mode unmounts the component and mounts it again, which takes away the observer. So, it seems that the component has rendered an observer that is no longer there, because it was unmounted by react.

I have to admit that this is really weird, but it's not something that I would try to work around with a ref. What StrictMode wants to simulate is: what happens if you the user quickly navigates away from the component and then comes back to it, because that's what the offscreen API (from react) might introduce: effects might then fire when you scroll the page down and up again (to the best of my knowledge). if you're not comfortable with effects firing multiple times, you really shouldn't be using an effect.

> We want to fire an unknown amount of mutations with the same useMutation hook from our event handler, and then track each loading state individually. In some other issue thread I found your reply saying a solution was to run the mutation in the leaf component and trigger it on effect, so I figured that would be a reasonable way forward.

Not sure where I said that 😅 . Firing a mutation multiple times from the same `useMutation` is possible, but you'll only track the latest state. If that's not what you want, the best solution is to invoke individual `useMutation` calls on the leaves and then call `mutate` for each on their own instance, so that they all have their own loading states.

In v5, we'll introduce a `useMutationState` hook that can track states for mutations, even when they have been fired by the same `useMutation` call, and over multiple components. It seems that this hook will return the proper state:

- https://codesandbox.io/s/mutation-with-suspense-onsuccess-forked-xpplu5?file=/src/Test.tsx
- https://tanstack.com/query/v5/docs/react/reference/useMutationState

**Comment by aconrad** [comment]
I have the same problem where `useMutation`'s `isLoading` is stuck on `true`. This only happens with React 18's `<StrictMode>...</StrictMode>`. Here's my illustration:

https://codesandbox.io/s/mutation-with-suspense-onsuccess-forked-c7wd41?file=/src/Test.tsx

If we remove `<React.StrictMode>` from the `index.tsx` file, it works as intended.

Using:
* `"@tanstack/react-query": "4.24.9",`
* `"react": "18.2.0",`

Side note: In my app, I noticed that `isLoading` isn't stuck when doing a full-page load (e.g. entering the URL in the browser) vs. if I'm navigating to that page using react-router's `<Link />` navigation.

**Comment by aconrad** [comment]
I realize that I was doing a mutation as part of the render process (at the top-level of the component). So I wrapped the mutation call in a `useEffect()` and it works just fine.

**Comment by YassienW** [comment]
> I have to admit that this is really weird, but it's not something that I would try to work around with a ref. What StrictMode wants to simulate is: what happens if you the user quickly navigates away from the component and then comes back to it, because that's what the offscreen API (from react) might introduce: effects might then fire when you scroll the page down and up again (to the best of my knowledge). if you're not comfortable with effects firing multiple times, you really shouldn't be using an effect.


@TkDodo What should i do if i want to call a non idempotent POST request (mutation in this case) once the component mounts? I don't see any way other than a useEffect

**Comment by TkDodo** [comment]
> @TkDodo What should i do if i want to call a non idempotent POST request (mutation in this case) once the component mounts? I don't see any way other than a useEffect

mutations shouldn't be side-effects of components rendering or mounting. That's what StricMode is trying to tell us. Users can go to your page, navigate back and go there again. Then, you'll also have two mutations. In the future, React might do the same thing with their planned offscreen api.

**Comment by YassienW** [comment]
This is all great in theory, but what should one do if the business requires this? A resource must be created one time when a page is opened for the first time. I can't think of a way to call the request other than as a reaction to the component mounting

**Comment by TkDodo** [comment]
What is the business requirement ?

Anyways, there is no change in production. Let it fire twice in dev mode, it's fine in prod 🤷

**Comment by YassienW** [comment]
A subscription is created when the user opens the on-boarding page for the first time. Which ends up creating 2 of them in dev.
I could just ignore the issue in dev and production will work fine, i was just hoping i could avoid the issue completely.

**Comment by TkDodo** [comment]
sounds like you're missing an unsubscribe in the cleanup

**Comment by YassienW** [comment]
It's not a subscription to a socket, event, etc. It's a resource that is created and shouldn't be deleted on cleanup

**Comment by TkDodo** [comment]
sorry, I'm not going to invest time into issues caused by workarounds (refs) to make StrictMode not do something in dev mode that it's intended to do. You can:

- ignore the double fire, as it only happens in dev and not in prod
- not use strict mode
- not fire a mutation in useEffect
- fire a request in useEffect without react-query's mutations and re-add your ref workaround

**Comment by dtinth** [comment]
My use case is this:

- User logs in from an OAuth provider. The provider redirects user back to a callback page. Maybe it’s using PKCE or something so it’s fine to do this client side.
- Now we are implementing an OAuth callback page, so, as soon as a callback page is mounted, the page component should attempt to use the code to sign the user in.

```js
export default function () {
  const mutation = useMutation({
    mutationFn: async () => {
      const params = new URLSearchParams(window.location.search)
      const code = params.get('code')
      const state = params.get('state')
      // ...
    },
  })
  useEffect(() => {
    mutation.mutate()
  }, [])
  // ...
}
```

The problem is that, in the above, `mutationFn` is called twice.

We could have used `useQuery` here, but the act of signing in is a mutation, so it doesn’t make much sense to use `useQuery` here. We also don’t want to deal with automatic retries and automatic refetching, i.e. we want the "mutation" behavior.

Using `useRef` to only call `mutation.mutate()` does not work, as per this comment: https://github.com/TanStack/query/issues/5341#issuecomment-1527727996

> mutations shouldn't be side-effects of components rendering or mounting.

We oftentimes have to implement pages/routes whose sole purpose is to perform some action after loading, and then redirect user to another page. OAuth callbacks for public clients is one example. Payment processing is another example.

> That's what StrictMode is trying to tell us. Users can go to your page, navigate back and go there again. Then, you'll also have two mutations.

…and this is the solution:

<img alt="image" src="https://github.com/TanStack/query/assets/193136/47299913-793c-4cb5-9f19-868357c48c7e">

Currently we work around it like this:

```ts
// Move the mutation code outside the component,
// and use some extra logic to prevent it from running simultaneously.
let activeSignInPromise: Promise<void> | null = null
function signIn() {
  if (!activeSignInPromise) {
    activeSignInPromise = (async () => {
      try {
        const params = new URLSearchParams(window.location.search)
        const code = params.get('code')
        const state = params.get('state')
        // ...
      } finally {
        activeSignInPromise = null
      }
    })()
  }
  return activeSignInPromise
}

export default function () {
  const mutation = useMutation({ mutationFn: signIn })
  useEffect(() => {
    mutation.mutate()
  }, [])
  // ...
}
```

…but I couldn’t expect junior devs to know how to implement this, therefore I wish there is an easier way to do it with React Query.

> don't put them in a useEffect (they should likely run in event handlers anyways)

I would love to put it in event handlers too! But is there any event suitable for implementing such callback page? I would like to avoid something like this if possible:

```js
<img
  src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=='
  alt=''
  onLoad={() => mutation.mutate()}
/>
```

Any suggestion is appreciated.

**Comment by rofreytag** [comment]
I ran into the exact same issue: after I fire the mutation once, the `status` is stuck in `pending`. The underlying mutation fires `onSuccess`, so why does it not transition to the `success` state? This _is_ a bug.

In our case we need to POST once for a given combination of data. The `useEffect` dependencies make sure we only fire once for that combination. We use the `useRef` workaround to avoid firing twice in react-strict mode. Any workaround makes the code even more unreadable.

```
  const currentRun = useRef('');
  const { mutate, isSuccess, status } = useMyCustomMutation();

  useEffect(() => {
    if (eventId && 
      user?.id && 
      currentRun.current !== `${eventId}-${user.id}`) {
      currentRun.current = `${eventId}-${user.id}`;
      console.log("firing effect")
      mutate({
        eventId,
        userId: user.id,
      })
    }
  }, [mutate, eventId, user?.id]);
```

Please fix this.

**Comment by TkDodo** [comment]
in case it helps, in v5, you can `useMutationState` to subscribe to values directly from the cache, so that works as you'd expect:

https://codesandbox.io/s/mutation-with-suspense-onsuccess-forked-vy4fsc?file=/src/Test.tsx

**Comment by ruslan-simonenko** [comment]
I have spent around an hour trying to figure out why my query was not completing properly, and finally found this bug. Quite surprised that it is closed.

@TkDodo the fact that this happens only in dev mode is irrelevant to it being an issue - if something isn't working in dev mode, then engineers certainly won't push the code into production.

If fixing this bug is too time consuming, then do you think it deserves a mention in the docs? Especially considerig that useEffect with ref is the official way of ensuring that something fires once on mount in React.

I ended up using `setTimeout` workaround - seems to fix the issue:

```
useEffect(() => {
    if (activeSessionID.current === sessionID) {
      return;
    }
    activeSessionID.current = sessionID;
    setTimeout(() => verifyPayment({ sessionID }), 0); // << makes mutation complete properly
  }, [verifyPayment, sessionID]);
```

**Comment by nishantpal1911** [comment]
> in case it helps, in v5, you can `useMutationState` to subscribe to values directly from the cache, so that works as you'd expect:
> 
> https://codesandbox.io/s/mutation-with-suspense-onsuccess-forked-vy4fsc?file=/src/Test.tsx

The `useMutationState` hook fixes the issue. Here are two custom hooks to ensure that any mutations that start in `useEffect` will be run once (even in `StrictMode`) and always return the correct mutation state (straight from the cache).
I've also made `options.scope` as required to ensure that even if multiple mutation calls are made somehow, they will be run serially. Feel free to drop it as per use case.
This approach will be useful for the non-idempotent API calls that need to be made on component mount.
```ts
// src/hooks/effect.ts

const useEffectOnce = (effect: React.EffectCallback) => {
  const didRun = useRef(false);

  useEffect(() => {
    if (!didRun.current) {
      didRun.current = true;
      const destructor = effect();
      if (destructor) return destructor;
    }

    return () => {};
  }, [effect]);
};

export default useEffectOnce;
```
```ts
// src/hooks/mutation.ts

type MutationOptions<TData = unknown, TError = DefaultError, TVariables = void, TContext = unknown> = Required<
  Pick<UseMutationOptions<TData, TError, TVariables, TContext>, 'scope'>
> &
  Omit<UseMutationOptions<TData, TError, TVariables, TContext>, 'mutationKey'>;

type IsPending = { isPending: boolean };

const useGlobalSyncMutation = <TData = unknown, TError = DefaultError, TVariables = void, TContext = unknown>(
  options: MutationOptions<TData, TError, TVariables, TContext>,
  queryClient?: QueryClient
): Omit<UseMutationResult<TData, TError, TVariables, TContext>, 'isPending'> & IsPending => {
  const mutationResults = useMutation({ ...options, mutationKey: [options.scope.id] }, queryClient);
  const mutationStates = useMutationState({
    filters: { mutationKey: [options.scope.id], exact: true },
    select: (mutation) => mutation.state.status,
  });
  const lastMutationState = mutationStates[mutationStates.length - 1];
  const isPending = lastMutationState === 'pending';

  return {
    ...mutationResults,
    mutate: (...params: [TVariables]) => {
      if (!isPending) {
        mutationResults.mutate(...params);
      }
    },
    isPending,
    isIdle: !lastMutationState || lastMutationState === 'idle',
    isSuccess: lastMutationState === 'success',
    isError: lastMutationState === 'error',
  };
};
```

**Comment by Ilya-Valasiuk** [comment]
I have similar problem where I need to call mutation from `useEffect`.

I used `debounce` and it looks like it works well in my case.

Example:

```
const doRefreshToken = useCallback(() => {
    refresh(undefined, {
      onError: () => {
        ...
      },
    });
  }, [refresh, router]);

  /**
   * Github issue https://github.com/TanStack/query/issues/5341
   * Prevent double call in react strict mode.
   *  */
  const doRefreshTokenDebounced = useDebounceCallback(doRefreshToken, 100);

useEffect(() => {
  doRefreshTokenDebounced();
}, [doRefreshTokenDebounced])
```

**Comment by dorlanpabon** [comment]
I’ve found a potential solution to prevent the double invocation of useMutation in React’s StrictMode. This approach uses a useRef to track if the mutation has already been executed, effectively avoiding the unintended behavior in StrictMode. Here’s the code:


``
import { useMutation, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';
import { useRef, useEffect } from 'react';

interface StrictModeMutationOptions<TData, TError, TVariables, TContext>
  extends UseMutationOptions<TData, TError, TVariables, TContext> {
  mutationFn: (variables: TVariables) => Promise<TData>;
}

export function useStrictModeMutation<TData = unknown, TError = unknown, TVariables = void, TContext = unknown>(
  options: StrictModeMutationOptions<TData, TError, TVariables, TContext>
): UseMutationResult<TData, TError, TVariables, TContext> {

  // `hasRun` keeps track of whether the mutation has been executed in `StrictMode`
  const hasRun = useRef(false);

  // Set up the React Query mutation
  const mutation = useMutation<TData, TError, TVariables, TContext>(options);

  // Conditional mutation function to prevent double execution
  const strictModeMutate = (variables: TVariables) => {
    if (!hasRun.current) {
      hasRun.current = true;
      mutation.mutate(variables);
    }
  };

  // Reset `hasRun` when mutation returns to `idle`
  useEffect(() => {
    if (mutation.status === 'idle') {
      hasRun.current = false;
    }
  }, [mutation.status]);

  // Return the mutation with `strictModeMutate` instead of `mutate`
  return { ...mutation, mutate: strictModeMutate };
}
``

**Comment by dorlanpabon** [comment]
I’ve implemented a solution to address the double-invocation issue of useMutation in React StrictMode by adding a conditional check using useRef. This approach also includes a custom reset function to allow the mutation to be re-triggered when needed. Here’s the code:


```tsx
import { useMutation, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';
import { useRef } from 'react';

interface StrictModeMutationOptions<TData, TError, TVariables, TContext>
  extends UseMutationOptions<TData, TError, TVariables, TContext> {
  mutationFn: (variables: TVariables) => Promise<TData>;
}

export function useStrictModeMutation<TData = unknown, TError = unknown, TVariables = void, TContext = unknown>(
  options: StrictModeMutationOptions<TData, TError, TVariables, TContext>
): UseMutationResult<TData, TError, TVariables, TContext> {

  // `hasRun` tracks if the mutation has already been executed
  const hasRun = useRef(false);

  // Setting up the mutation with React Query
  const mutation = useMutation<TData, TError, TVariables, TContext>(options);

  // Conditional mutation function to prevent double execution
  const strictModeMutate = (variables: TVariables) => {
    if (!hasRun.current) {
      hasRun.current = true;
      mutation.mutate(variables);
    }
  };

  // Custom reset function to allow the mutation to be re-triggered
  const reset = () => {
    hasRun.current = false;
    mutation.reset();
  };

  // Return the mutation with `strictModeMutate` instead of `mutate`
  return { ...mutation, mutate: strictModeMutate, reset };
}

```


This example shows how to use the reset function to re-trigger the mutation in the component:

```tsx
import React, { useEffect } from 'react';
import { useStrictModeMutation } from './useStrictModeMutation';

const MyComponent = () => {
  const { mutate, isLoading, isSuccess, isError, reset } = useStrictModeMutation({
    mutationFn: async (data) => {
      // Simulate an API call
      const response = await fetch('/api/resource', {
        method: 'POST',
        body: JSON.stringify(data),
        headers: { 'Content-Type': 'application/json' },
      });
      return response.json();
    },
  });

  useEffect(() => {
    mutate({ id: 1, name: 'Sample Data' });
  }, [mutate]);

  return (
    <div>
      {isLoading && <p>Loading...</p>}
      {isSuccess && (
        <>
          <p>Mutation succeeded!</p>
          <button onClick={reset}>Run Again</button>
        </>
      )}
      {isError && <p>There was an error.</p>}
    </div>
  );
};

export default MyComponent;
```

This solution prevents double execution in StrictMode, allows manual resets, and keeps the mutation state controlled. It should help prevent issues related to non-idempotent mutations in StrictMode, where multiple renders can cause unexpected behavior. I hope this helps others facing similar issues!

Please let me know if you spot any issues or if there are areas that could be improved. I’d be happy to refine this solution further based on any feedback!

**Comment by komali2** [comment]
Hello,

We're having issues with this as well, regarding the creation of an auth token after redirecting from auth0. 

> ignore the double fire, as it only happens in dev and not in prod

I don't ship known buggy code.
 
> not use strict mode

For the same reason I don't use `@ts-ignore`, I can't do this. 

> not fire a mutation in useEffect

Happy to. In react, what's the recommended way to run code on a component rendering, once, based on dependencies, other than useEffect? I've googled and found nothing. 

> fire a request in useEffect without react-query's mutations and re-add your ref workaround

Then the data I get back from our post request isn't available in the tanstack query state, unless I guess I add it manually? It seems odd.

**Comment by Jdruwe** [comment]
> > in case it helps, in v5, you can `useMutationState` to subscribe to values directly from the cache, so that works as you'd expect:
> > https://codesandbox.io/s/mutation-with-suspense-onsuccess-forked-vy4fsc?file=/src/Test.tsx
> 
> The `useMutationState` hook fixes the issue. Here are two custom hooks to ensure that any mutations that start in `useEffect` will be run once (even in `StrictMode`) and always return the correct mutation state (straight from the cache). I've also made `options.scope` as required to ensure that even if multiple mutation calls are made somehow, they will be run serially. Feel free to drop it as per use case. This approach will be useful for the non-idempotent API calls that need to be made on component mount.
> 
> // src/hooks/effect.ts
> 
> const useEffectOnce = (effect: React.EffectCallback) => {
>   const didRun = useRef(false);
> 
>   useEffect(() => {
>     if (!didRun.current) {
>       didRun.current = true;
>       const destructor = effect();
>       if (destructor) return destructor;
>     }
> 
>     return () => {};
>   }, [effect]);
> };
> // src/hooks/mutation.ts
> 
> type MutationOptions<TData = unknown, TError = DefaultError, TVariables = void, TContext = unknown> = Required<
>   Pick<UseMutationOptions<TData, TError, TVariables, TContext>, 'scope'>
> > &
>   Omit<UseMutationOptions<TData, TError, TVariables, TContext>, 'mutationKey'>;
> 
> type IsPending = { isPending: boolean };
> 
> const useGlobalSyncMutation = <TData = unknown, TError = DefaultError, TVariables = void, TContext = unknown>(
>   options: MutationOptions<TData, TError, TVariables, TContext>,
>   queryClient?: QueryClient
> ): Omit<UseMutationResult<TData, TError, TVariables, TContext>, 'isPending'> & IsPending => {
>   const mutationResults = useMutation({ ...options, mutationKey: [options.scope.id] }, queryClient);
>   const mutationStates = useMutationState({
>     filters: { mutationKey: [options.scope.id], exact: true },
>     select: (mutation) => mutation.state.status,
>   });
>   const lastMutationState = mutationStates[mutationStates.length - 1];
>   const isPending = lastMutationState === 'pending';
> 
>   return {
>     ...mutationResults,
>     mutate: (...params: [TVariables]) => {
>       if (!isPending) {
>         mutationResults.mutate(...params);
>       }
>     },
>     isPending,
>     isIdle: !lastMutationState || lastMutationState === 'idle',
>     isSuccess: lastMutationState === 'success',
>     isError: lastMutationState === 'error',
>   };
> };

Did something similar, thanks for the inspiration

**Comment by florianmatz** [comment]
Isn’t it possible to useQuery for a ‘one time mutation on mount’ combined with a stale time of Infinity? I mean after all the query fn is just an asynchronous function?

Stumbled across this topic as I need to perform an upload on mount (and cannot use an event handler for some reasons).


@TkDodo ?

**Comment by TkDodo** [comment]
not recommended because queries can still re-run, e.g. if they get garbage collected or if invalidation marks it as “invalid”. You can surely work around it but I wouldn’t recommmend it.

**Comment by Szorcu** [comment]
I've run into the exact same scenario as @dtinth described in https://github.com/TanStack/query/issues/5341#issuecomment-1667408136.

We are implementing the SSO/OAuth callback page, and I am having a hard time finding a clean way to trigger a mutation only once on mount. I think it's a very valid and quite popular scenario where mutation by design has to be called in `useEffect` - a page that is solely responsible for performing a mutation immediately on load and then redirecting the user or closing the window.

I’m wondering whether the following pattern is still considered the recommended workaround, or if there’s now a better approach:

```tsx
const { mutate } = useMutation(...);

const hasRun = useRef(false);

useEffect(() => {
  if (hasRun.current) {
      return;
  }

  hasRun.current = true;
  const timeout = setTimeout(() => mutate(), 0);

  return () => { 
      clearTimeout(timeout);
  };
}, [mutate]);
```

It would be great if the docs or examples could cover this use case since it seems fairly common in practice.

**Comment by TkDodo** [comment]
the fix is to _not_ skip the second run and accept the two requests in dev mode, or turn off strict mode, or move the request to a route loader

**Comment by ErikGro** [comment]
These are not fixes, these are workarounds

**Comment by TkDodo** [comment]
conceptually, a mutation shouldn’t happen as a side-effect of rendering

**Comment by dtinth** [comment]
It appears from the comments that, 2 years later, people still keep running into this issue, which makes me think if something should be done about it.

For example, I think it might be great if `useMutation` has an option like (e.g.) `autoMutateKey` which causes the mutation to automatically run when the key changes in a similar fashion to `useQuery`’s `queryKey` (however, unlike `useQuery`, the auto-mutate key is locally scoped to the component that renders it), then we can tell people to never use `mutate()` inside `useEffect()`, while also providing an adequate alternative (or ‘escape hatch’).

**Comment by RSATom** [comment]
After some digging into sources I've got some idea about possible reason of issue. And I think reason is here: 
https://github.com/TanStack/query/blob/38b40081cedd207285ac0b4bb6818a2e84704b95/packages/react-query/src/useMutation.ts#L30-L36

The problem is, with StrictMode enabled, React calls state init function **twice**. But always uses reference created **on the first call**. And it's correct behavior, since according to [React useState docs](https://react.dev/reference/react/useState#parameters):
```
If you pass a function as initialState, it will be treated as an initializer function. It should be **pure**,
should take no arguments, and should return a value of any type. 
```
According to [wiki](https://en.wikipedia.org/wiki/Pure_function) :

<img width="930" height="154" alt="Image" src="https://github.com/user-attachments/assets/1f8cdc99-9243-462f-b25e-2e530628b5db" />

key here "the function has no side effects", but I have a feeling it's not true for `new MutationObserver` .

I have some ideas how to fix it, so going to do some experiments....

**Comment by RSATom** [comment]
I was wrong, the problem is inside
https://github.com/TanStack/query/blob/38b40081cedd207285ac0b4bb6818a2e84704b95/packages/react-query/src/useMutation.ts#L42-L50

and if be more specific here:
https://github.com/TanStack/query/blob/38b40081cedd207285ac0b4bb6818a2e84704b95/packages/query-core/src/mutationObserver.ts#L96-L100

observer is removing before second `useSyncExternalStore` call...

**Comment by RSATom** [comment]
finally was able to get it working by commenting following line of code:

https://github.com/TanStack/query/blob/c9bc6002ad856e349ad15a7d07e3dac251e8c022/packages/query-core/src/mutationObserver.ts#L98

But I'm not sure if this change can break something else...

**Comment by aza547** [comment]
> conceptually, a mutation shouldn’t happen as a side-effect of rendering

I may be stupid but is this reflected in the docs? I couldn't find it if so.

I also ran into this today implementing an OAuth callback.

Workaround from @dtinth works great but this has definitely dampened my enthusiasm for ReactQuery.
