### ISSUE TITLE
Svelte - Update not triggering after mutation and `invalidateQueries`

### ISSUE THREAD

**Issue by inzanez** [TanStack/query#5351]
### Describe the bug

When stripping down the example in the CodeSandbox (especially removing the '...isFetching'), updates to objects are not triggering correctly. At least elements depending on the store created by `createQuery` do not re-render, although the underlying list changes (and things depending on that list rerender instantly).

I modified the sample in the way because noticed that simple mutations followed by `invalidateQueries` does not seem to re-trigger rendering although the items are refetched in the background.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/peaceful-chebyshev-g1k6rq?file=%2Fsrc%2Froutes%2FEditTodo.svelte&selection=%5B%7B%22endColumn%22%3A9%2C%22endLineNumber%22%3A85%2C%22startColumn%22%3A9%2C%22startLineNumber%22%3A85%7D%5D

### Steps to reproduce

In the CodeSandbox:
On top there is the list of fruits. Clicking `Edit` will open the editor at the bottom.
Directly above the editor, the same list is rendered but directly from the source store (which is the 'mock API data'). Editing a name and clicking save will modify the entry causing the list rendered from the store to update, but the list on top will not update....

Adding another todo however will update everything.

### Expected behavior

I would would expect the components to re-render.

### How often does this bug happen?

Every time

### Platform

Linux, Chromium, Version 112.0.5615.49 (Official Build) (64-bit)

### Tanstack Query adapter

svelte-query

### TanStack Query version

4.29.1

### TypeScript version

5.0.0

**Comment by TkDodo** [comment]
@lachlancollins can you have a look please?

**Comment by lachlancollins** [comment]
Hi @inzanez , I'm a bit confused about what the bug here is. The behaviour on the [React playground](https://tanstack.com/query/latest/docs/react/examples/react/playground) is identical to the [Svelte playground](https://tanstack.com/query/latest/docs/svelte/examples/svelte/playground), which I'm assuming you build this example from.

These examples have an artificial delay in all requests which highlights the different steps in querying/mutating. When you click "save", it sends a mutation, with a built-in delay. Once the mutation is complete, it displays "saved", and invalidates the query. Then, the query begins fetching, again with a built-in delay. Once the query is complete, the updated list will render.

Please let me know if I've missed the issue, and if so try out both the React and Svelte examples to confirm it's a svelte-specific issue.

**Comment by inzanez** [comment]
@lachlancollins Yes,...I think you missed the issue here. I modified the Svelte playground as you can see. And it does indeed store the update and refetch the data, but it does not re-render the list as it should. At least not in the very minimal example I created by editing the playground.
I think the important part is that it is not about the actual playground but about stripped down version I linked to above.

**Comment by inzanez** [comment]
![no-update](https://github.com/TanStack/query/assets/4837650/aa7cbd4c-d1b3-4de9-87cd-9df5d0230982)

**Comment by lachlancollins** [comment]
@inzanez I see, thanks for the video, so it's something that doesn't affect the original playground. I can't actually browse files within the codesandbox you've shared, so I can't troubleshoot this. Could you either share the full codesandbox, or the issue you ran into with the table in your own project?

**Comment by inzanez** [comment]
@lachlancollins 
I attached a local project that contains the same information. The file `EditTodo.svelte` contains the reference list based on the `$list` store directly.

[query-test.zip](https://github.com/TanStack/query/files/11597873/query-test.zip)

**Comment by lachlancollins** [comment]
@inzanez so it's specifically the deletion of this code in `Todos.svelte` that stops it from working:

```
    {#if $query.isFetching}
      <span>
        Background Refreshing... (Attempt: {$query.failureCount + 1})
      </span>
    {:else}
      <span>&nbsp;</span>
    {/if}
```

This immediately points to a reactivity issue, so I tried putting some `$: ` into the code. Turns out, it was actually the `fetchTodos` function which needed to be reactive, since it uses store values... I don't really get this but in reality your API endpoints wouldn't depend on a store. This is the fix:

```
$: fetchTodos = async ({ filter }: { filter: string }) => {
  ...
}
```

I'll rewrite the example to be more realistic once v5 is out!

**Comment by inzanez** [comment]
@lachlancollins I see, that's like..."how we get things to work". And I agree. But somehow it does not really convince me yet. I mean,...it does not feel like 'yeah, that makes sense'.

I mean, there is this:
```
    const query = createQuery<any, Error>({
        queryKey: ['todos', { filter }],
        queryFn: () => fetchTodos({ filter }),
    })
```

which should re-trigger fetching if there is an invalidation of the queryKey `todos`. Which in turn would call (and actually does call, proven by watching the console logs / network tab) `queryFn`. Which fetches new entries and returns them,...

So:
1. I could not argue why `fetchTodos` in this case should be reactive. This makes absolutely no sense to me
2. The store behind the`query` **does** get updated, but somehow it does not trigger re-rendering. I usually see this behavior with inadequate array updates of some sort so that reactivity does not trigger.

**Comment by inzanez** [comment]
Well, it does not seem that easy all in all. I will try to get a sample running with a real API that I can share. But that might take some time. Maybe I get some more details on the issue on my end in the meantime. A very quick try to re-create that error with a very minimal web service failed. So,...nothing to add for now. I will get back should I ever manage to reproduce it with a minimal example.

**Comment by lachlancollins** [comment]
> 2. The store behind the`query` **does** get updated, but somehow it does not trigger re-rendering. I usually see this behavior with inadequate array updates of some sort so that reactivity does not trigger.
> 
> All in all this does not feel right. It feels like magic that is not understandable.

@inzanez this is the way reactivity works in Svelte - some people do consider Svelte to be too magic for them!

Let's think through this code block like the Svelte compiler:

```
const fetchTodos = async ({ filter }: { filter: string }) => {
    console.info('fetchTodos', { filter })

    return new Promise((resolve, reject) => {
      setTimeout(() => {
        if (Math.random() < $errorRate) {
          return reject(
            new Error(JSON.stringify({ fetchTodos: { filter } }, null, 2)),
          )
        }
        resolve($list.filter((d) => d.name.includes(filter)))
      }, $queryTimeMin + Math.random() * ($queryTimeMax - $queryTimeMin))
    })
  }
```

When you perform the mutation in `EditTodo.svelte`, you update `$list` and then invalidate the query successfully. The query within `Todos.svelte` which calls the `fetchTodos` function *does* get invalidated and react to it, and re-runs. However, since the `fetchTodos` function hasn't been told that it depends on values that are reactive (including `$list`), it does not update its own held value of `$list`, and hence the query returns the same list as before. By specifically marking the function as reactive with `$: `, Svelte tracks dependencies for that function and reacts when they change.

I hope that makes sense! If you think the Svelte team should consider this a bug, please consider creating an issue here: https://github.com/sveltejs/svelte
