### ISSUE TITLE
QueryClient options 'logger' doesn't work

### ISSUE THREAD

**Issue by Darcrandex** [TanStack/query#5430]
### Describe the bug

I don't want an error message box to appear in development mode.
then I set this options:
```javascript
 logger: {
    log: console.log,
    warn: console.log,
    error: () => {
      // do nothing
    }
  },
```

but it doesn't work.

### Your minimal, reproducible example

https://codesandbox.io/s/react-query-logger-u6z1in?file=/src/index.js:181-344

### Steps to reproduce

set the option, then trigger a mutation

### Expected behavior

doesn't work

### How often does this bug happen?

None

### Platform

OS: mac 16
browser: chrom

### Tanstack Query adapter

None

### TanStack Query version

v4.29.7

**Comment by TkDodo** [comment]
not sure what you mean. The only thing visible in the console is because there is a `console.log("update error");` in the `onError` handler of the mutation. When removing that, there is nothing visible on the console...

> I don't want an error message box to appear in development mode.

The error message overlay is not coming from react-query but from the framework you're using. It says:

> This error overlay is powered by `react-error-overlay` used in `create-react-app`.

![Screenshot 2023-05-18 at 18 29 19](https://github.com/TanStack/query/assets/1021430/f3fb8117-7780-4687-9621-680526581380)

You're likely seeing the overlay because you use `mutateAsync`, which returns the rejected Promise, and you're not catching it.

You probably just want `mutate` instead of `mutateAsync`. Please see: https://tkdodo.eu/blog/mastering-mutations-in-react-query#mutate-or-mutateasync
