### ISSUE TITLE
[v5 beta] Type inference for `useQuery` breaks when using `queryOptions` util and `select`

### ISSUE THREAD

**Issue by jakst** [TanStack/query#5436]
### Describe the bug

When using the new `queryOptions` util from react-query v5, type inference seems to be a bit fragile. For example when spreading the resulting options object and adding a select statement to the query, the resulting data type is incorrect. More interestingly, the type seems to be inferred correctly if we also set the type `refetchInterval` option. I haven't tested around exactly which other options trigger this behaviour, but I believe this data point should be helpful enough in fixing the issue.

```typescript
import { queryOptions } from '@tanstack/react-query'

const options = queryOptions({
  queryKey: ["key"],
  queryFn: () => Promise.resolve(1),
});

// Type inference breaks, so TS complains about return type of select()
const query1 = useQuery({
  ...options,
  select: (data) => data > 1
});

// Type inference works like it should, so query2.data has type boolean
const query2 = useQuery({
  ...options,
  select: (data) => data > 1,
  refetchInterval: 1,
});

// When inlining the query options, types are correct even without refetchInterval
const query3 = useQuery({
  queryKey: ["key"],
  queryFn: () => Promise.resolve(1),
  select: (data) => data > 1,
});
```

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/festive-platform-0krnf3?file=%2Fsrc%2FApp.tsx%3A21%2C28

### Steps to reproduce

* Open the codesandbox
* See the ts errors in the editor

### Expected behavior

The correct data type should be inferred from the return type of the select function in useQuery.

### How often does this bug happen?

Every time

### Platform

v5.0.0-alpha.34

### Tanstack Query adapter

react-query

### TanStack Query version

v5.0.0-alpha.34

### TypeScript version

v5.0.4

**Comment by TkDodo** [comment]
yeah that's interesting. I'd expect `select` to _not_ work in these cases, because the return type of `queryOptions` will be of type `<number, Error, number, QueryKey>`. So `select` wants to "change" the 3rd generic, but it can't because it has already been inferred.

I'm pretty puzzled why adding `refetchInterval: 1` changes something. I mean, `refetchInterval` can be a function as well, and it uses the 3rd generic (`TData`), too, but I'm unsure how this can change the typings on `options`...

maybe @DamianOsipiuk or @ecyrbe have any ideas?

**Comment by gloomweaver** [comment]
I used custom wrapper around useQuery this providing generic for select which then I would pass to query, so you could easily pass select to custom hooks. It's doable. I want to look into this issue.

**Comment by TkDodo** [comment]
it also breaks a simple `intialData` use-case, because the type of `QueryOptions` is inferred as `UndefinedInitialDataOptions<number, DefaultError, number, string[]>`, and once TS thinks `initialData` is: `initialData?: undefined`, it doesn't allow us to pass it again ...

```
import { queryOptions, useQuery } from '@tanstack/react-query' // types: alpha

const options = queryOptions({
  queryKey: ["key"],
  queryFn: () => Promise.resolve(1),
});

const query1 = useQuery({
  ...options,
  initialData: '' // errors here!
});
```

[see this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRwK4FMoE8DyYbAQB2AzgDRyonoCKG2cAvnAGZQQhwDkAAjAIakBAYwDWAeijp+wmAFo0mLFzjjxcGFjDoSALjj8ANmAAW-ALAAoK8OIl4EfIVJwAvCnq4ndgBQIrcB5KANLoWPoA2gBEomFRALpkAUHYAGJE+j4AlG4AfHAACuwgwNQAdFIkEIYAbug+AIxZSZaMWQDcVjZ28IrYDW6U1HRKfsllE44Edi2BwETABEYAIvwC+lxcVm3tQA)

**Comment by jakst** [comment]
> it also breaks a simple `intialData` use-case, because the type of `QueryOptions` is inferred as `UndefinedInitialDataOptions<number, DefaultError, number, string[]>`, and once TS thinks `initialData` is: `initialData?: undefined`, it doesn't allow us to pass it again ...
> 
> ```
> import { queryOptions, useQuery } from '@tanstack/react-query' // types: alpha
> 
> const options = queryOptions({
>   queryKey: ["key"],
>   queryFn: () => Promise.resolve(1),
> });
> 
> const query1 = useQuery({
>   ...options,
>   initialData: '' // errors here!
> });
> ```
> 
> [see this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRwK4FMoE8DyYbAQB2AzgDRyonoCKG2cAvnAGZQQhwDkAAjAIakBAYwDWAeijp+wmAFo0mLFzjjxcGFjDoSALjj8ANmAAW-ALAAoK8OIl4EfIVJwAvCnq4ndgBQIrcB5KANLoWPoA2gBEomFRALpkAUHYAGJE+j4AlG4AfHAACuwgwNQAdFIkEIYAbug+AIxZSZaMWQDcVjZ28IrYDW6U1HRKfsllE44Edi2BwETABEYAIvwC+lxcVm3tQA)

That one errors because you're trying to set initialdData to a string while the queryFn returns a number though, right?

**Comment by TkDodo** [comment]
you're absolutely right. I thought that the options can't be narrowed anymore once it's set to `UndefinedInitialDataOptions`, but seems like they can. Using the right type works, so that's not an issue. Then the question is really: why doesn't the same work for select 🤔

**Comment by LeoCaprile** [comment]
I tried to make a custom hook and get on this same issue, any follow ups?

**Comment by jakst** [comment]
That's strange. In our repo we have upgraded to Typescript v5.1.3 and react-query v5 alpha-56 since I created the issue, but the types still work like I initially explained. Adding refetchInterval makes the types work the way I would expect them to when using select, while without it select fails.

I would very much like to avoid having to add an intermediary API that might or might not get used every time we use queryOptions. The nice part about the queryOptions API is that it allows only the shared parts of the query to be created up front, while leaving the other options up to the consumer without abstracting over the useQuery hook. Not having this type cooperate unfortunately throws a cog in the whole machinery =(

**Comment by TkDodo** [comment]
For `select`, which changes the output type, you need a function I'm afraid. The thing with `refetchInterval` is super weird but not reproducible in a standalone typescript playground I guess?

**Comment by jakst** [comment]
No it doesn't seem to work in the TS playground, but I think it's broken in some way.

Try this barebones setup to reproduce:
```
mkdir tmp && cd tmp
npm init --yes
npm install typescript @tanstack/react-query@alpha @types/react
```

Paste this in a typescript file called `tmp.ts` and open project in vscode
```typescript
import { queryOptions, useQuery } from '@tanstack/react-query'

const options = queryOptions({
  queryKey: ['key'],
  queryFn: () => Promise.resolve(1),
})

const query1 = useQuery({
  ...options,
  select: (data) => data > 1,
})

const query2 = useQuery({
  ...options,
  select: (data) => data > 1,
  refetchInterval: 1,
})

const query3 = useQuery({
  queryKey: ['key'],
  queryFn: () => Promise.resolve(1),
  select: (data) => data > 1,
})
```

`query1` will have an error on select, `query2` and `query3` will have the correct types without errors.

--- 

> For select, which changes the output type, you need a function I'm afraid

Yea I see that that's the case at the moment, but it should be possible to write the types in a way that it works, as is evidence by my repro above where it works when refetchInterval is added. Something with the return type of queryOptions is making typescript trip. If a regular `useQuery` call can switch out the type when select is there, why shouldn't one where we spread in queryOptions?

If you don't know how to solve this, then I guess there's not much more to do. But please don't dismiss it as not reproducible or impossible to fix 🙏  It really is reproducible if you try my example above.

Thank you for the patience!

**Comment by TkDodo** [comment]
Yeah not sure what's up with the ts playground...

> But please don't dismiss it as not reproducible or impossible to fix

👍 

> If a regular useQuery call can switch out the type when select is there, why shouldn't one where we spread in queryOptions?

because a regular `useQuery` infers all the types from what you pass to it. But once you extract it to an object and give it a type, when you spread it, it can become types that don't overlap. Consider, even without the `queryOptions` function:

```
import type { UseQueryOptions } from '@tanstack/react-query'

const staticOptions: UseQueryOptions<number, Error, number, Array<string>> = {
    queryKey: ['key'],
    queryFn: () => Promise.resolve(1),
}

**Comment by jakst** [comment]
I don't have enough understanding of RQ's internal types (or advanced generics in general) to know why the type acts like that, but maybe I can help by showing my current workaround.

[This TS playground shows a helper function that I created to basically do what I expect `queryOptions` to do](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ4A0cMeY6cAqhtrngPJgzAQB2qRJZcN+A0unjgBfOADMoEEHADkAARgBDNooDGAawD0UdApUwAtAEcc+aXA0bipdKgBccBQBswACwUAod+gAekWGOQWPWYWOBVtBRgsEzwAHnc4OAAVAAUFKAUQdgSw1lR4JJ48fkEfKJYAE1RuGJKCHKSAEUiFesTCmIAxFmbFNuSAUSgJKH6AJXQYZCgWJOs4MvRK6qpo2gYmPNiO2m7e1sHh6CImlpOikoA+d0uACgwpsG77W7B0zLtktIysgEo4AC8lzgEymMzmZH+CBy2jBoVe7yy9lSiNQ-yBcAeyCeLARPzRAG53EJPCo8vAIIwQtUAWEIlEirc8R97EgAG5OHD2FjIEAAI1wwnRwNu0MSxloJXsAG1pGoBNIiG98QA6DmOHAAXX6Evwzzgt2FcBSEhAwAwKu0qAgjjZ6GZWTVnPIACo4AAmX71IS-X5E9xk5RwXV4ACMgJQ1BiopyKrjlM2bFF6q5cFDPv6GEc6D0LwqLSN+cUcGBoeJftJ5ODMXdEbQa3wMcScZVCepyed9nTXpyWZzMBeVqNVpLaf62lEkxULgAkiwolB1V3vRWA1WQwBmOtR2hN6uSgQygBE8rwR+1ORD+sNgOBJsk5vQlpsNrtt1DPcSfdzBqLCkLLSjqGK4EkAA)

All queries in this example get type `UseQueryResult<boolean, DefaultError>`, as I would expect. Couldn't the queryOptions type be implemented like this as well?

```typescript
import { useQuery, type UseQueryOptions, type QueryKey } from '@tanstack/react-query'

export function createQuery<
  TParams,
  const TQueryKey extends QueryKey,
  TData,
  TQueryFnData,
  TError,
  ReturnType extends UseQueryOptions<TQueryFnData, TError, TData, TQueryKey>
>(setupFn: (params: TParams) => ReturnType) {
  return (params: TParams) => setupFn(params);
}

const options = createQuery((params: { value: number }) => ({
  queryKey: ['key', params.value],
  queryFn: () => Promise.resolve(params.value * 2),
}));

const query1 = useQuery({
  ...options({value: 1}),
  select: (data) => data > 1
});

const query2 = useQuery({
  ...options({value: 1}),
  select: (res) => res > 1,
  refetchInterval: 1,
});

const query3 = useQuery({
  queryKey: ["key"],
  queryFn: () => Promise.resolve(1),
  select: (data) => data > 1,
});
```

**Comment by TkDodo** [comment]
idk, can you refactor this to not have a `setupFn` ?

Also, what I noticed is that the QueryKey type is not inferred in the QueryFn. It's always `QueryKey` instead of being inferred from the actual `queryKey` that is passed:

[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ4A0cMeY6cAqhtrngPJgzAQB2qRJZcN+A0unjgBfOADMoEEHADkAARgBDNooDGAawD0UdApUwAtAEcc+aXA0bipdKgBccBQBswACwUAod+gAekWGOQWPWYWOBVtBRgsEzwAHnc4OAAVAAUFKAUQdgSw1lR4JJ48fkEfKJYAE1RuGJKCHKSAEUiFesTCmIAxFmbFNuSAUSgJKH6AJXQYZCgWJOs4MvRK6qpo2gYmPNiO2m7e1sHh6CImlpOikoA+d0uACgwpsG77W7B0zLtktIysgEo4AC8lzgEymMzmZH+CBy2jBoVe7yy9lSiNQ-yBcAeyCeLARPzRAG53EJPCo8vAIIwQtUAWEIlEirc8R97EgAG5OHD2FjIEAAI1wwnRwNu0MSxloJXsAG1pGoBNIiG98QA6DmOHAAXX6EvwzzgorguuKAiFgOBKQkIGAGBV2lQEEcbPQzKyas55AAVHAAEy-foWRJB4NwAB6AH5ib9fkT3GTlEaYgBGQEoagxUU5FXZymbNii9VcuBJoT+nIYRzoPQvCotYVwWuKODApNR2Px-KJ2g+1NoNb4TOJbMq3PUgse+wlsuJCtVmAve31+3N4v9bSiSYqFwASRYUSg6sn9VL7fJXfwAGZe+naIPzya8DKAETyvBP7U5Y36271y2SG3oHaNiOs6txJtOmLoJW1YGo2Cj1nBK5JseMZAA)

**Comment by TkDodo** [comment]
@jakst I finally figured out what's wrong in the playground. `@tanstack/react-query` re-exports the Query Core, so when we set `// types: beta`, it still doesn't pull in the core types of beta.

The fix is to explicitly import the core as well, even though it appears unused:

import { queryOptions, useQuery } from '@tanstack/react-query' // types: beta
import * as QueryCore from '@tanstack/query-core' // types: beta

With this, I can reproduce your original issue:

[playground](https://www.typescriptlang.org/play?ssl=4&ssc=65&pln=3&pc=1#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA2iSxwDecAjgK5ZQCeA8mBjAIAO1QAaOB1RYAil15wAvnCIlyAARjIx23AGsA9JTwwAtJ248ycQ4bgweYLKgBccAEZZt9cNHhIaHDyVgDC0FiqxKRkWjqoekaWvGa4ETZ2Dk4u7l4+NGm6cBCCwmJwALzsCvyloqgAFMw0cNVWANJYPO4A2gBE+l19ALriLW28AGIi7g0AlJUAfHAACtHAMgB0lKgQADYAblgNAIxzY0pzANx0mQAq2XDAIgTcWCK4kR4m+hJwu3A7gBlOBpcB7ZDPdDIDwQDjwSgwDhQERZZzFAj-LB7LD4eYFerwZI8E6VKQyEK8JrjTa0kpCepjVoyHH4WYAE2Q2gWFWWnO0cGWJxolxuNHuj2er0oH0iAHdoL84HtgIMnvBUAALOF7dmSAHEgBMm35yDgmqCjnRsP2OBEBKKRrJ0jkNWprVpm3pZQk4xZuJgHK5yB5fODgrgJyZcEorxguE1AEkRDBuAdkHt3FGRddbvYAOqa95PEQqkTPADmDiLEx4xTqYkkVpcKEooOglHwcCwR1RcuAMG18JjWDjCeTqag6b2DoStYAzM6KW7mq1iZ1unB+oMeCNo8TprNQ6t1lsdvsjqdzn7sQGg9ylnBTRHs6KgA)

**Comment by jakst** [comment]
Ah, that explains it! Makes sense.

About the setupFn, you were correct in that the types weren't actually working as expected, so I haven't managed to create a better util fn myself.
