### ISSUE TITLE
refetchInterval is missing in types for QueryOptions

### ISSUE THREAD

**Issue by rasmusrim** [TanStack/query#5460]
### Describe the bug

In my QueryCache.onSuccess / QueryCache.onError functions I use the property query.options.refetchInterval. Typescript complains and claims that property is not there, but it clearly is.

![image](https://github.com/TanStack/query/assets/16855788/8a2a0190-2eff-4c28-906e-1e2c6613a741)

### Your minimal, reproducible example

https://codesandbox.io/s/react-typescript-playground-forked-j6mf7d?file=/src/index.tsx

### Steps to reproduce

If you look at the onSuccess and onError functions in index.tsx, you will see that Typescript complains and claims refetchInterval does not exist. In the console, however, you will see that the refetchInterval property does in fact exist.

### Expected behavior

Typescript should accept query.options.refetchInterval without complaining.

### How often does this bug happen?

Every time

### Platform

I guess this happens everywhere.

### Tanstack Query adapter

None

### TanStack Query version

4.28.0

### TypeScript version

5.0.4

**Comment by TkDodo** [comment]
it's not missing. you opened a PR today with a "fix" for it, and I explained why that's not right:

- https://github.com/TanStack/query/pull/5459#issuecomment-1562499459

**Comment by TkDodo** [comment]
nope, because it's an observer level property. Again, you could have two instances of `useQuery`, where each one has a different `refetchInterval` specified.

Why do you need access to it? What problem are you trying to solve?

**Comment by nik-webdevelop** [comment]
@TkDodo I was just about to raise exact same issue, but luckily found this one.

My use case is that I check for `throwOnError` property. If it throws I do nothing, if it doesn't I show error toast.

An argument that we could have different `useQuery` with different observer options just doesn't click for me. `QueryObserverOptions` type properties are all optional and we could check them inside `QueryCache` handlers.

It is really frustrating to pass `QueryObserverOptions` to an `error` argument of an `onError` handler and at the same time declare in Types that we don't.

**Comment by TkDodo** [comment]
@nik-webdevelop when you look at a query in the cache, it can't know what the observers are doing. You can use the same query in two places, once with `throwOnError: true` and once with false:

```
const useTodos = (options: { throwOnError: boolean }) => {
  return useQuery({
    queryKey: ['todos'],
    queryFn: fetchTodods,
    ...options
}
```

then use this with `useTodos({ throwOnError: true })` in one component and `useTodos({ throwOnError: false })` in another. That's a feature. Maybe in one place, you're only interested in the count of todos, and you can fall back to `0` if there is an error, so you don't want to throw to an error boundary here. In other cases, you might. The same is true for `refetchInterval`. You can have a todo list that you want to refetch every 5 seconds, but you might want to have different observers that don't refetch the whole list. Those can be mounted in different parts of the app, at different times.

So when you look at the `query` how it's stored in the cache, it doesn't know anything about those options because there can be multiple observers with different values. We can't give you the one `throwOnError` value because that doesn't exist.

observers on a query are public but if it makes sense, we could expose those so that you could look at `query.observers`, map over them, and look at all options and then do what you want with them. I'm not fully convinced that this is necessary though. You can set `throwOnError` globally and set `onError`, and have one be the inverse of the other. It's what I do personally for example:

```
new QueryClient({
    defaultOptions: {
        queries: {
            throwOnError: (error, query) => query.state.data === undefined,
        },
    },
    queryCache: new QueryCache({
        onError: (error, query) => {
            if (query.state.data !== undefined) {
                showToast.error(error)
            }
        },
    }),
})
```

it works quite well.

**Comment by nik-webdevelop** [comment]
Thanks for a quick response and great explanation! 

> look at a query in the cache, it can't know what the observers are doing

I've just tested that `onError` handler gets `query.options` with specific to observer options:

```tsx
const { data } = useTodo();
// if error occurs here `query.options` will NOT have `staleTime` and `throwOnError`
```

```tsx
const { data } = useTodo({ staleTime: 5000, throwOnError: true });
// if error occurs here `query.options` will have `staleTime` and `throwOnError`
```

So, although the cache doesn't keep track of observers, the `onError` handler itself gets `query.options` from a specific observer (where the error occurred) and thus gets `QueryOptions` + `QueryObserverOptions`

Regarding example that you provided: I've ended up with almost a simillar approach, but there is one issue with presented solution. If I set `throwOnError: true` and there is a refetch error, I end up with both `ErrorBoundary` and `toast`.

My attempt: 

```tsx
onError: (error, query) => {
  const { throwOnError } = query.options as QueryObserverOptions;

  const isThrowingErrorToBoundary =
    typeof throwOnError === 'function'
      ? throwOnError(error, query)
      : throwOnError;

  if (!isThrowingErrorToBoundary) {
    showToast({ ...toastParams });
  }
}
```

**Comment by TkDodo** [comment]
>  the onError handler itself gets query.options from a specific observer

I think this is just because internally, on useQuery, we set the options to the observer, which then spreads it onto the query. so we would need to omit the options that are observer specific when doing that, but it would add additional runtime code for no real gain. the typescript types forbid access to those fields and thats good enough for me. you probably see the options from the _last_ observer. don't rely on it.

**Comment by nik-webdevelop** [comment]
Ok, i see. So, this means that the logic that i am trying to implement is impossible?

**Comment by TkDodo** [comment]
>  If I set throwOnError: true and there is a refetch error, I end up with both ErrorBoundary and toast.

well do you want the boundary displayed or the toast?

but yeah, if you set something on useQuery directly that is an observer property, the global callback can't know about it

**Comment by nik-webdevelop** [comment]
It would be nice to have access to the observer options, but I get it, thank you very much.
