### ISSUE TITLE
[v5 alpha] queryClient.refetchQueries({queryKey}) does NOT trigger re-render

### ISSUE THREAD

**Issue by yegao** [TanStack/query#5488]
### Describe the bug

After use queryClient.setQueryData(queryKey, { ...queryData });Invoke queryClient.refetchQueries({queryKey}) does NOT trigger UI's re-render。
In addition，queryClient.resetQueries({queryKey}) is working。

### Your minimal, reproducible example

queryClient.setQueryData(queryKey, { ...newQueryData }); queryClient.refetchQueries({queryKey});

### Steps to reproduce

queryClient.setQueryData(queryKey, { ...newQueryData });
queryClient.refetchQueries({queryKey});

The component which depend on this query not re-render

### Expected behavior

queryClient.refetchQueries({queryKey}) will make component which depend on this query re-render

### How often does this bug happen?

None

### Platform

macOS

### Tanstack Query adapter

None

### TanStack Query version

^5.0.0-alpha.38

**Comment by TkDodo** [comment]
Can you please shown a codesandbox or stackblitz reproduction showing this behavior?

**Comment by yegao** [comment]
> Can you please shown a codesandbox or stackblitz reproduction showing this behavior?

https://codesandbox.io/s/reverent-shadow-gwdy30

**Comment by TkDodo** [comment]
thanks. the problem is your mutable way of updating data. We have a guide on this topic here: https://tanstack.com/query/v4/docs/react/guides/updates-from-mutation-responses#immutability

Our structural sharing feature will see the same object and will then re-use the pre-existing one as an optimization.

so:
- don't change `dataset` inplace
- instead, do: `queryClient.setQueryData(["dataset"], { ...dataset, k: "B" });`

note that then, `setQueryData` will re-render your component correctly, and then `refetchQueries` will re-render it _again_, with the old data, where `k` is still `"A"` - because that's what the QueryFunction does.

I'm a bit confused by this example, but I'm 100% certain immutable updates solve your problem.

**Comment by yegao** [comment]
> thanks. the problem is your mutable way of updating data. We have a guide on this topic here: https://tanstack.com/query/v4/docs/react/guides/updates-from-mutation-responses#immutability
> 
> Our structural sharing feature will see the same object and will then re-use the pre-existing one as an optimization.
> 
> so:
> 
> * don't change `dataset` inplace
> * instead, do: `queryClient.setQueryData(["dataset"], { ...dataset, k: "B" });`
> 
> note that then, `setQueryData` will re-render your component correctly, and then `refetchQueries` will re-render it _again_, with the old data, where `k` is still `"A"` - because that's what the QueryFunction does.
> 
> I'm a bit confused by this example, but I'm 100% certain immutable updates solve your problem.

I have done a demo here https://codesandbox.io/s/hopeful-hertz-ocvp6e
Here's what really confused me:
