### ISSUE TITLE
Next.js app dir incremental adoption mix with pages dir not working

### ISSUE THREAD

**Issue by dbrxnds** [TanStack/query#5506]
### Describe the bug

Next.js app directory allows for incremental adoption so long as you do not have conflicting routes between the pages directory and the app directory, we want to use incremental adoption as our application is too large to make the jump all at once, however it seems that React Query context (QueryClientProvider) does not work with this. 

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/zen-cherry-4mknmy?file=%2Fpages%2Fpages.tsx%3A4%2C1

### Steps to reproduce

1. Open the CodeSandbox
2. Navigate to the root route, this works.
3. Navigate to the /pages route, this does not work.

### Expected behavior

For it to work

### How often does this bug happen?

Every time

### Platform

- OS: Linux Mint 21.1, MacOS Ventura
- Browser: Google Chrome
- Version: Any, I have attempted to use multiple

### Tanstack Query adapter

react-query

### TanStack Query version

4.24.4 in our application, Codesandbox is 4.29.7

### TypeScript version

5.0.4

### Additional context

Just to confirm that this should work with React context:

https://codesandbox.io/p/sandbox/sleepy-yalow-8pccs5?file=%2Fapp%2Fpage.tsx%3A13%2C40

**Comment by igorovic** [comment]
I have the same issue. No matter all the refactoring of my code it stills complains about `No QueryClient`

`Error: No QueryClient set, use QueryClientProvider to set one`

**Comment by AyushMainali123** [comment]
@dbrxnds @igorovic, this issue is caused by `pages.tsx` not being enclosed inside the `QueryClientProvider`. Wrapping the pages directory with `QueryClientProvider` solves the issue. Wrapping `_app.tsx` with `QueryClientProvider` fixes this issue.


Here is some changes I made to your code to make it work as expected:
https://codesandbox.io/p/sandbox/happy-lovelace-u15qum?file=undefined

**Comment by dbrxnds** [comment]
Hi @AyushMainali123, thanks! I wasn't aware that you could use both _app.tsx and root layout at the same time. Don't quite understand why it works with regular context though?

**Comment by AyushMainali123** [comment]
Yes, we can use both `_app.tsx` and root layout at the same time. `_app.tsx` works only for the pages directory and not the app directory and vice versa.

I couldn't quite get what context you are referring to.

**Comment by dbrxnds** [comment]
@AyushMainali123 See the last link in my original issue.

That would be this one: https://codesandbox.io/p/sandbox/sleepy-yalow-8pccs5?file=%2Fapp%2Fpage.tsx%3A13%2C40

**Comment by AyushMainali123** [comment]
@dbrxnds , 

The code you have written works with the regular context because layout.tsx contains the entire page component inside the `children` prop which is a required prop in the layout.tsx file.

Additionally, you have added a ContextProvider in the layout component. The ContextProvider in the layout component wraps the children, and all the states of the provider are passed down to the child component of the ContextProvider.

Here is an implementation of the code you wrote which might solve your confusion:
https://codesandbox.io/p/sandbox/sleepy-yalow-8pccs5?file=%2Fapp%2Fpage.tsx%3A13%2C40

**Comment by TkDodo** [comment]
thanks for looking into this @AyushMainali123

so my takeaway is that we need a Provider for both app dir root and pages root. You can use the same `queryClient` instance, though I don't think it matters much because navigations between app dir and pages dir are full page reloads anyways.
