### ISSUE TITLE
Why useEffect triggers twice after the API response is cached?

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#5538]
### Discussed in https://github.com/TanStack/query/discussions/5537

<div type='discussions-op-text'>

<sup>Originally posted by **dev-rish** June  5, 2023</sup>
**Describe the Bug**
After switching between 1 & 2 for couple of times (so that react query caches data for each of them), the useEffect still triggers twice.
The expected behavior is seen till v3.8.3 i.e. useEffect only triggers once. Once react query is updated to v3.9.0 every click on 1 or 2 causes useEffect to trigger twice.

Is there a way to prevent the second trigger?

I found related issues but still wanted some more info. if possible.

**Minimal, reproducible example**
v3: https://codesandbox.io/s/optimistic-firefly-1tk7i5
v4: https://codesandbox.io/s/sad-scott-cidk6s?file=/src/App.js

**Steps to reproduce**
Click in 1 > Click on 2 > Click in 1 > Click on 2 

**Expected behavior**
useEffect to trigger only once when `id` is switched.

**How often does this bug happen?**
Always</div>

**Note**:

- Seems to be `select` related, because it works as expected if `select` is removed
- This is _not_ strict mode related

**Comment by incepter** [comment]
Isn't the behavior normal since it is about new data coming from API ?

I mean, I inspected the stack traces and found that the `selector` function is ran twice:
- When useQuery renders and finds data in cache about the id
- When data is refreshed from API, and then the observer needs to re-select data, and obviously the new object doesn't equal the previous one.

**Comment by TkDodo** [comment]
> When data is refreshed from API, and then the observer needs to re-select data, and obviously the new object doesn't equal the previous one.

while this is true, react-query does structural sharing, and it does that also on the result of select. So if it's deeply the same, the same object reference should be reused.

**Comment by omermizr** [comment]
I'm not too familiar with the internals, but I think the issue is with https://github.com/TanStack/query/blob/main/packages/query-core/src/query.ts#L470, where you call `setData` with the raw result, rather than the selected result.
That's also incompatible with the `structuralSharing` function option, because it takes `TData`, but we pass it `TQueryFnData`.

**Comment by incepter** [comment]
I think I know what's happening in there.
I have a fix locally, but im not sure about its impact.

I will followup with a PR and explanations later today.

**Comment by mk-nickyang** [comment]
Looks like this is still a issue in the latest **v4** when `keepPreviousData: true`, see https://codesandbox.io/p/sandbox/eager-wescoff-x7k9rd

It is fixed in **v5** tho even with `placeholderData: keepPreviousData`, see https://codesandbox.io/p/sandbox/mystifying-dust-7rnfwf
