### ISSUE TITLE
isLoading not returning Bool without destructing | Nuxt - Vue-Query

### ISSUE THREAD

**Issue by mrniamster** [TanStack/query#5658]
### Describe the bug

![image](https://github.com/TanStack/query/assets/52563039/9a3d1646-ccad-431d-ba90-b79c1c6cac55)

As shown above, without destructing, and using useQuery in a direct const like below, the isLoading is not returning bool, i haven't tested for other types, but isFetching is working good.
![image](https://github.com/TanStack/query/assets/52563039/ca3bb659-b759-4a98-8d45-de675c20f051)

### Your minimal, reproducible example

https://codesandbox.io/s/new

### Steps to reproduce

Output  .isLoading without destructing 
Example 
```
<template>
<span v-if=" fetchUser.isLoading">Loading..</span>
////Its stuck in  Loading. only
<span v-else>Things are loaded</span<
</template>

<script>
const fetchUser = useQuery({
   queryFn: async () => $fetch('/'),
   queryKey: ['fetchUser', state.email],
   onSuccess(r) {

      }
   },
})
</script>
```

### Expected behavior

when used like below 
![image](https://github.com/TanStack/query/assets/52563039/c39cf514-5bf3-436c-9b32-365543d0b0c1)

@return type should be  : Boolean

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/52563039/9a3d1646-ccad-431d-ba90-b79c1c6cac55)

### Platform

Nuxt project info:                                                                    5:17:51 PM  

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.11.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  npm@9.6.5
- Builder:          vite
- User Config:      vue, routeRules, nitro, css, vite, postcss, app, modules, content, googleSignIn, runtimeConfig, devtools, plugins
- Runtime Modules:  nuxt-vue3-google-signin@0.0.8, @pinia/nuxt@0.4.11, @nuxt/content@2.7.0, @pinia/nuxt@0.4.11, @nuxtjs/color-mode@3.3.0
- Build Modules:    -
------------------------------

### Tanstack Query adapter

vanilla

### TanStack Query version

^4.29.19

**Comment by DamianOsipiuk** [comment]
All properties returned by `vue-query` are `ref`'s. Otherwise if you try to destructure them, you will loose reactivity, which is a very common problem among new Vue devs.
Vue should unwrap refs that are passed to the template, but it seems that they are doing it only for direct accessed properly and dot notation access - `query.isLoading` is not unwrapped.

This is not strictly a problem with `vue-query`.
You could potentially open a feature-request in Vue repository to get it working.

We could potentially just return `reactive` object and count on users to properly handle destructuring with `toRefs` conversion, but i doubt that will be a good idea (more confused users than benefits).
There is an RFC in place to make `reactive` props destructurable, but until that lands and will be supported in custom composables, i doubt we could do anything about it.

**Comment by mrniamster** [comment]
Hello @DamianOsipiuk  This really makes sense, i used react-query previously, it worked. well in that case,

One point i would like to add here  is:

With destructing only few property like isLoading are not working here, isFetching  is all working good when tested with ve dev tool

Can you  please tell me how to use the isLoading then with below query now : 
```
<template>
<span v-if=" fetchUser.isLoading">Loading..</span>
////Its stuck in  Loading. only
<span v-else>Things are loaded</span<
</template>

<script>
const fetchUser = useQuery({
   queryFn: async () => $fetch('/'),
   queryKey: ['fetchUser', state.email],
   onSuccess(r) {

      }
   },
})
</script>
```

**Comment by mrniamster** [comment]
Hello @DamianOsipiuk , Still unhappy with what they said tbh, 
But still thinking why we have to use query.isLoading.value on the template and for some query.isFetching works just fine, 
This looks so inconsistent.
