### ISSUE TITLE
OnlineManager's setOnline doesn't seem to work with subscriptions correctly

### ISSUE THREAD

**Issue by pushys** [TanStack/query#5674]
### Describe the bug

I've got a custom React hook for subscribing to changes in `onlineManager.isOnline`:

```typescript
import { useState, useEffect } from "react";
import { onlineManager } from "@tanstack/react-query";

export default function useIsOnline() {
  const [isOnline, setIsOnline] = useState(onlineManager.isOnline());

  useEffect(() => {
    const unsubscribe = onlineManager.subscribe(() => {
      console.log(`Online: ${onlineManager.isOnline()}`);
      setIsOnline(onlineManager.isOnline());
    });

    return () => unsubscribe();
  }, []);

  return isOnline;
}
```

It works great when default behavior is in place. But instead of relying on browser's `online`/`offline` events I've created a hook with `networkMode: 'always'` that periodically checks connection to API and depending on success/error of the request I manually set online state using `onlineManager.setOnline`.

The problem is `onlineManager.setOnline(false)` doesn't trigger callback in the subscription or maybe I am a bit misunderstanding the concept of `OnlineManager`.

### Your minimal, reproducible example

https://codesandbox.io/s/focused-williamson-gxks92

### Steps to reproduce

1. Set up subscription through `onlineManager.subscribe`.
2. Manually call `onlineManager.setOnline(false)`.

### Expected behavior

Expect the callback to be executed on both `onlineManager.setOnline(true)` and `onlineManager.setOnline(false)`.

### How often does this bug happen?

Every time

### Platform

- OS: Windows.
- Browser: Any modern one.

### Tanstack Query adapter

react-query

### TanStack Query version

4.28.0

### TypeScript version

4.9.4

**Comment by TkDodo** [comment]
yeah this is kinda weird. The only place where we use `subscribe` from online and focus managers is here:

https://github.com/TanStack/query/blob/1ef2958113e6ac41eaae3d2b849aed518b69e7b9/packages/query-core/src/queryClient.ts#L89-L100

we even make an extra check to see if we are online via `if (onlineManager.isOnline())`, which makes little sense given that we only call the callback if we are online true :/

I would propose to change this in v5 to:

- always call the listener callback of `subscribe` when a change happens
- maybe even pass the current `value` as an argument to the listener

I'd have to do this on v5 though because it's technically a breaking change (even though `subscribe` seems to be undocumented)

**Comment by TkDodo** [comment]
ah, the interesting part is that it seems to work fine if use the "standard" online measuring behaviour - the `else` part in this block:

https://github.com/TanStack/query/blob/00319a14211045325c509c3ac991a024e4f7d3f6/packages/query-core/src/onlineManager.ts#L56-L62

but once you get your custom online boolean (the `if` part in the above block), we only call `onOnline` if the value is truthy.

I think we could call this a "fix" and just remove the `if` statement here:

https://github.com/TanStack/query/blob/00319a14211045325c509c3ac991a024e4f7d3f6/packages/query-core/src/onlineManager.ts#L65-L71

🤔
