### ISSUE TITLE
select function error is not propagated to global error handling

### ISSUE THREAD

**Issue by kacper-witas-tsh** [TanStack/query#5878]
### Describe the bug

When error is thrown inside `select` function of query it's local state is error state, but on the QueryCache layer it is considered as success (onSuccess is called instead of onError).

Probably related to this issue which was fixed but didn't include global `onError`:
https://github.com/TanStack/query/issues/1540

We're using query@^4.2.1 but I've tested it on @beta and it has the same issue, sandbox is using beta version.

### Your minimal, reproducible example

https://codesandbox.io/s/angry-jepsen-9k5x84?file=/src/App.js

### Steps to reproduce

1. Open sandbox
2. Look in the console

### Expected behavior

Error thrown inside select function should propagate to `onError` defined inside QueryCache instead of `onSuccess`

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 115.0.5790.170

### Tanstack Query adapter

None

### TanStack Query version

^4.2.1

### TypeScript version

4.7.4

### Additional context

We need this to work correctly for capturing a select fn error in sentry

**Comment by TkDodo** [comment]
> Error thrown inside select function should propagate to onError defined inside QueryCache instead of onSuccess

The discrepancy comes from the fact that `select` operates on observer / component level, which means you can have multiple, different selects for the same query.

In your example, you could have two custom hooks both listening to the same Query, but with different selects:

```
const useFoo = (select) => useQuery({
  queryKey: ["foo"],
  queryFn: async () => {
    return 5;
  },
  select,
  retry: false
})

const useBar = () => useFoo(data => data * 2)
const useBaz = () => useFoo(() => { throw new Error("baz") }
```

So in both scenarios, the "Query" itself - what is stored in the cache - was successful. That is also what the global callbacks indicate. Then, you have consumners of your query - the components or observers. They can further do things with that data. That can also fail, which is why we are putting the local component state into error, but not the global one.

I think this somehow makes sense, but yeah, it's a bit weird. If we'd want consistency, we would have to keep the Query itself in success state, basically swallowing the error from `select` and act as if it never happened. But that would be super weird for TypeScript as well because the returned data would be in the wrong shape ...

**Comment by TkDodo** [comment]
If the transformation isn't component specific, you could still do it inside the queryFunction ?

**Comment by TkDodo** [comment]
I don't think there's much we can do here. as I said, the query itself was successful, and that's what the global callbacks listen for.

**Comment by OliverJAsh** [comment]
My intuition was that exceptions inside `select` would not be caught/handled by React Query, rather they would be treated as regular exceptions during the component render phase, i.e. they bubble up to error boundaries. Is there any reason why it doesn't work like that? 🤔
