### ISSUE TITLE
`persistQueryClient` still cause refetch data on reload.

### ISSUE THREAD

**Issue by nhtoby311** [TanStack/query#5926]
### Describe the bug

I'm using [PersistQueryClientProvider](https://tanstack.com/query/v4/docs/react/plugins/persistQueryClient#persistqueryclientprovider), in order to store the `useQuery` data into `localStorage`, so it won't refetch when I refresh the page. However, the refetch is still happened, despite it stores the value in the localStorage. Note: the API I'm using returns a random value each time.

### Your minimal, reproducible example

https://codesandbox.io/s/react-query-persist-issue-knqv68?file=/src/index.tsx

### Steps to reproduce

1. When refreshing, the JSON data is being changed after a slight delay.
2. There also a refetch request on each refresh

### Expected behavior

It shouldn't refetch on reloading the page.

### How often does this bug happen?

Every time

### Platform

- Browser: Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

v4.33

### TypeScript version

v5.0.2

**Comment by TkDodo** [comment]
you haven't customized staleTime, so the data loaded from localstorage is seen as "too old" (older than 0ms, which is the default staleTime). That's why you see a background refetch. If you set a higher staleTime, you won't see a refetch in that timeframe.

https://codesandbox.io/s/react-query-persist-issue-forked-tlxynn?file=/src/index.tsx

**Comment by nhtoby311** [comment]
Thank you! It works well now 🔥 I think it would be also nice if you could include this info in the docs as well!

**Comment by TkDodo** [comment]
Please submit a PR :)

**Comment by levymetal** [comment]
I've been trying to debug an issue with `PersistQueryClientProvider` refusing to hydrate with cached data. It has something to do with `cacheTime`. For example, in the above CodeSandbox (https://codesandbox.io/s/react-query-persist-issue-forked-tlxynn?file=/src/index.tsx), a `cacheTime` of `1000 * 60 * 60 * 24` works. However, `1000 * 60 * 60 * 24 * 28` doesn't. Weirdly enough a higher value such as `1000 * 60 * 60 * 24 * 56` causes it to work again.

Not only do some `cacheTime` values like `1000 * 60 * 60 * 24 * 28` break hydration, but they break caching from memory as well. Ie if a query is unmounted and immediately re-mounted, `data` is `undefined` and the query refetches.

However, this only occurs with `PersistQueryClientProvider`. `QueryClientProvider` doesn't seem to be affected by the same issue.

**Comment by TkDodo** [comment]
> a cacheTime of 1000 * 60 * 60 * 24 works. However, 1000 * 60 * 60 * 24 * 28 doesn't.

what do you mean with "works" or "doesn't work". What's happening, what does "refuse to hydrate" mean, and what would you expect to happen instead ?

Maybe you should show a codesandbox reproduction that clearly breaks, because I have no idea how to reproduce what you are claiming ...

**Comment by levymetal** [comment]
@TkDodo Thanks for getting back to me. When I say "Refuses to hydrate" I mean that hydration does not occur. Ie, dehydrated data is not loaded into the cache, and the data is refetched from the server every time the query is mounted.

As mentioned, to reproduce the issue you need only change the `cacheTime` in the aforementioned CodeSandbox to `1000 * 60 * 60 * 24 * 28`. I have now forked the CSB here: https://codesandbox.io/s/react-query-persist-issue-forked-4mjk9p?file=/src/index.tsx to include this change (as well as bumping all `@tanstack` deps to `4.35.0`). When the page is refreshed, the cache is not hydrated and the data is refetched from the server.

I have also made another CSB which shows the same issue occurring when the query is unmounted/remounted: https://codesandbox.io/s/react-query-persist-issue-forked-dhnrfd?file=/src/App.tsx. If you click `Toggle Content`, this mounts/unmounts the query, and the data is always refetched and is never served from the cache. I have also added a button to log the query cache to the console, this shows that the cache is always empty. 

Originally I thought this had something to do with `PersistQueryClientProvider`, however `QueryClientProvider` also seems to exhibit the same behaviour: https://codesandbox.io/s/react-query-persist-issue-forked-lhmndr?file=/src/index.tsx. Toggling the query will cause the data to be refetched every time. So I'm no longer sure whether this has to do with persisters; I think it's unrelated TBH.

I've put together some more detailed instructions for repro, but if there's anything else I can do to help you reproduce the issue just let me know.

### Steps to reproduce

#### Scenario 1: hydrating the query cache

- Visit https://codesandbox.io/s/react-query-persist-issue-forked-4mjk9p?file=/src/index.tsx
- Observe that the query client has been configured with a `cacheTime` of `1000 * 60 * 60 * 24 * 28` and a `staleTime`, and the app is using `PersistQueryClientProvider`
- Observe the data on the page
- Refresh the page, observe that the cache is not hydrated, the data is different and a network request has been made.
- Change the `cacheTime` to a different value, such as `1000 * 60 * 60 * 24` or `1000 * 60 * 60 * 24 * 60`
- Repeat the steps above. Observer that the cache is hydrated on page refresh, the data is served from the cache, the data remains the same, and a network request is not made.

#### Scenario 2: loading data from the query cache

 - Visit https://codesandbox.io/s/react-query-persist-issue-forked-dhnrfd?file=/src/index.tsx
 - Observe that the query client has been configured with a `cacheTime` of `1000 * 60 * 60 * 24 * 28` and a `staleTime`, and the app is using `PersistQueryClientProvider`
 - Click `Toggle Content`. This will mount the query.
 - Click `Toggle Content` again. This will unmount the query.
 - Click `Toggle Content` again. This will mount the query. Observe that the data is different, and a network request has been made.
 - Click `Log query cache data` and open the console. Observe that the cache is empty.
 - Change the `cacheTime` to a different value, such as `1000 * 60 * 60 * 24` or `1000 * 60 * 60 * 24 * 60`
 - Repeat the steps above. Observe that the data remains the same on remount, and the cache is populated with the data.

The same result occurs regardless of whether `PersistQueryClientProvider` or `QueryClientProvider` is used. The same steps can be repeated with `QueryClientProvider` and the same result can be observed: https://codesandbox.io/s/react-query-persist-issue-forked-lhmndr?file=/src/index.tsx

### Expected behaviour:

When using a `QueryClient` with a `staleTime` greater than `0` and a `cacheTime` of `1000 * 60 * 60 * 24 * 28`, with a persister, I expect the query cache to be hydrated with data from the persister, and when the query is mounted I expect the query to return data from the cache, and I do not expect the data to be refetched from the server if it is not stale.

### Actual behaviour:

When using a `QueryClient` with a `staleTime` greater than `0` and a `cacheTime` of `1000 * 60 * 60 * 24 * 28`, with a persister, the query cache is not hydrated with data from the persister, and the query cache itself is never populated after data has been fetched. When a query is mounted, the data is always refetched from the server.

### TanStack Query version
v4.35.0

### Platform
 - Browser: Chrome 116.0.5845.140
 - Browser: Safari 16.6

**Comment by TkDodo** [comment]
@levymetal thanks for the details, I've looked into this.

- The Query is restored correctly from localstorage
- It is then however instantly garbage collected, which shouldn't happen, which is why you'll see the new fetch every time.

I traced this back to `setTimeout` being called immediately when you pass the value for 28 days. A super easy reproduction is:

```
setTimeout(() => {
  console.log('hello world')
}, 1000 * 60 * 60 * 24 * 28);
```

this will log `'hello world'` immediately.

The reason is apparently that `setTimeout` uses a 32 bit int to store the delay, so the max allowed value is `2147483647`, which is 24.88 days. We use `setTimeout` for our garbage collection timer, so I guess this would be our limit here as well.

https://stackoverflow.com/questions/3468607/why-does-settimeout-break-for-large-millisecond-delay-values

**Comment by levymetal** [comment]
@TkDodo Fascinating! After hitting this issue I figured that it isn't necessary to set the `cacheTime` to 28 days anyway, considering the cache is updated whenever a stale query is refreshed. In fact, 28 days probably does more harm than good. The rename of `cacheTime` to `gcTime` in v5 makes this more intuitive, so thanks in advance for that 😄
