### ISSUE TITLE
Using `signal` in the `queryFn` makes the query run twice

### ISSUE THREAD

**Issue by Gamote** [TanStack/query#6089]
### Describe the bug

I have discovered that whenever I try to use the `signal` property of the context the `queryFn` is running twice. I don't even need to use it but just specify it in the `queryFn` like so: `queryFn: ({ signal }) => ...`; if I remove it it works just fine: `queryFn: () => ...` the function runs only once.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/react-query-bug-demo-page-72c698?file=%2Fsrc%2Fapp%2Fpage.tsx%3A1%2C1-39%2C1

### Steps to reproduce

1. Follow the documentation and setup React Query.
2. Choose a component and add the following code:
    ```tsx
    "use client";
    
    import { useQuery } from "@tanstack/react-query";
    
    export default function Index() {
      const resultBug = useQuery({
        queryKey: ["current_user_bug"],
        // Issue: if `signal` is specified in the params
        //  the query is going to run twice
        queryFn: ({ signal }) => {
          console.log("Twice (page)");
    
          return {
            id: "test",
          };
        },
      });
    
      const resultAlsoBug = useQuery(["current_user_also_bug"], ({ signal }) => {
        console.log("Also Twice (page)");
        return {
          id: "test",
        };
      });
    
      const resultOk = useQuery({
        queryKey: ["current_user_ok"],
        // In here the signal is not specified and the query runs only once
        queryFn: () => {
          console.log("Once (page)");
          return {
            id: "test",
          };
        },
      });
    
      return <>Check the Console to see the bug logs.</>;
    }
    ```
3. Start the project: `yarn dev`
4. Navigate to the page and check the logs, you should see:
    ```txt
    Twice (page)
    Also Twice (page)
    Once (page)
    Twice (page)
    Also Twice (page)
    ```

### Expected behavior

We expect that the `queryFn` will run only once and it is not influence by the usage of the incoming parameters:
```txt
Twice (page)
Once (page)
Also Twice (page)
```

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Chrome
- Version: Version 117.0.5938.132 (Official Build) (arm64)

### Tanstack Query adapter

react-query

### TanStack Query version

v4.35.7

### TypeScript version

v5.2.2

**Comment by TkDodo** [comment]
I know it sounds weird, but it's expected. Let me explain:

we track if the `signal` that we provide to the `QueryFunctionContext` gets used by consumers. We do this with custom getters on the object, so a destruct already triggers the getter. Usually, you'd forward the `signal` to `fetch`, but we can't know that. So invoking the getter means you're using the signal.

When you're using the signal, React Query behaves a bit differently than normal: When a component unmounts that uses a query that is currently fetching, instead of letting the Promise resolve and storing the data in the cache for later usage, we cancel the query and revert back to the previous state. This is what you want when using the `signal`, because it means requests that are running can be aborted when they become unused.

Further, NextJs uses `React.StrictMode` per default, which means React will unmount and mount the component in dev mode. This will always trigger a second fetch (because we fetch when a component mounts), but it can usually be deduplicated. With the signal though, the first fetch will be aborted because of the unmount. So you'll see:

- mount, triggers fetch
- unmount, aborts query & cancels fetch
- mount, triggers new fetch

If you do a real fetch request, you'll even see the cancelled request in the browser devtools.

So yeah, it's a combo of using the signal + strict mode in dev env. If you want, please amend the docs about request cancellation. I've known this from the start (~ 1 year ago) but so far, no one has really reported it as an issue. There's also nothing we can do here because we can't wait with the request cancellation just to see if maaaaybe there will be another mount soon...

**Comment by Gamote** [comment]
It makes sense, @TkDodo thank you for the quick response.

So from what I gather it will not be an issue in production because StrictMode will not be used and the component will not unmount like it does now.

Also, how would you deal with this in a local development environment? Would you just let it be, or?

**Comment by TkDodo** [comment]
Yes, I'd let it be. But also, I'm usually not using AbortSignals

**Comment by Gusis93** [comment]
I think this issue should be pasted in the docs about signal 😄 its been driving me crazy that I was prefetching a query and as soon as I got to a page using said query, it was re fetching, it never occurred to me that it could be because I was deconstructing ({signal}) in the fetchFn. Glad I found this because it was driving me insane!
