### ISSUE TITLE
Prefetching request not running or too late (v5)

### ISSUE THREAD

**Issue by nilshartmann** [TanStack/query#6108]
### Describe the bug

I have a component ("Post") that triggers a prefetch request and a suspense request as described here: https://tanstack.com/query/v5/docs/react/guides/prefetching#prefetch-in-components

When the component renderes, it seems, the prefetch request does not start to run. 

You can see the behaviour in the sandbox app in the console, where it says, the first ("prefetch") request for a `Comment` starts only after the suspense request for the `Post` has been finished. 
Also the UI should not display the fallback component for the `Comment` component, as the request data thanks to prefetching should be available at rendering time ("Post" request takes way longer than "Comment" request).

### Your minimal, reproducible example

https://codesandbox.io/s/hopeful-neumann-qnr5s7?file=/src/App.js

### Steps to reproduce

- Start the app
- have a look at the console log
- you see that the `Comment` component renders and then the "comment" request starts.
- But why is the comment request not running when it's prefeetch in the `Post` component?
- 

### Expected behavior

As a user, I would expect that the "comment" request is triggered as early as the `Post` component is rendered (even before the `getPost` query)

### How often does this bug happen?

Every time

### Platform

- macOS, firefox

### Tanstack Query adapter

react-query

### TanStack Query version

5.0.0-rc4

**Comment by TkDodo** [comment]
yeah this doesn't work I'm afraid because of how `suspense` works. @Ephem I remember flagging this in the docs PR, but maybe we didn't adapt it in all places?

having `useQuery` do your prefetching only works if you `useQuery`, not if you `useSuspenseQuery`, so this code example is actually incorrect:

```
// Prefetch
useQuery({
  queryKey: ['article-comments', id],
  queryFn: getArticleCommentsById,
  // Optional optimization to avoid rerenders when this query changes:
  notifyOnChangeProps: [],
})

const { data: articleResult } = useSuspenseQuery({
  queryKey: ['article', id],
  queryFn: getArticleById,
})
```

`useQuery` only "schedules" a fetch - it doesn't fetch during rendering. But `useSuspenseQuery` "suspends" by throwing a promise to the SuspenseBoundary, so that scheduled fetch never happens, as effects and useSyncExternalStore subscriptions never run.

@Ephem I think we have to remove / tweak this example

**Comment by TkDodo** [comment]
probably prefetching from within the queryFn, or in your route loader, or on the server.

**Comment by Ephem** [comment]
@nilshartmann Thanks for reporting this! This example changed a few times during writing and ended up in a bad place.

@TkDodo This example first used `useSuspenseQueries`, but you correctly pointed out that would block until the prefetch was done which is not what we wanted. You also pointed out in one of the SSR guides that even though `prefetch`+`useSuspenseQuery` works, maybe the guides should be using `useQuery` instead because of reasons, that I did change. This example, using suspense and wanting to prefetch a separate query, is completely legit and something we should support.

This is yet another good argument we should implement that `usePrefetch` hook that we've talked about. Maybe it's as simple as:

```tsx
const usePrefetch = (...args) => {
  const queryClient = useQueryClient();

  // Runs in render, doesn't fetch if there's already data
  // so should not have observable side effects?
  queryClient.ensureQueryData(...args);
  
  // Could optionally prefetchQuery in an effect here if
  // we want to prefetch fresh data when safe
};
```

?

@nilshartmann The above is another approach you could try while we figure this out, though the options @TkDodo listed are the verified to work ones. 😄

I'll go ahead and remove this section from the docs until we've figured it out.

**Comment by nilshartmann** [comment]
Hi @Ephem , thanks for your response! I already thought about the `usePrefetch` approach but was not sure, because calling `ensureQueryData` would be a (forbidden) side effect in render phase?

**Comment by TkDodo** [comment]
> because calling ensureQueryData would be a (forbidden) side effect in render phase?

as @Ephem pointed out, side-effects are only disallowed in react if they are "observable", meaning they have an influence that other components could see. Priming a cache is highlighted specifically as an exception to this. `hydration` also puts data into the cache during render. However, what you shouldn't do is run the query if you already have data in the cache, because that data can be observed by another component already.

That's why `ensureQueryData` should be fine, because it only fetches if there isn't data in the cache already, so whatever side-effect it produces cannot be observed by other components.

@Ephem what do you think about, for now, we change the example to calling `ensureQueryData` in the component instead of `useQuery` ?

**Comment by nilshartmann** [comment]
> side-effects are only disallowed in react if they are "observable", meaning they have an influence that other components could see. Priming a cache is highlighted specifically as an exception to this

Didn't know that. Thanks!

I tried `usePrefetch` and it works!
