### ISSUE TITLE
initialData = null is preventing fetching from a hard loading state

### ISSUE THREAD

**Issue by cgarrovillo** [TanStack/query#6152]
### Describe the bug

When initialData is set to `null`, RQ does not default to fetching.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/rq-v4-initial-data-as-null-kqh5n4?embed=1&file=%2Fsrc%2Findex.jsx%3A29%2C22

### Steps to reproduce

1. Go to the reproduction
2. Notice that the page crashes because it tries to use the null data

### Expected behavior

As a developer, I expected RQ to default to fetching the resource instead of using my `null` initial data, but i am seeing that RQ uses `null` as the value and does not fetch the resource

There is also no documentation about this behaviour at all other than a 1 line comment about returning `undefined`, which still doesn't imply that `null` should not be used.

### How often does this bug happen?

Every time

### Platform

- OS: MacOS Ventura
- Browser: Chrome 117

### Tanstack Query adapter

None

### TanStack Query version

v4.7.1

**Comment by TkDodo** [comment]
`null` is a valid value to be returned from your `queryFn`, just like `0` or empty string. Also, with the default setting of `staleTime: 0`, you would get a background refetch. You don't get it in your example because you put `null` into the cache and then try to access `.name` on it, which yields:

> Uncaught TypeError: Cannot read properties of null (reading 'name')

You already know the answer: use `undefined`
