### ISSUE TITLE
Possible problem with type narrowing in react-query version 5.0.0

### ISSUE THREAD

**Issue by doberkofler** [TanStack/query#6167]
### Describe the bug

I'm testing the new version 5 of react-query and it seems as if the type narrowing of the data is no longer working as expected. Before version 4 the following example would have used TypeScript type narrowing and result in `data` to be of type `string` but after upgrading to version 5 it is still `string` or `undefined`:

```typescript
import {useQuery} from '@tanstack/react-query';

const foo = (): string => {
    const {data, isLoading, isError} = useQuery({queryKey: ['foo'], queryFn: () => Promise.resolve('foo')});

    if (isLoading) {
	    return '';
    }

    if (isError) {
	    return '';
    }

    return data;
};
```

### Your minimal, reproducible example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwK4GcCmBFJaoE8C+cAZlBCHAOQACMAhgHYp0DGA1gPRRq3MwC0AR2x4KAbgCwAKCnMIjeEQgQ4AXjgAKAJQAuOEyjB6Ac1UA+RFLhW4s+YgAmtOgBo4wFABkIte4aOv3AFEoUihCNVRMYVx1BCEcXABpNFxdAG0KRQgKAF1XeLwAMXpdLTM4AAVSEHc0ADouFAgAGwA3NHVMpQpNfE0JaUlrNyINdy8fP00LSQBIYa4YJCh6SjFLa3wpDatgUfUgkOhphCl560Xl1Yp1oc3tu6tLlbhHOgH8AaA

### Steps to reproduce

TypeScript does show a type error when returning data

### Expected behavior

`data` should have type narrowed down to `string`

### How often does this bug happen?

Every time

### Platform

macOS

### Tanstack Query adapter

react-query

### TanStack Query version

5.0.0

### TypeScript version

5.2.2

**Comment by TkDodo** [comment]
that's because `isLoading` now no longer derived from a status, but a _derived_ flag, so this is on purpose. The 3 main states that discriminate `data` are:

- `status === 'pending`` or `isPending` - we have no data yet
- `status === 'success'` or `isSuccess`- we have data
- `status === 'error'` or `isError`- we have an error

in v5, `isLoading` is the same as `isInitialLoading` was in v4 - a derived flag that describes that you can display a loader, meaning the query is `pending` and the `fetchStatus` is `fetching`. There are cases where you are in `pending` state but are _not_ fetching, mainly when the query is `enabled: false`. It was the most critiqued thing in v4 that a query is "loading" when its disabled, so it's not really "loading".

If you use `isPending` as the [migration guide](https://tanstack.com/query/latest/docs/react/guides/migrating-to-v5#status-loading-has-been-changed-to-status-pending-and-isloading-has-been-changed-to-ispending-and-isinitialloading-has-now-been-renamed-to-isloading) suggests, you get proper narrowing:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwK4GcCmBFJaoE8C+cAZlBCHAOQACMAhgHYp0DGA1gPRRq3MwC0AR2x4KAbgCwAKCnMIjeEQgQ4AXjgAKAJQAuOEyjB6Ac1UA+RFLhW4s+YgAmtOgBo4wFAAU09e4aOv3AFEoUihCNVRMYVx1BCEcXABpNFxdAG0KRQgKAF1XeLwAMXpdLTM4D1IQdzQAOi4UCAAbADc0dUylCk18TQlpSWs3Ig13Lx8-TQtJAEghrhgkKHpKMUtrfCl1q2AR9SCQ6CmEKTnrBaWVijXBja3bqwvluEc6fvx+oA
