### ISSUE TITLE
Types for getQueryData is unknown

### ISSUE THREAD

**Issue by nicitaacom** [TanStack/query#6198]
### Describe the bug

I got unknown type when type in known
```tsx
  const {} = useQuery({
    queryKey: ["cart_quantity"],
    queryFn: async () => {
      if (user) {
        const cart_quantity = await supabaseClient
          .from("users_cart")
          .select("cart_quantity")
          .eq("id", user?.id)
        return cart_quantity as ICartQuantityResponse
      }
      return null
    },
  })
  ```
  
  I know that type here is `ICartQuantityResponse`
 When I want to get queryData I got unknown type
 
![image](https://github.com/TanStack/query/assets/39565703/5e3fe15f-664e-4a30-85ef-f50720d819ad)

  

### Your minimal, reproducible example

codesandbox doesn't work (no way to open in vs code - infinity loading - no way to delete some file - it do nothing)

### Steps to reproduce

1. make query request
2. getQueryData
3. got unknown type of query data

### Expected behavior

I wait that I give me type for query data but I got unknown

### How often does this bug happen?

Every time

### Platform

"next": "13.5.3",
 "@tanstack/react-query": "^5.0.0",
    "@tanstack/react-query-devtools": "^5.0.1",

### Tanstack Query adapter

react-query

### TanStack Query version

^5.0.0

### TypeScript version

5.2.2

**Comment by TkDodo** [comment]
this has always been the expected behaviour. React Query cannot know what lives under a certain queryKey in the cache, because there is no up-front definition. Instead, queries are defined ad-hoc.

> codesandbox doesn't work (no way to open in vs code - infinity loading - no way to delete some file - it do nothing)

next time, use typescript playground.

what you can do is pass a generic to `queryClient.getQueryData`, as shown in this [typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ4A0c2ueAwgDbDoB28AvnAGZQQhwDkAAjAIY2o+AYwDWAeijpeQmAFoAjjnwcAsACh1QiAPiLSlanTgBeODXQB3YkvJVaMABQBKdZu2C4e-CZQYS+BwR1OE8bAGl0PAAuOABtACIhXlgAfUV+GGAYPHiAXQJg0NIAMRoY3lQ8GiE4ZxMAPkRCkMkYZCgaOHiQPAA1XgoceML6ArV6Fw01LzwAOgATXj51MTEQkIA9AH5XNS0dOEW+AFUaERoIC07TGYN7WYBzdBh-PAARJd4HWI4k1PS6Fk8BxcpNVus4NtdvsPEdeABBVCoYAPczzHy3Ox0R7PV4fPgAHkEUGANAe9W+v2SMDSyAyQJBYLW622QA)

---

what's new in v5 is that you can define your query object with the `queryOptions` helper, and re-use the key from that. Those keys are "tagged" with the return type from the queryFn, so we can actually know the expected type. Have a look at [this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ4A0c2ueAwgDbDoB2MRAjjvgPJgzAQ2pwC+cAMygQQcAOQABGAENuMgMYBrAPRR00+TAC0TUmICwAKCPyuqeLvyVqdOAF44NdAHdizclVowAFAEojJmbw8tKw2LIcMHhsHGb2cJbR7Jzc3ghGcAnuANLoeABccADaAEQhsAD6TBHAUSUAugQZWaQAYjSF0qh4NPJwfvYAfIjNmWowyFA0cCUgeABq0hQ4Jc28TYa8-saGpnIt+PFoWO7e5TDhdLVJsdzbRokAdAAm0jJGysqZmQB6APwBXZBOCvGQASRoAlwame8US1i8jwA5ugLu4ACJvaRnUJompRGIpVCPRK5PDbT7fOD-IA).

---

all of this is documented here:

- https://tanstack.com/query/v5/docs/react/typescript#typing-query-options

**Comment by nicitaacom** [comment]
> because there is no up-front definition
What do you mean by 'up-front definition'?

**Comment by nicitaacom** [comment]
A I got you what you mean - I mean this 
![image](https://github.com/TanStack/query/assets/39565703/3b7a9830-987f-4a93-9aed-1281a6eadf40)


I want press ctrl+alt+enter and got TypeScript intellisense of all my queries - also you may store info in provider (its something I wrap all my project in layout.tsx)
(for exampe under node_modules generate types for intellisense)
In supabase I know exist that thing (but you need to do it manually because its server related - no way to refresh it when DB changes)

So I don't want to continue this conversation - please ignore this (if you want - you can improve this)

**Comment by TkDodo** [comment]
> What do you mean by 'up-front definition'?

It's clear to me now that you don't understand how react-query works and why we can't have "autocomplete" on `queryClient.getQueryData`.

In things like supabase or graphql, you have one big definition (the database or the graph): one place where everything is defined. That's where auto-complete comes from.

In react-query, no such thing exists. I can have a button that does:

```
<button onClick={() => queryClient.setQueryData(['foo'], 'bar)
```

after I click the button `['foo']` is a query in the cache.
before that, it isn't.

So when you do `queryClient.getQueryData(I WANT AUTO COMPLETE HERE), there is no way that we can show you `['foo']`.

tools like trpc or zodios that build on top of react query can do this because again, they have an "up front" definition: one place that exists at compile time, before your code runs, where every possible key is defined (in trpc, its the router), that typescript can look at and infer types from.

> also you may store info in provider

for that to work, you would need to provide information about all queries to the QueryClient at the point where you define the QueryClient, not only about what the possible keys are, but also about what the types are.

**Comment by borispetrovdev** [comment]
If `getQueryData` and `setQueryData` optionally took `QueryOptions` objects, would that solve the missing type inference?

**Comment by TkDodo** [comment]
@borispetrovdev they do now:

- https://tkdodo.eu/blog/the-query-options-api#datatag
