### ISSUE TITLE
Offline mode: refresh doesn't continue in-flight mutations 

### ISSUE THREAD

**Issue by DarioSiroki** [TanStack/query#6238]
### Describe the bug

Using the offline mode recipe (storage persister, resumePausedMutations, setMutationDefaults and other jazz), if you fire a mutation while offline and refresh the page in online mode, the pending mutations are loaded from storage and continued.

However, if you fire a mutation and refresh the page while it's still pending (request is in-flight) - it doesn't continue.

I have a React Native app where users often have poor connection. They are in remote areas an offline capabilities are a must, as well as data sync once they are back online. I'm using a retry of 5 with exponential back-off. If user exits the app while sync is in progress (i.e. mutations are pending), they are going to be lost when they reopen the app.

### Your minimal, reproducible example

https://tanstack.com/query/v4/docs/react/examples/react/offline 

### Steps to reproduce

1. Cause a mutation
2. Refresh the page while mutation's request is in flight

Result: Mutation won't continue

### Expected behavior

Mutation continues

### Platform

macos
chrome
ndroid, ios (React Native)

### Tanstack Query adapter

react-query

### TanStack Query version

tried both v4 and v5

**Comment by TkDodo** [comment]
> However, if you fire a mutation and refresh the page while it's still pending (request is in-flight) - it doesn't continue.

only paused mutations are persisted per default, so that's the expected behaviour. You can of course customize this and also persist mutations in the `pending` state, but I don't think thats what you want:

1) you would have to write your own `resumeMutations` function, because we only have `resumePausedMutations` and that can only resume paused mutations. We could add a filter though to change that.

2) If a mutation is in-flight, and I refetch the page, why would I want another run of the mutation? The mutation was likely received by the backend at this point. Note that "resume" doesn't mean "continue" - it just means we fire a new mutation and replay the request.

Put another way: if the mutation is `addTodo`, and I fire it, then refresh the page, we would fire `addTodo`, which means 2 todos would have been added. This doesn't sound good ...

**Comment by DarioSiroki** [comment]
Thanks for the reply! You validated my thoughts, I reached the same conclusions after some digging and thinking...

**Comment by DarioSiroki** [comment]
Re-thinking about it... wouldn't it make sense to persist queries that are in the retry queue tho? And then modify the resumePausedMutations to work as expected with it too.. I think I'll go with this approach in my app

```ts
export function defaultShouldDehydrateMutation(mutation: Mutation) {
  mutation.state.isPaused || (mutation.state.status === 'pending' && mutation.state.failureCount > 0)
}
```

**Comment by TkDodo** [comment]
> should probably exclude it if it's in-flight...

I don't think there's currently a concept for "being in the retry queue". From an outside perspective, the mutation is `pending`, but yeah, it might be "paused" because we're sleeping until the next retry 🤔 .

It _might_ make sense to put the query/mutation into `paused` state while this is happening, but that would likely be a breaking change 🙈

**Comment by DarioSiroki** [comment]
> I don't think there's currently a concept for "being in the retry queue". From an outside perspective, the mutation is `pending`, but yeah, it might be "paused" because we're sleeping until the next retry 🤔 .
> 
> It _might_ make sense to put the query/mutation into `paused` state while this is happening, but that would likely be a breaking change 🙈

Yes, that would be a breaking change, however I don't see why this approach wouldn't work, besides the fact that I don't think there's anything in the API telling you if the mutation is in-flight so the "isExecuting" here is fictional
```ts
export function defaultShouldDehydrateMutation(mutation: Mutation) {
  mutation.state.isPaused || (mutation.state.status === 'pending' && mutation.state.failureCount > 0 && !mutation.state.isExecuting)
}
```

Also another suggestion: keeping a track of lastFailedAt timestamp on the Mutation would make it possible to have a relatively simple way of creating a hook like useRetryDelay which could then be used to figure out how much milliseconds are left until mutation is fired again if it failed. Use case would be showing the client how much until next try.

**Comment by bessey** [comment]
Hi there, resurrecting this thread as I am experiencing the exact same problem as the OP; React Native app, users often have poor connection, TanStack's opinions are causing lost writes.

> only paused mutations are persisted per default, so that's the expected behaviour. 

I can understand why this behaviour is a safe default but I am quite surprised it is not configurable. After all, `useMutation` provides APIs to enable retry after failure, despite the fact this could lead to "backend maybe processed it" bugs too. Its up to the user to ensure mutations that auto-retry are idempotent, and there are many techniques to achieve this like [idempotency keys](https://docs.stripe.com/api/idempotent_requests). 

Here's two real use cases we have today:

1. TanStack believes there is network connectivity because the user's device does, but in practice the connection is so bad (high packet loss / low bandwidth) that mutations are timing out. We set 15s timeouts and enable retries to ensure that requests are retried later.
2. A single TanStack mutation is in flight or a low bandwidth connection. This mutation function is responsible for orchestrating several requests which include multi-megabyte file uploads. It is idempotent and will resume from where it left off, given the chance. Due to the slow nature of the mutation function, the risk of the app being backgrounded and killed while it is in flight is high.

In both cases I would _rather_ TanStack persisted these mutations and started them fresh on the next app boot than the current behaviour.

**Comment by bessey** [comment]
For others reference, turns out TanStack _does_ offer enough public APIs to change this behaviour to what I expected <3 see https://github.com/TanStack/query/discussions/7044
