### ISSUE TITLE
QueryObserver doesn't catch-up to current state

### ISSUE THREAD

**Issue by matthewhuang97** [TanStack/query#6331]
### Describe the bug

I'm integrating our application with [jotai-tanstack-query](https://jotai.org/docs/integrations/query) and ran into a bug with how that library uses Tanstack Query. It seems to be reproducible independently:

1. Create a new `QueryObserver` with stale/cache time set to Infinity
2. Subscribe the observer, which triggers the queryFn
3. Un-subscribe the observer
4. The queryFn resolves in the background while the observer is un-subscribed
5. Re-subscribe the observer

After this state, the observer won't receive any updates and will stay stuck in a loading state. `observer.getCurrentResult()` also still shows a loading + fetching state. I would've expected the observer to have some update about queryFn that finished. Reading from the QueryClient's cached values shows that the query state _is_ loaded and set to the expected value.

Thanks so much in advance!

### Your minimal, reproducible example

https://codesandbox.io/s/funny-pond-755jkd?file=/src/App.tsx

### Steps to reproduce

1. Create a new `QueryObserver` with stale/cache time set to Infinity
2. Subscribe the observer, which triggers the queryFn
3. Un-subscribe the observer
4. The queryFn resolves in the background while the observer is un-subscribed
5. Re-subscribe the observer

### Expected behavior

I would've expected the observer to have an update that queryFn that finished, or that `observer.getCurrentResult()` returns the fresh value matching the QueryClient's cache

### How often does this bug happen?

Every time

### Platform

macOS

### Tanstack Query adapter

None

### TanStack Query version

5.7.2, also repros on 4.24.10

**Comment by TkDodo** [comment]
I think you need to use `getOptimisticResult`:

https://codesandbox.io/s/purple-paper-6qlzjq?file=/src/App.tsx

But I'll look into this some more

**Comment by TkDodo** [comment]
I debugged this a bit, and it seems to be a sequence of events happening (or not happening here) that lead to this:

1) we update (set) the result when the observer is created
2) we update the result when new data comes in
3) we update the result when options change, which happens in an effect in react

1) is happening, so the result is set to `pending`, then we fetch.
2) is not happening because the observer has unsubscribed in the meantime
3) is not happening because `setOptions` is not being called

Turns out it's a one line fix:
- https://github.com/TanStack/query/pull/6334

**Comment by matthewhuang97** [comment]
Thanks so much for the fast fix!
