### ISSUE TITLE
useSuspenseQuery() returns undefined as data when network is offline

### ISSUE THREAD

**Issue by jinjor** [TanStack/query#6344]
### Describe the bug

`useSuspenseQuery()` returns undefined as data when network is offline. This is strange because  the type of `useSuspenseQuery()` says that `data` should never be `undefined`.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/frosty-field-7khlvr?file=%2Fsrc%2FApp.tsx%3A1%2C1

### Steps to reproduce

1. Go to example linked above
2. Open DevTool and modify the network throttling to "Offline"
3. Click "Load" button

### Expected behavior

I expected a promise to be thrown and the fallback ("Loading...") is shown, but actually `undefined` was returned as data.

### How often does this bug happen?

None

### Platform

- OS: macOS
- Browser: Chrome 118

### Tanstack Query adapter

None

### TanStack Query version

v5.8.1

**Comment by TkDodo** [comment]
Hm, that's not good. I mean I know why this happens: because the default `networkMode: 'online'` makes queries go to `paused` state immediately, without actually triggering suspense.

`networkMode: 'offlineFirst'` + at least one retry (there are 3 on by default) would likely fix this for you, but I agree, we have to find a way to make this better 🤔 

the condition to decide if we should suspend is this:

https://github.com/TanStack/query/blob/129f8c9fad154bd16f6ab6d739592ea520c491b5/packages/react-query/src/suspense.ts#L36

so if we're not `fetching` (which we are not, because we are `paused`), suspense isn't triggered

**Comment by jinjor** [comment]
Thank you 😃

> networkMode: 'offlineFirst' + at least one retry
 
I have tried this workaround and it seems to be working fine in my case!
