### ISSUE TITLE
initial data breaks keepPreviousData

### ISSUE THREAD

**Issue by Mario-Eis** [TanStack/query#6353]
### Describe the bug

When initialData is set AND placeholderData is keepPreviousData, then initial data is returned while the query is fetching.
Expected is the same behaviour as if initial data would not be set. That is to return the previously fetched data.

UPDATE: This issue is also present, when data is re-fetched.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/dreamy-shape-n4tj7c?embed=1&file=%2Fsrc%2Findex.jsx

### Steps to reproduce

Open the Sandbox
Click "Load next"

### Expected behavior

Expected is the same behaviour as if initial data would not be set. That is to return the previously fetched data.

### How often does this bug happen?

Every time

### Platform

Windows 11, latest chrome

### Tanstack Query adapter

react-query

### TanStack Query version

5.8.1

**Comment by TkDodo** [comment]
This is working as expected, because you pass `initialData` to all queries. When you change the queryKey, a new cache entry is created. If you pass `initialData`, that data will be put into the cache for that entry, which means the query goes into success state. previous data is only shown while the query is in pending state, which it isn't when `initialData` is supplied.

You're probably thinking that `initialData` only does something when `useQuery` is first called, but that's not how it works. It is used every time a new Query is created, and by changing the query key, you do exactly that.

So if you want the initialData only to be used for the index 0 cache entry, you have to be explicit about that:

```
initialData: index === 0 ? {
  name: "Initial data!",
  description: "This is not the kept data.",
  subscribers_count: 0,
  stargazers_count: 0,
  forks_count: 0
} : undefined,
```

here is a fixed version of your reproduction: https://codesandbox.io/p/sandbox/mystifying-voice-z2md6v?embed=1&file=%2Fsrc%2Findex.jsx%3A37%2C31
