### ISSUE TITLE
Mutation state from useMutationState is out of sync with mutation from useMutation

### ISSUE THREAD

**Issue by dorshinar** [TanStack/query#6462]
### Describe the bug

The `status` of a mutation as reported by `useMutationState` is out of sync with the `status` as reported by `useMutation`, for the same mutation key. 

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/sharp-beaver-k7w6lf

### Steps to reproduce

1. Click on "Trigger"
2. Immediately click on "Reset"
3. The state will be out of sync

### Expected behavior

I expect mutations to be synced throughout my application, regardless of how I read their data

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/query/assets/17943918/7cfbcafa-409b-47cf-bdd2-2b093a44e964

### Platform

- OS: MacOS Sonoma 14
- Browser: Arc Version 1.17.2 (43249), Chromium Engine Version 119.0.6045.159

### Tanstack Query adapter

react-query

### TanStack Query version

v5.10.0

### TypeScript version

v4.4.2

**Comment by TkDodo** [comment]
I think this is on purpose / per design, because `useMutation` and `useMutationState` do two different things:

- `useMutation` gives you a `MutationObserver`, that has its own states.
- it's also the thing that can trigger a mutation (`useMutationState` cannot).
- once you trigger a mutation, the mutation is added to the cache. You can see that while the observer is idle, there is no result from `useMutationState` because the mutation itself doesn't exist yet. By your definition, that would also be "out of sync" already.
- Then, the mutation is running. Calling `reset` doesn't stop that. What it actually does is set back the internal state of the observer:

https://github.com/TanStack/query/blob/1d3ee672d2a1536e3463243813c91902aa97d973/packages/query-core/src/mutationObserver.ts#L91-L95

But the mutation itself is still in the cache, and it's still running. Once it resolves, global callbacks will also be invoked. So useMutationState always reflects what's in the cache, while `useMutation` only does this for the observer.
