### ISSUE TITLE
Nextjs Streaming+Server Action Error: Server Functions cannot be called during initial render. 

### ISSUE THREAD

**Issue by yanggggjie** [TanStack/query#6591]
### Describe the bug

<img width="488" alt="image" src="https://github.com/TanStack/query/assets/60206592/f64f6cc0-65a8-4734-ab8e-2ed3b3036326">

### Your minimal, reproducible example
[codesandbox](https://codesandbox.io/p/devbox/quizzical-rumple-6jqh8m?file=%2Fsrc%2Fapp%2Fapi%2Fwait%2Froute.ts&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clo1ketbw00083b6iqx9s8j9i%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clo1ketbw00033b6igxpbw5z0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clo1ketbw00053b6i09rti15f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clo1ketbw00073b6iufjo05i2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B65.20638307617749%252C34.79361692382251%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clo1ketbw00033b6igxpbw5z0%2522%253A%257B%2522id%2522%253A%2522clo1ketbw00033b6igxpbw5z0%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clo1ketbw00073b6iufjo05i2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo1ketbw00063b6i69allxbx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clo1ketbw00073b6iufjo05i2%2522%252C%2522activeTabId%2522%253A%2522clo1ketbw00063b6i69allxbx%2522%257D%252C%2522clo1ketbw00053b6i09rti15f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo1ketbw00043b6ih9bz6w9l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clo1ketbw00053b6i09rti15f%2522%252C%2522activeTabId%2522%253A%2522clo1ketbw00043b6ih9bz6w9l%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A23.833958423903923%257D)

### Steps to reproduce

error output in terminal

### How often does this bug happen?

Every time

### Tanstack Query adapter

react-query  5.0.0
react-query-next-experimental

**Comment by TkDodo** [comment]
suspense queries run on the server as well. This seems to be a nextjs design decision that you cannot call server actions during SSR. There isn't anything we can do here.

**Comment by ajwootto** [comment]
Is there a good way to get around this? It feels like a really nice use case for `useSuspenseQuery` to be able to define a server action for data fetching and plug it in to React Query so that components can automatically suspend and get their data via these fancy RPC calls rather than having to wire up a fetch call + API route. Quite unfortunate that it doesn't seem to be able to work like this.

**Comment by TkDodo** [comment]
Idk, please ask nextJs 😅

**Comment by NikolaRusakov** [comment]
@ajwootto, I experienced same issue which I resolved by reexporting my request functions in separete file containing `"use server"` and `"server-only` pragmas and added named export in index file to make importing more consistent across projects..
Then I added conditional to my queryFn function where I check for window to distinguish SSR and client Server Action.
<img width="1312" alt="Screenshot 2024-05-14 at 12 40 13" src="https://github.com/TanStack/query/assets/8559774/9e6d826d-a920-4c56-841a-9ed404ba5f4d">

It does feels hacky but does its job for now.
It imposes some additional complexities to the project since I couple tanstack query with jotai state management and leverage jotai-query library which I have to take care of atom hydration and such.

I hope this discovery finds you helpful.

**Comment by KajSzy** [comment]
@TkDodo I've encountered this issue following [Advanced Server Rendering](https://tanstack.com/query/latest/docs/framework/react/guides/advanced-ssr) which kinda implicitly states that `getPosts` it's server action
If that's not true I have concerns that sharing fetching logic between server and client is a good thing

**Comment by igor9silva** [comment]
Calling the Server Action from an RSC works fine, so injecting initial data via `useSuspenseQuery()`'s `initialData` does the job and get rid of the errors, while keeping SSR ✅ 

I'm not entirely sure what the initial "fetch waterfall" warning mean, so maybe there are some hidden costs I'm not seeing.

(I know it's a Next thing, but this is the page I find from Google so I'm writing here for reference)

Something like that:

**Parent Server Component**
```ts
function Parent() {
	const data = await getData(); // server action
	return <ChildClientComponent initialData={data} />
}
```

**Child Client Component**
```ts
function Child({ initialData }: { initialData: Data }) {
	const query = useSuspenseQuery({
		queryKey: ['data'],
		queryFn: () => getData(), // the very same server action
		initialData,
	});
}
```

**Comment by withintheruins14** [comment]
even though I am seeing this error today on one screen, I feel like the rest of my app does work this way? I think some mixture of `actions.ts` files and the "use server" directive can get you around this

**Comment by withintheruins14** [comment]
In my case, I just needed to make sure I was awaiting the promise in the Page SRC - that cleared the error in the client component

**Comment by snigdha920** [comment]
Works for me if i cache the result of the server method using `unstable_cache`

**Comment by GhostvOne** [comment]
> In my case, I just needed to make sure I was awaiting the promise in the Page SRC - that cleared the error in the client component

Hello it didn't do anything for me :( 
Still looking for a good solution using useSuspenseQuery

**Comment by MartinCura** [comment]
In case it helps anyone because i just went through turning on Cache Components in a medium-sized app:

- If you have `useSuspenseQuery()` and it doesn't get initial data somehow, it will try to run its `queryFn` on initial render server-side and it complains if it's a Server Function (it feels to me that it should be able to sort that out? that's on Next.js); so you can either
  - Pass it `initialData` (like igor9silva showed) and no error
  - Use the prefetcher [pattern](https://tanstack.com/query/latest/docs/framework/react/guides/advanced-ssr#prefetching-and-dehydrating-data) (which i like) higher up, and make sure it has a `connection()` if necessary, e.g. i have:
```tsx
export async function Prefetcher({ children }: { children: React.ReactNode }) {
  await connection()

  const queryClient = getQueryClient()
  void queryClient.prefetchQuery(cartQueryOptions())

  return <HydrationBoundary state={dehydrate(queryClient)}>{children}</HydrationBoundary>
}
```
and this wraps children in some of my `layout.tsx` files (and you must have some `<Suspense>` wrapping it), and this also avoids the error.
