### ISSUE TITLE
When used in conjunction with the latest version of "vite-plugin-vue-devtools@7.0.3," there may be an error.

### ISSUE THREAD

**Issue by whyfail** [TanStack/query#6632]
### Describe the bug

In a Vite project, when using both "@tanstack/vue-query": "^5.17.0" and "vite-plugin-vue-devtools": "^7.0.3" simultaneously, there may be an error upon starting the project.

This results in my "vite-plugin-vue-devtools" being unable to function properly.

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/tanstack-vue-query-7d2xj6

### Steps to reproduce

Open the console and you'll see an error message

![image](https://github.com/TanStack/query/assets/65395563/f068ed9d-ab8c-4759-b839-ae23235b3f59)

### Expected behavior

Open the console and you'll see an error message

### How often does this bug happen?

None

### Platform

window11
Google Chrome:119.0.6045.159
vue:3.4.3
vite:5.0.10

### Tanstack Query adapter

None

### TanStack Query version

v5.17.0

**Comment by TkDodo** [comment]
@DamianOsipiuk fyi

**Comment by DamianOsipiuk** [comment]
@whyfail Since this is a breaking change in the devtools rewrite, we cannot do to much from our side actually.  
What we could do is to offer a way to `disable` the devtools plugin. Or maybe even disable it by default, and offer `enable` flag? 🤔 

And for the future, since now there are a lot of devtools creating (nuxt, vite, vue) i think that we should eventually remove it from the lib itself.  
It was ok, when there was only one `official vue devtools`, but now people can choose from many.

We offer component-based devtools that should be always up-to-date, and if someone wants to hook to other offered by their framework, it should be up to the community to maintain those integrations.

**Comment by StefanFlaschko** [comment]
So, how to enable the devtools if I want to use it. In the documentary, there are no hints on how to do it: https://tanstack.com/query/v4/docs/framework/vue/devtools
