### ISSUE TITLE
`gcTime` is not working or, better, is useless if we use `persister`

### ISSUE THREAD

**Issue by frederikhors** [TanStack/query#6679]
### Describe the bug

I'm using `experimental_createPersister` like this:

```ts
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      gcTime: 1000 * 30, // 30 seconds
      persister: experimental_createPersister({
        storage: AsyncStorage,
        maxAge: 1000 * 60 * 60 * 12, // 12 hours
      }),
    },
  },
})
```

Everything works perfectly.

Until today when for the first time I need to use `gcTime: 0` in the below query:

```ts
const playerQuery = createQuery({
  queryKey: ['player'],
  queryFn: getPlayer,
  gcTime: 0
});

$: ({ error, isLoading, isRefetching, data } = $playerQuery);
```

In this case I would like to completely disable the cache (hence the usage of `gcTime`).

But it doesn't work. As soon as the `createQuery` gets called the data is already there.

This is because persister is caching it, in fact if I disable the persister `gcTime` works.

Why persister does not "respect" the `gcTime`?

Is there a way to disable the persistence for this single query?

### Your minimal, reproducible example

I'll post if needed...

### How often does this bug happen?

Every time

### Tanstack Query adapter

svelte-query

### TanStack Query version

5

**Comment by TkDodo** [comment]
> Why persister does not "respect" the gcTime?

That's on purpose and actually one reason to use the new persister - to have data in storage that you _do not_ have in memory anymore. The reason is that we'd wanted an option that allows for memory efficient persistence, that's why gc time is decoupled from the persister.

The persister has a `maxAge` that defines how long the query should be stored. `gcTime` tells you when it can be garbage collected from memory. If the query gets gc'd, and then you use the query again, a restore attempt from the persister will be made. Since your maxAge is 12 hours, it will re-read that data for 12 hours.

> Is there a way to disable the persistence for this single query?

pass `persister: undefined` ?

or use the `filters` option on the persister. From the docs:

```
  /**
   * Filters to narrow down which Queries should be persisted.
   */
  filters?: QueryFilters
```

**Comment by frederikhors** [comment]
`persister: undefined` works amazingly! THANKS! ♥
