### ISSUE TITLE
Reload browser breaks garbage collection

### ISSUE THREAD

**Issue by mathias-berg** [TanStack/query#6697]
### Describe the bug

Hi!

I am building an Electron app and I use `PersistQueryClientProvider`.
As default `gcTime` I have set 3 days, but for some I need a different value so I just change that in that specific query.

For a while I have been seeing in the React Query Devtools that the amount of `inactive` queries just gets higher and higher and doesn't seem to be garbage collected (normally I just have about 30-40 inactive queries, but one time I hade over 1000!!!).
Whenever I debug this and clear all my cache, everything works fine. The cache is removed exactly the second it should be removed.
After a short while it goes back to not garbage collect the inactive ones.

Yesterday I finally found a way to reproduce this. Not only in my Electron app, but in a very simple Codesandbox.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/react-query-reload-69d36c

### Steps to reproduce

The `gcTime` is set to 10 seconds.

1. Click the different "tabs", look in the devtools to see that the query is added and that the inactive ones is removed after 10 seconds.
2. Press them all again and before they are removed, reload the browser window.
3. Wait 10 seconds for the inactive queries to be removed. The queries won't be garbage collected any more.
4. Click the tabs again to see if you can restart the `gcTime` timer. The query is still there after 10 seconds. 

Only way to get them to be removed is to reset the cache (from devtools).

I also tested this with a local build instead of Codesandbox and if you close the tab or quit the browser, you will get the same effect as a browser reload. 

### Expected behavior

I am expected that the inactive query will be garbage collected even after I reload the browser.
If the tab is closed or if I quit the browser, I expect the queries to be garbage collected once the app is restarted again and the  `gcTime` has passed.

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/query/assets/26097801/a328c4ef-83b8-48a2-b8fc-31115d0ff51a

### Platform

OS: MacOs Sonoma 14.2.1
Browser: Safari 17.2.1, Chrome 120.0.6099.199
Electron: 26.2.1

### Tanstack Query adapter

react-query

### TanStack Query version

5.17.10

### TypeScript version

4.9.4

### Additional context

I have tested both `createAsyncStoragePersister` and `createSyncStoragePersister` with no difference.
Version for them both: `5.17.10`

**Comment by TkDodo** [comment]
1) we only store data in localStorage, not options
2) your queries hydrate from localStorage with the default options if not otherwise specified.
3) The `gcTime` specified on `useQuery` of the `useGetTab` hook will only have an effect if the query gets rendered by `useGetTab`, which it doesn't do if you only restore it from localStorage but then never switch to that tab.

You can specify `dehydrateOptions` on the `PersistQueryClientProvider` and specify the defaultOptions that should be used when restoring. However, that would affect all queries restored from localStorage, and if they should have different options, that will not work.

The best way imo is to define options with `queryClient.setQueryDefault`. That's basically default options per key, which will always be picked up. So remove `gcTime` from `useQuery` and instead do:

```
queryClient.setQueryDefaults(["getTab"], { gcTime: 10 * 1000 });
```

working fork of your sandbox: https://codesandbox.io/p/sandbox/react-query-reload-forked-ndjf8c
