### ISSUE TITLE
Incorrect behavior with `React.use(promise)`

### ISSUE THREAD

**Issue by himself65** [TanStack/query#6797]
### Describe the bug

```ts
const pollingTasks = new Map();

function Example() {
  const { data } = useSuspenseQuery({
    queryKey: ['repoData'],
    queryFn: () => {
      return axios
        .get('https://api.github.com/repos/tannerlinsley/react-query')
        .then((res) => {
          return new Promise((resolve) => {
            setTimeout(() => {
              resolve(res.data);
            }, 1000);
          });
        });
    },
  });

  const id = useId();
  const t = true;
  if (t) {
    console.log('c', !pollingTasks.has(id), t, !pollingTasks.has(id) || t);
    if (!pollingTasks.has(id) || t) {
      console.log('create new one');
      const promise = new Promise((resolve) => {
        setTimeout(() => {
          console.log('resolve');
          resolve();
        }, 1000);
      });
      pollingTasks.set(id, promise);
      use(promise);
    }
  }
  const p = pollingTasks.get(id);
  console.log('run', id);
  use(p);  // <-- should trigger infinite re-render

  return (
    <div>
      <h1>{data.name}</h1>
      <p>{data.description}</p>
      <strong>👀 {data.subscribers_count}</strong>{' '}
      <strong>✨ {data.stargazers_count}</strong>{' '}
      <strong>🍴 {data.forks_count}</strong>
    </div>
  );
}
```

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-query-lb2sln?file=src%2Findex.jsx

### Steps to reproduce

Just run it

### Expected behavior

Should show an infinite loopIt should

### How often does this bug happen?

Every time

### Platform

- ANY

### Tanstack Query adapter

react-query

### TanStack Query version

v5.18.0

**Comment by himself65** [comment]
If you comment L28-L41, the behavior will be correct. So this is tanstack query issue

**Comment by TkDodo** [comment]
> If you comment L28-L41, the behavior will be correct. So this is tanstack query issue

I can reproduce this entirely without react-query, just by `using` a stable promise before your infinite loop (this is pretty much what useSuspenseQuery does). Here is a fork of your reproduction, completely without react-query:

https://stackblitz.com/edit/tanstack-query-tzbepn?file=src%2Findex.jsx

Maybe it's an issue in `use`, or maybe it's intended behaviour because with the v19 RC of react, there is a warning:

> A component was suspended by an uncached promise. Creating promises inside a Client Component or hook is not yet supported, except via a Suspense-compatible library or framework.

https://stackblitz.com/edit/tanstack-query-tbk8nv?file=src%2Findex.jsx

This warning goes away if we comment out your `use` calls.
