### ISSUE TITLE
Cancelling query retry on observer unsubscribe inconsistency

### ISSUE THREAD

**Issue by mbret** [TanStack/query#6932]
### Describe the bug

This code https://github.com/TanStack/query/blob/main/packages/query-core/src/query.ts#L306 state that when there are no more observers we should cancel the retry, however if we don't add observer in the first place and just run the query the retry is not cancelled in such a way. There are test files for query which confirms that retry should keep going. 

This create an inconsistency because if the query test file code runs by itself it works but if we add and then remove an observer during the process it would fail.

### Your minimal, reproducible example

.

### Steps to reproduce

.

### Expected behavior

.

### How often does this bug happen?

None

### Platform

.

### Tanstack Query adapter

None

### TanStack Query version

latest

**Comment by TkDodo** [comment]
observers give us an idea about which query is considered active and which isn't. if you have no observer and run a query anyways, and have retries configured, we will run them (because there is nothing else we can do).

If you add and then remove an observer while a query is running, this gives us the "signal" that this query is no longer used, so we don't need to needlessly retry.

Imo, this is a feature and works as designed, as aborting is something that we have to tie to observers.

**Comment by mbret** [comment]
> If you add and then remove an observer while a query is running, this gives us the "signal" that this query is no longer used, so we don't need to needlessly retry.

Opiniated but makes sense indeed

> Imo, this is a feature and works as designed, as aborting is something that we have to tie to observers.

I understand.

Reading the tests files gave me the impression of an anomaly but I appreciate your explanation. I personally find this behavior a bit strange especially since cancellation is usually done in a more explicit way either by consuming signal or calling cancel().
