### ISSUE TITLE
'PersistQueryClientProvider' refers to a value, but is being used as a type here. Did you mean 'typeof PersistQueryClientProvider'

### ISSUE THREAD

**Issue by marcshilling** [TanStack/query#6962]
### Describe the bug

"@tanstack/query-async-storage-persister": "^5.22.2",
"@tanstack/react-query": "^5.22.2",
"@tanstack/react-query-persist-client": "^5.22.2",

Using the example straight out of your docs, it doesn't seem to know what this is:
![image](https://github.com/TanStack/query/assets/5598961/48169bdd-3423-4a41-9160-06238f1f5d5b)

### Your minimal, reproducible example

no

### Steps to reproduce

install and try to use

### Expected behavior

it works

### How often does this bug happen?

None

### Platform

React Native

### Tanstack Query adapter

None

### TanStack Query version

5.22.2

**Comment by TkDodo** [comment]
> Your minimal, reproducible example
no

>Steps to reproduce
install and try to use

impossible to tell without a reproduction. maybe you're using a `.ts` file instead of `.tsx`, or there's something else wrong with your ts-config settings. I can look into it if you provide a runnable reproduction, but I won't invest my time if you don't invest your time to do that first.

feel free to reopen once you have that

**Comment by marcshilling** [comment]
@TkDodo thanks, was TSX file. Sorry, late night.
