### ISSUE TITLE
`useQuery` with `initialData` is returning `undefined` data when another query with the same key a no `initialData` is fetching

### ISSUE THREAD

**Issue by nelyousfi** [TanStack/query#6968]
### Describe the bug

If a component is mounted with a query with initial data, and another query with the same key is still fetching, the returned data is `undefined` instead of the initial data. 

This behavior can cause the app to crash, as it won't be caught by the inferred `DefinedUseQueryResult` type.

### Your minimal, reproducible example

[Codesanbox](https://codesandbox.io/p/sandbox/react-query-with-initial-data-zvrgg7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt0ccnje00063b6h9hs2w0x9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt0ccnje00023b6he7d13yze%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt0ccnje00033b6hsuwh921s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt0ccnje00053b6hg9gv69hc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt0ccnje00023b6he7d13yze%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt0ccnje00013b6hnhazihal%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clt0ccnje00023b6he7d13yze%2522%252C%2522activeTabId%2522%253A%2522clt0ccnje00013b6hnhazihal%2522%257D%252C%2522clt0ccnje00053b6hg9gv69hc%2522%253A%257B%2522id%2522%253A%2522clt0ccnje00053b6hg9gv69hc%2522%252C%2522activeTabId%2522%253A%2522clt0d0doy013f3b6h8e590dqe%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clt0d0doy013f3b6h8e590dqe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clt0ccnje00033b6hsuwh921s%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clt0ccnje00033b6hsuwh921s%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Start a query without initial data.
2. While the first query is still fetching, start a second one with the same key but this time with initial data.
3. Notice that the second query is returning `undefined` instead of initial data.

### Expected behavior

Expecting the initial data to be returned from the second query.

### How often does this bug happen?

Every time

### Platform

All platforms.

### Tanstack Query adapter

react-query

### TanStack Query version

5.22.2

### Additional context

When providing initial data, even the inferred `DefinedUseQueryResult` type suggests that the data will always be defined.

**Comment by TkDodo** [comment]
oh interesting. So conceptually, I think this is how it's designed to work. `initialData` is only taken into account when the Query is created in the cache, which in your case happens when you call `prefetchQuery`.

When your component renders, it will pick up the already existing Query and `initialData` is ignored.

So overall, this is a typings issue at best. I was very reluctant to add any guarantees on `data` always being defined, and really thought that when `initialData` is provided, nothing can go wrong. But I guess there are cases like the one you've described.

However, I don't think we're going back on the type definitions to make them `T | undefined` even if `initialData` is provided. It's too good of a dx improvement 99% of the time.

What you probably want in your case is `placeholderData`, which is always taken in to account _and_ doesn't narrow the type.

https://codesandbox.io/p/sandbox/react-query-with-initial-data-forked-whffv2

**Comment by FrikkieSnyman** [comment]
Interesting discussion. 

Since this is a typings issue, I do wonder if there's some consideration to infer return type based on the query key? Perhaps this already digresses to a discussion on [key management](https://tkdodo.eu/blog/effective-react-query-keys), but I do believe that in almost all cases, the expectation would be that a single return type exists given a key, regardless of that key being used in `prefetchQuery` or `useQuery`.

**Comment by TkDodo** [comment]
well with `queryOptions`, we can infer the return type when a key is used depending on what the quryFn returns. But that doesn't help us with adding `| undefined` to the union or not
