### ISSUE TITLE
Solid Query is not working correctly with ErrorBoundary

### ISSUE THREAD

**Issue by PeterDraex** [TanStack/query#6992]
### Describe the bug

When an error is triggered during SSR within a component that uses Solid Query, the render crashes, the error is silenced and the server doesn't respond. 30 seconds later, a "renderToString timed out" message is shown.

### Your minimal, reproducible example

https://stackblitz.com/edit/github-pqy8j7-phzf23?file=src%2Fcomponents%2FSolidApp.tsx

### Steps to reproduce

1. Open the link
2. Wait until the container starts, dependencies are installed.
3. You are shown a blank page  - App crashed instead of displaying the fallback of `ErrorBoundary`. The error was silenced.
5. Wait for a 30 second timeout.
6. "renderToString timed out" is shown in the console and in the preview window.
--
Optionally:

1. Open SolidApp.tsx
2. Uncomment `<ThrowError />` outside the `<QueryClientProvider>`
3. See that the ErrorBoundary catches the error correctly - this leads me to assume that the issue is within Tanstack Query

### Expected behavior

When error happens during SSR within ErrorBoundary, it is logged on the console and the `fallback` param of the `ErrorBoundary` is rendered instead of children.

### Environment

- Happens every time
- OS: Windows 11
- Browser: Google Chrome Version 122.0.6261.69 (Official Build) (64-bit)
- TanStack Query adapter: solid-query
- TanStack Query version: 5.22.2

**Comment by ardeora** [comment]
This should be fixed with the latest version of solid-query. 
Fixed sandbox here https://stackblitz.com/edit/github-pqy8j7-8hxy9d?file=src%2Fcomponents%2FSolidApp.tsx


Once again, Thanks so much for opening these issues with Solid Query. I really appreciate it and it helps us get solid-query to a more stable position. Please feel free to open more issues you run into and I will fix them ASAP
