### ISSUE TITLE
React Native, pnpm: Unable to resolve module @tanstack/query-core

### ISSUE THREAD

**Issue by saaymeen** [TanStack/query#7025]
### Describe the bug

Using react query with react native and pnpm, I am presented with the error message that ```@tanstack/query-core``` could not be found. It is indeed missing in node_modules. If I add it manually, I get the same error message for ```use-sync-external-store```.  As it seems, both are listed as direct dependencies in the package.json of ```@tanstack/react-query```.

This happens regardless of v4 or v5.

If i add both packages manually, I get another error:

 ```
Class private methods are not enabled. Please add `@babel/plugin-transform-private-methods` to your configuration.
```

I can go on with this chain of adding and installing packages, but as this is not mentioned anywhere in the docs, I suppose it is not the expected behavior.

### Your minimal, reproducible example

https://github.com/saaymeen/react-query-pnpm-react-native-issue

### Steps to reproduce

- Clone Repo
- ```pnpm i```
- ```pnpx pod-install```
- ```pnpm ios```

### Expected behavior

App builds, bundles, creates a query client and renders the welcome page. Instead, an error message about missing imports is shown.

### How often does this bug happen?

Every time

### Platform

- MacOS Sonoma 14.3
- pnpm@8.13.1
- @tanstack/react-query v4 or v5 does not matter
- react-native@0.72.6
- iOS Simulator

### Tanstack Query adapter

react-query

### TanStack Query version

5.24.8

### TypeScript version

4.8.4

**Comment by TkDodo** [comment]
It's doubtful that v4 and v5 yield the same experience. `use-sync-external-store` is only needed in v4. The "private fields" error can only be in v5 because we only use private fields in v5. The requirements are documented here: https://tanstack.com/query/v5/docs/framework/react/installation#requirements

if your environment doesn't support private fields, you have to transpile the source yourself.

> As it seems, both are listed as direct dependencies in the package.json of @tanstack/react-query

a package manager should install `dependencies` of a lib. Yes, `@tanstack/react-query` depends on `@tanstack/query-core`. There is nothing we can do if the dependency defined in package.json isn't installed for you for whatever reason.

**Comment by TkDodo** [comment]
also your lock file shows that query-core is there:

https://github.com/saaymeen/react-query-pnpm-react-native-issue/blob/6a49c95ebd0af8783f6ee97dbfed89a849185fa2/pnpm-lock.yaml#L1939-L1941

**Comment by lizy0329-biubiubiu** [comment]
“private fields”错误只能出现在v5中，因为我们只在v5中使用private fields。"

I can't find [support older browsers tips](https://tanstack.com/query/v5/docs/framework/react/installation#requirements) in vue doc
