### ISSUE TITLE
Codemod for other (non-react) supported frameworks

### ISSUE THREAD

**Issue by vojvodics** [TanStack/query#7030]
### Describe the bug

In the migration guide, the path to codemod is available only in the `@tanstack/react-query` package. Should it be bundled with other framework packages?

I tried running the codemod in a vue project, but it failed (probably because it doesn't understand `.vue` files and needs some kind of transformation). What would it take for the codemod to support `.vue` or `.svelte` files? 

I imagine this could be a blocker for any mid to large vue project to migrate to v5. Is there a plan to make it work for other frameworks? If not, I'll be happy to try and modify the codemod to support it. 

### Your minimal, reproducible example

/

### Steps to reproduce

Run codemod in a vue project - you will get an error that the codemod file doesn't exist (it isn't bundled)

### Expected behavior

Codemod should be bundled with vue-query, and should modify `.vue` files

### How often does this bug happen?

None

### Platform

/

### Tanstack Query adapter

None

### TanStack Query version

v5.24.1

### Additional context

https://github.com/TanStack/query/issues/5230

**Comment by TkDodo** [comment]
I think the code-mods are specific for react-query because we look at certain imports, and other libraries have different syntax. Sorry, we just didn't write code-mods for other adapters. To be honest, the usage of those adapters is not large enough.

You're welcome to make the codemods works with vue and distribute them with `vue-query`, but I don't think that we will be working on this, sorry. It's a separate package in the monorepo, and all we do is copy them over to the `react-query` package upon build.
