### ISSUE TITLE
react query dev tools has a black text color in dark mode

### ISSUE THREAD

**Issue by jebalirami7** [TanStack/query#7041]
### Describe the bug

react query dev tools has a black text color in dark mode

### Your minimal, reproducible example

aa

### Steps to reproduce

aa

### Expected behavior

aa

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/138411253/ad7f688a-4844-40f8-add3-c155ceb20510)

### Platform

aa

### Tanstack Query adapter

react-query

### TanStack Query version

latest

**Comment by TkDodo** [comment]
Thank you for filing this issue, but we need more information before looking into this.

Specifically, a minimal, standalone, runnable reproduction is needed - preferably with [codesandbox](https://codesandbox.io/new) or [stackblitz](https://stackblitz.com/). If your issue is TypeScript related, prefer a [TypeScript playground](https://www.typescriptlang.org/play).

We'll close this issue for now, but we'll certainly re-open it if there is a proper reproduction.
