### ISSUE TITLE
Vite warnings when Sourcemaps are enabled

### ISSUE THREAD

**Issue by Stanzilla** [TanStack/query#7181]
### Describe the bug

When sourcemaps are enabled in Vite and building for production, the following warnings are emitted:

```
vite v5.2.6 building for production...
node_modules/@tanstack/react-query-devtools/build/modern/index.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/@tanstack/react-query/build/modern/useSuspenseQuery.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/@tanstack/react-query/build/modern/useBaseQuery.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
```

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-6wvpyq?file=src%2FApp.css

### Steps to reproduce

I tried to repro it in the stackblitz above but could not with a very basic layout, so it might just be something I do in the rest of my app. If there is any indication of that, please just close the issue.

The project is an electron react app, using Vite to bundle.

### Expected behavior

No warning in console.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/75278/8934da1c-bcdc-4577-a3f6-6901c8aac417)

### Platform

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.150.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 3800)|
|Memory (System)|31.31GB (28.82GB free)|
|VM|0%|

### Tanstack Query adapter

react-query

### TanStack Query version

5.28.8

### TypeScript version

5.4.3

**Comment by hitsthings** [comment]
Info for the next traveler:

https://github.com/vitejs/vite/issues/15012 has more conversation on this. It seemed to be an issue in Rollup, but perhaps caused by an issue in esbuild.

sapphi-red there [noted](https://github.com/vitejs/vite/issues/15012#issuecomment-1858010382) it may related to esbuild sourcemaps not having a mapping for 'use client' directives. (https://github.com/evanw/esbuild/issues/3548)

In the meantime, cgaube has a [plugin that can hide the warnings](https://github.com/vitejs/vite/issues/15012#issuecomment-1825035992).

**Comment by srflp** [comment]
Solution: bump @vitejs/plugin-react to 4.3.2 or higher
