### ISSUE TITLE
useInfiniteQuery breaks array order in get request and missing returned data

### ISSUE THREAD

**Issue by berkaycirak** [TanStack/query#7186]
### Describe the bug

In my api, all data is ordered according to timestamp and when client request that data it also returns based on pagination. For example, below I request 15 items from the api but useInfiniteQuery return first 7 items then returns 5 items. Also those items are unordered in the array whereas I have an ordered data at the api. 
``` js
const fetchEvents = async ({ pageParam }): Promise<NFTHistory[]> => {
    let apiUrl = `myApi/histories?skip=${pageParam * 15}&take=15`;
    
    const result = await axios.get(apiUrl);
    return result.data;
  };

  const { data, fetchNextPage, hasNextPage } = useInfiniteQuery({
    queryKey: [`${queryKey}_${chainId}`],
    queryFn: fetchEvents,
    initialPageParam: 0,
    getNextPageParam: (lastPage, pages, lastPageParam) => {
      if (lastPage.length === 0) {
        return undefined;
      } else {
        return lastPageParam + 1;
      }
    },
  });
  ```
![image](https://github.com/TanStack/query/assets/81809211/2ea32cac-7ad2-4136-ab2d-095438b1babd)

### Expected behavior

I expect like normal axios request where I can get correct data without useInfiniteQuery
```js
useEffect(() => {
    const fetchResult = async () => {
      const result = await axios.get(
        'myApi?skip=0&take=15'
      );

      console.log(result.data); //return 15 items as ordered
    };
    fetchResult();
  }, []);
  ```

**Comment by TkDodo** [comment]
Thank you for filing this issue, but we need more information before looking into this.

Specifically, a minimal, standalone, runnable reproduction is needed - preferably with [codesandbox](https://codesandbox.io/new) or [stackblitz](https://stackblitz.com/). If your issue is TypeScript related, prefer a [TypeScript playground](https://www.typescriptlang.org/play).

We'll close this issue for now, but we'll certainly re-open it if there is a proper reproduction.
