### ISSUE TITLE
queries stuck on loading state in Next.js layout.tsx

### ISSUE THREAD

**Issue by ghost** [TanStack/query#7475]

**Comment by TkDodo** [comment]
is the issue clerk related or redirect related?

- if it's only reproducible with clerk - please file an issue with clerk
- if it's because of a redirect, please create a reproduction that does a redirect _without_ clerk.

thanks

**Comment by TkDodo** [comment]
> issue is not related to clerk at all. layout.tsx file queries just gets stuck when page redirect from external source.

Then why are you having problems with a reproduction that does a redirect without clerk?

> you could it by running the project with clerk set

I don't have a clerk account or use clerk so no, I cannot. The point of a minimal, standalone reproduction is to prove that the issue is really with react-query and that addressing it here will actually fix it.

For example, We've had issues filed the past with a create-t3-app reproduction and it turned out the issue was a NextAuth context provider at the top:

- https://github.com/TanStack/query/issues/5335#issuecomment-1542399130

So forgive me if I'm skeptical to invest my time into chasing something that may or may not be a problem with React Query. For all I know, it could also be a bug in NextJs.

> i couldnt reproduce without clerk(external) redirect. 

My point exactly
