### ISSUE TITLE
Query that is not enabled returns the result stored in the cache

### ISSUE THREAD

**Issue by dany-pellerin** [TanStack/query#7630]
### Describe the bug

When fetching data with useQuery, the hook returns the result that was stored in the cache even though the query is not enabled. This can lead to unexpected behavior.

For example, let's say you have 2 pages:
1. a listing with a bunch of results
2. a page where you only see the results based on some filter, otherwise the query is disabled.

- If you navigate to page 1 then page 2, in page 2 you will see all items since there's no filter.
- If you directly navigate to page 2, you won't see anything because the result hasn't been stored in the cache yet (expected), then if you navigate to page 1 then page 2 again, all results will be visible on page 2. (unexpected since the query is not enabled)

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/hardcore-tom-ywk5jm

### Steps to reproduce

1. Navigate to code sandbox
2. You should see 2 lists of items, one where the query is enabled and the other where the query is not
3. Both list show all items even though the query is not enabled for the 2nd one

### Expected behavior

As a user, if a query is not enabled, I would expect to not receive the result stored in the cache.

### How often does this bug happen?

Every time

### Platform

MacOS, Chrome

### Tanstack Query adapter

None

### TanStack Query version

5.40.1

### TypeScript version

5.4.4

**Comment by brunolopesr-dft** [comment]
The `enabled` property of a query controls whether the query should start the fetch lifecycle or not. If the query cache was already populated for a given `queryKey`, the `data` property will return it, even if `enabled` = `false`

Following your example, if the `page` is something that is used to retrieve a new set of data, it should be included in the `queryKey` along with other properties. If the `enabled` property is `false` when the `page` changes from 1 to 2, it will not start the fetch, you can observe that by looking at the `fetchStatus` property that will be `idle`, the data then will stay at `undefined`.

If the data for the page 2, in this scenario, was already populated for example in another place of your app or by prefetching, even if `enabled` = `false`, it will be returned by the `useQuery` if it is still available in the cache.

To show or not to show the data should be controled by you in your app, not by React Query.

**Comment by dany-pellerin** [comment]
> The `enabled` property of a query controls whether the query should start the fetch lifecycle or not. If the query cache was already populated for a given `queryKey`, the `data` property will return it, even if `enabled` = `false`
> 
> Following your example, if the `page` is something that is used to retrieve a new set of data, it should be included in the `queryKey` along with other properties. If the `enabled` property is `false` when the `page` changes from 1 to 2, it will not start the fetch, you can observe that by looking at the `fetchStatus` property that will be `idle`, the data then will stay at `undefined`.
> 
> If the data for the page 2, in this scenario, was already populated for example in another place of your app or by prefetching, even if `enabled` = `false`, it will be returned by the `useQuery` if it is still available in the cache.
> 
> To show or not to show the data should be controled by you in your app, not by React Query.

I understand what you're saying, maybe the use case I've given is not clear enough. Maybe I should've started a discussion instead of raising an issue.

The way I see it is there should be a distinction between a `paused` query, I would expect a paused query to be temporarily disabled and return what is in the cache, if anything. On the other hand, as a user I would expect an `enabled` query that is disabled to not hit the network and not hit the cache either. It's disabled, it shouldn't return anything (at least that's what I believe users would expect).

> along with other properties

I am not going to provide very specific implementation details, but we are using typescript and some auto-generated code, and the object that we are passing to the useQuery function always has the same structure, it is strongly typed, imagine something like:

```
{
   someProperty: undefined // whatever type this would be
}
```

In the first instance we are not using `someProperty` but we still need to provide it because of strong typing, in the other case we only want to show the result when the property is defined, so it's disabled if someProperty is undefined. We are getting a very unexpected behavior in our app because of that. This is a simplified explanation of what is happening.

Based on what you are saying, we have 2 options, either we ditch the strongly typed code, which we don't want, or we add logic in a wrapper that when it's not enabled it doesn't return the result. It's not ideal but it's not a big deal either.

I looked in the documentation and there's no mention of that design decision (not enabled returns the cached result if any). It took me by surprise and I think it could be the same for other people. That design choice is up to you, but as a user of the library it can be very unexpected. Maybe I just missed it in the doc, but if I didn't, I would highly suggest that you update the documentation and add more details about what `enabled` does.

Thank you!

**Comment by TkDodo** [comment]
The docs say:

> If you ever want to disable a query from automatically running, you can use the enabled = false option.

When you call `useQuery`, you are still creating an observer that watches the cache entry for that key. If data is available, it will be given to you. If data gets in the cache by some means, the component will re-render. Otherwise, you would have a component that is subscribed to a query that could _never_ re-render.

> In the first instance we are not using someProperty but we still need to provide it because of strong typing

I don't fully understand your use-case. Seems like you have created some abstraction that is kinda in the way?

FWIW, I think you want to look into the `skipToken` we provide to automatically disable a query in a type-safe way. We also have an abstraction where we provide a url and required options, something like:

```
useQuery(fooQuery('/api/foo/$id', { params: path: { id : 1 }})
```

now `id` is required because it's part of the path, but what if `id` starts as undefined and becomes defined later? What we do is:

```
useQuery(fooQuery('/api/foo/$id', id ? { params: path: { id : 1 }} : skipToken)
```

`skipToken` can be imported from `@tanstack/react-query`, and if passed as the `queryFn`, the query will not run. See: https://tanstack.com/query/latest/docs/framework/react/guides/disabling-queries/#typesafe-disabling-of-queries-using-skiptoken

**Comment by dany-pellerin** [comment]
> I don't fully understand your use-case. Seems like you have created some abstraction that is kinda in the way?

It's one way to put it, yes. We never had an issue with it before, it's actually been very useful and made our transition from v4 to v5 easier. It seems like this is an edge case.

> I think you want to look into the skipToken we provide to automatically disable a query in a type-safe way

Based on the description it seems like this would work. I feel like it would be a workaround since the `skipToken` was not explicitly designed for that purpose. It feels a little a little clunky imo, at this point we'll have an internal discussion about it. Appreciate the help.

Thanks.

**Comment by Abibibi** [comment]
> The `enabled` property of a query controls whether the query should start the fetch lifecycle or not. If the query cache was already populated for a given `queryKey`, the `data` property will return it, even if `enabled` = `false`
> 
> Following your example, if the `page` is something that is used to retrieve a new set of data, it should be included in the `queryKey` along with other properties. If the `enabled` property is `false` when the `page` changes from 1 to 2, it will not start the fetch, you can observe that by looking at the `fetchStatus` property that will be `idle`, the data then will stay at `undefined`.
> 
> If the data for the page 2, in this scenario, was already populated for example in another place of your app or by prefetching, even if `enabled` = `false`, it will be returned by the `useQuery` if it is still available in the cache.
> 
> To show or not to show the data should be controled by you in your app, not by React Query.

Thanks, it worked perfectly well for me

**Comment by jcready** [comment]
> When you call `useQuery`, you are still creating an observer that watches the cache entry for that key. If data is available, it will be given to you. If data gets in the cache by some means, the component will re-render. Otherwise, you would have a component that is subscribed to a query that could never re-render.

I think this is where the confusion comes in. When I create a "disabled query" (i.e. `enabled: false`) it's non-obvious why that would still create an observer for that key. After all the query options have `enabled: false`, not `maybeRunTheQueryFn: false`. The query is disabled, thus no observer is needed. This behavior bit me in the following way:

We had multiple "queries" (query key + query fn), let's call them A, B, and C. Internally A, B, and C would just take some variable (which would get included in the query key and would be used in the query fn) and effectively return a `QueryOptions` object. They also had logic to set `enabled: false` if the variable passed to them was, say, `undefined`.

In one component we would `useQuery(A('foo'))` and in another component we had dependent query chain. Something like:

```ts
const a = useQuery({ ...A('foo'), enabled: componentProp.enabled });
const b = useQuery(B(a.data?.bar));
const c = useQuery(C(b.data?.baz));

useEffect(() => {
  if (c.data) {
    // do something with c.data
  }
}, [c.data]);
```

So what ended up happening is that both components got rendered at the same time and the second component ended up hitting `// do something with c.data` even though `componentProp.enabled` was `false`.

To get the desired behavior seems to require that we include the "enabled-ness" of the query into the query key itself. e.g.
```ts
const a = useQuery({ ...A(componentProp.enabled ? 'foo' : undefined), enabled: componentProp.enabled });
```

**Comment by TkDodo** [comment]
> I think this is where the confusion comes in. 

Yeah I mean it's just how Query is designed to work. `useQuery` subscribes you to the cache entry, and there are other ways to get data into that cache. Imagine you have a button in a different component that does a mutation and you write the response to that entry with `queryClient.setQueryData`. It is expected that a component that "uses" this query will always see the data that is in the cache. Sure it's a concept you have to get used to, but I think it's very likely the behaviour you almost always want.

**Comment by dany-pellerin** [comment]
I would like to preface my comment by saying this library is nothing short of amazing, to the point where most of the react ecosystem was impacted by it.

> It is expected that a component that "uses" this query will always see the data that is in the cache

I respectfully disagree, haha. Users have no idea what is `disabled` when using the flag. Day-to-day users don't know what happens under the hood, disabling the cache observer as well as the query is probably what most users expect out of the box. In my book, when I `disable` something, it means it's completely disabled, not partially. After reading the explanation, I can understand the design decision, but I would name it something like `pause` and use `disable` to disable the whole thing, right now that's not an option. This would be a breaking change, but I would be very happy to see that change in the next major version.

>  Sure it's a concept you have to get used to, but I think it's very likely the behaviour you almost always want.

Again I respectfully disagree, I can't think of a real-life use case where I disable a query, but would want to use what's in the cache if there is something. That being said, there might absolutely be real-life valid use cases, that's why I would appreciate having both options, `paused` or `disabled`. It would be more explicit, and less-prone to biting the users with something they don't expect.

**Comment by TkDodo** [comment]
>  but I would name it something like pause and use disable to disable the whole thing

I actually like the redux-toolkit-query naming of `skip`. It would also invert the condition. But we're  past that I guess :)

99% of the time, it doesn't matter. Queries are usually temporarily disabled, and will never have data. The most common case is:

```
  const [filter, setFilter] = React.useState('')

  const { data } = useQuery({
      queryKey: ['todos', filter],
      queryFn: () => fetchTodos(filter),
      // ⬇️ disabled as long as the filter is empty
      enabled: !!filter
  })
```

there is probably no way you'll have data in the cache for an empty filter. I've yet to come across a case where there is data in the cache, yet you want a disabled observer _and_ don't want to see data that's in the cache for the key you're observing.

Looking at your use-case once more:

> In the first instance we are not using someProperty but we still need to provide it because of strong typing, in the other case we only want to show the result when the property is defined, so it's disabled if someProperty is undefined. We are getting a very unexpected behavior in our app because of that. This is a simplified explanation of what is happening.

It seems like you're using the same value - `undefined` - for two different scenarios. One where you are not using `someProperty` at all and one where it's temporarily not available. Are you sure those should even observe the same cache entry? I guess the first scenario should rather be `['something', null]` rather than `['something', undefined]`. Or maybe `someProperty` could be an object where you distinct it better, like:

`['something', { someProperty: null }]` vs. `['something', undefined]`

Hard to say but usually, if you are not expecting to see data for that entry, it's because you are looking at the wrong entry / using the same entry for two different things. It should all become clear when you look at the `queryFn`. I'm guessing in the temporary disabled case,`someProperty` is used in the `queryFn`, while in the other case, it's not (but you have to pass it to your generator anyways)

**Comment by dany-pellerin** [comment]
> 99% of the time, it doesn't matter. Queries are usually temporarily disabled, and will never have data. The most common case is

This common case was exactly the case which was causing the issue, which I formulated very poorly. :) If you went to some page that had unfiltered data, and then to another page which you only show something if there is a filter selected, you ended up seeing the unfiltered data which was really unexpected and unwanted. That only happened if you navigated to the unfiltered data page before.

This is an exceptional case, it's going to be a rare occurrence for sure. The problem with that is, it means any time we use the disabled prop, this issue could potentially happen, so we need to be careful and manually override the result as if the query has never happened. We're not doing that as it's exceptional and it would be pretty cumbersome, but maybe at some point we'll have the issue again.

It's really a matter of being confident that we won't get bitten by this again, and right now we don't have the confidence and there's no option in the library that's going to give it to use. We'd have to make a wrapper which would handle that logic if we want to solve this and ensure it doesn't cause issues ever again. We can't rely on devs knowing this pitfall and reviewers catching it.

**Comment by TkDodo** [comment]
> If you went to some page that had unfiltered data, and then to another page which you only show something if there is a filter selected, you ended up seeing the unfiltered data which was really unexpected and unwanted

Please describe this use-case a bit more for me because I'm currently having a hard time imagining when this would be wanted. Usually, when you want users to filter upfront before showing something, it's because not filtering would me a massive overhead (think github issues without a filter on at least a repository) and not what people want. So you make the filter required.

But if that's the case, I can't imagine a screen where you actually fire that query without a filter, and get a result set back. And then you have that data but on another screen you want to _not_ display that data, even though it a) fits the filter criteria and b) is already there.

If such a scenario exists, the best thing you can do is be very explicit about it:

```
const { data } = useQuery({
  queryKey,
  queryFn,
  enabled: !!filter
})

if (!filter) {
  return <PleaseEnterAFilter />
}

return <...>
```

Or, split it up into two components: Make the filter be entered first, then conditionally render  a child that gets the filter passed as prop and passes it to `useQuery`. That side-steps `enabled` completely.

```
const [filter, setFilter] = useState(...)

...

{ filter ? <ResultList filter={filter} /> : null }

---

function ResultList({ filter }) {
  // no enabled here
  const { data } = useQuery({
    queryKey,
    queryFn,
  })
}

```

**Comment by jcready** [comment]
Your suggestion is to create and conditionally render an entirely new component vs. just providing a way to **actually** disabled the hook (e.g. no observers). Do you understand how cumbersome that sounds?

**Comment by dany-pellerin** [comment]
> describe this use-case a bit more for me

In our specific use case, it was a section of a page where we were showing some filtered resources, but only in some specific cases when there were filters applied, which was conditional on something else. We ended up sometimes seeing a bunch of resources when there should have been none because the condition was not met, but only when the user navigated to some other pages which fetched those resources unfiltered.

I understand you trying to figure out if there are real use cases for this, if it's worth putting effort to add that to the product. That totally makes sense and I appreciate it. For us there was a real use cases and it did cause a production issue. It was easy to fix, once we understood how it works under the hood. We feel we need to pad ourselves against this problem because we we're bitten by it and we don't want that happening again.

It all comes down to, what do you expect the `disabled` to do? Partially or completely disable? If for the library disable means to not enable the request be observe the cache, and you add a `skip` which would not do the request AND not return what's in the cache, that would greatly improve our confidence and we would replace the disable with the skip EVERYWHERE because that's always the behavior we want.

**Comment by TkDodo** [comment]
> Your suggestion is to create and conditionally render an entirely new component vs. just providing a way to actually disabled the hook (e.g. no observers). Do you understand how cumbersome that sounds?

Do you understand what the suggestion to add another flag / way of not having an observer actually means? This request has a ton of implications on how everything in the library works. Just to name a few off the top of my head:

- if you pass `initialData`, we have a type guarantee that `undefined` is not part of the union. That would go out of the window because with `enabled: false`, you would always get `undefined` back
- if you call `queryClient.setQueryData` for that entry, the observer would be informed, but I guess we don't want it to re-render because it will only get back `undefined` anyways.
- `select` runs on data from the cache, but would it run for this case?

> and you add a skip which would not do the request AND not return what's in the cache

this invites a million questions like "why do I not see my cached data even though I set with with `setQueryData` / `prefetchQuery` / hydration ? Oh, because that's how `skip` works. Having two options `enabled` and `skip` is absolutely not happening because do you understand how confusing that would be? It also wouldn't solve your problem because you can't catch if someone is using `enabled` on purpose or if they should be using `skip`.

I tried to understand the use-case but it's non-existent.

As always, conditions to widen our API surface to add new behaviour has to meet all of these criteria:
- It has to be a common use-case for multiple users
- It has to be difficult / impossible to implement in user-land

None of this is true here. `useQuery` already has 23 options and about as many return values. If we'd add every flag / option that someone suggests for their on-off use-case, we would have 1000 props, and probably also only 1000 users because the library would be too damn complex / bloated for anyone to realistically use.

**Comment by dany-pellerin** [comment]
> I tried to understand the use-case but it's non-existent.

It's not user-fed filters, it's filters that were given based on other condition. I can't explain it better and I don't think it matters to be honest. I can assure you it's very real it it caused a very real production issue. I was just misleading information on a page so not that big of a deal, but still an issue. The confusion about the `disabled` still remains whether my own specific case has an issue with it.

> Do you understand what the suggestion to add another flag / way of not having an observer actually means

I don't exactly, saying otherwise would be lying, but yes I can imagine this would be very complicated and annoying to implement.

> this invites a million questions like "why do I not see my cached data even though I set with with setQueryData / prefetchQuery / hydration ? Oh, because that's how skip works.

That is debatable I guess. For me that's exactly what I would expect and that would invite 0 questions. It's just very obvious that if you `disable` or `skip` something, even if you prefetch or set the query data the result won't be there. It's disabled. I'm specifically asking it to do nothing by passing this flag.

>  It also wouldn't solve your problem because you can't catch if someone is using enabled on purpose or if they should be using skip.

It would because we would ban the use of the enabled and always use skip. In other words we would never care about the current `disabled`, and in my opinion this is the case for the vast majority of the users of the library. I could be wrong be I don't see a case where I would've wanted it to behave the way it's been currently implemented.

> As always, conditions to widen our API surface to add new behaviour has to meet all of these criteria:
> It has to be a common use-case for multiple users
> It has to be difficult / impossible to implement in user-land

It's the case for at least 2, maybe we'll end up seeing other users complain about it at some point because the issue is very real. As much you you can't wrap your head around the idea of the current behavior causing issues, on my side I can't imagine a case where you would disable and want to receive what's been fed to the cache. All is a matter of perspective I guess...

By the way thanks again for taking the time and providing more explanations and details, hopefully (for me), some other people will have the same issue and jump in with other cases that are easier to explain / understand. I haven't checked, do you know what RTK does with the skip? Does it behave like react-query or it doesn't return what's in the cache? I haven't tested it, if you don't know, I'll definitely try it.

**Comment by TkDodo** [comment]
> on my side I can't imagine a case where you would disable and want to receive what's been fed to the cache. All is a matter of perspective I guess...

It really is a matter of perspective. A simple example is having a list query, and a dialog that pulls a single detail entry from the list query. Can be done with `useQuery` + `select`. And if you don't want this observer to cause a refetch (say, because you want to pre-fill a form and background refetches are not synced to the form state anyways), you can just set `enabled: false` instead of turning off all the refetch flags.

But most cases are really in a "it does not matter" situation because they are about "lazy queries" and the "empty cache entry" that's `enabled:false` will just never have data.

> do you know what RTK does with the skip? 

Since rtk query is built on redux, it's basically dispatch + useSelector. With `useSelector`, you subscribe to the cache entry (just like with `useQuery`). I don't think you can "turn that off", but please give it a try.

[The docs](https://redux-toolkit.js.org/rtk-query/usage/conditional-fetching) also mention disabling the conditional fetch, not the cache subscription.
