### ISSUE TITLE
QueryCache onError skips all other try/catch blocks and throws a global error

### ISSUE THREAD

**Issue by anthonyma94** [TanStack/query#8010]
### Describe the bug

When using `qc.fetchQuery` with a global `onError` set in QueryCache, any errors thrown by the query function will skip all try/catch blocks surrounding the `fetchQuery` function and immediately run the global `onError`. Errors thrown within the global `onError` also skips all try/catch blocks.

### Your minimal, reproducible example

https://stackblitz.com/edit/stackblitz-starters-ageqwz?file=app%2Fpage.tsx

### Steps to reproduce

1. Create a QueryClient with a custom QueryCache onError:

```tsx
const qc = new QueryClient({
      queryCache: new QueryCache({
        onError: (error, query) => {
          throw error; // this error should be caught in the try/catch below
        },
      })
    })
```
2. Use `fetchQuery`:

```tsx
const qc = useQueryClient();
async function () {
  try {
    const data = await qc.fetchQuery({
      queryKey: ["hello", "world"],
      queryFn: async () => {
        throw new Error("thrown"); // simulating a failed API call
      }
    });
  } catch (e) {
    console.log("i should log to console");
  }
}
```
  

### Expected behavior

try/catch surrounding `fetchQuery` should catch all errors thrown by itself and QueryCache onError.

### How often does this bug happen?

None

### Platform

- OS: WSL (Ubuntu)
- Browser: All

### Tanstack Query adapter

react-query

### TanStack Query version

v5.51.24

**Comment by TkDodo** [comment]
there's no need to re-throw errors from `onError`. `onError` is an event handler. At this point, the Query is already in error state, and `fetchQuery` will reject with that error.

if we were to allow throwing from `onError`, we would have two errors - one from the queryFn and one from the error handler. But which one should be cached for the Query? It's quite ambiguous.

So, bottom line: Your `onError` error handler shouldn't throw, and it also doesn't return anything. You can take the error you get and log it, or send it somewhere. If that fails, it's an unhandled promise rejection on purpose because it should be handled by you.
