### ISSUE TITLE
gcTime is not working with SSR, but it works well with CSR.

### ISSUE THREAD

**Issue by developer-choi** [TanStack/query#8136]
### My code
useInfiniteQuery({
  gcTime: 3000
});

This means that after 3 seconds of inactivity, the cache will be deleted.

This works well on the client side. ([README.md](https://github.com/developer-choi/react-query-bug-report-1?tab=readme-ov-file#how-to-reproduce-expected-behavior-video) > **How to reproduce expected behavior**)

However, this does not work **on the server side.** ([README.md](https://github.com/developer-choi/react-query-bug-report-1?tab=readme-ov-file#how-to-reproduce-expected-behavior-video) > **How to reproduce the bug**)

### Expressing my intention
Initially, the first page of data is fetched on the server side. 
After that, multiple calls to useInfiniteQuery().fetchNextPage() are made on the client side to fetch and store additional data in the cache.

After a period of inactivity longer than 3 seconds (such as navigating to another page and then returning), I intended to clear the cache..

To achieve this, I deliberately set the gcTime to 3000.

However, it did not work as intended — only on the server side.

The cache really has not been deleted.
I called fetchNextPage() multiple times to store data for pages in the cache. 
After navigating to another page and returning after more than 3 seconds, 
I found that the data for all pages was still displayed on the screen.

### Your minimal, reproducible example

https://github.com/developer-choi/react-query-bug-report-1

### Steps to reproduce

I wrote the reproduction steps in the [README.md](https://github.com/developer-choi/react-query-bug-report-1)

### Expected behavior

useInfiniteQuery({
  gcTime: 3000
});

After 3 seconds of inactivity, the cache should be deleted.

### How often does this bug happen?

Every time

### Screenshots or Videos

[(react-query-bug-report-1) Bug Reproduction Video](https://youtu.be/EFcFWIDEzl8)

### Platform

Windows 11
Chrome
129.0.6668.90

### Tanstack Query adapter

None

### TanStack Query version

5.59.0

**Comment by TkDodo** [comment]
your reproduction doesn’t set `gcTime` anywhere. If I set `gcTime: 3000`, the application behaves as expected: When going back to the previous page, it will only show 20 titles (1 page).

https://stackblitz.com/edit/github-js7wzn?file=src%2Fapp%2Fstart%2Flayout.tsx,src%2Fothers%2Freact-query.ts

It also should be noted that the browser back button could also just cache the html output. It would be more realistic if your second page has a link that points back to the entry page. Also, try adding the react query devtools to see what’s going on in the cache.

**Comment by yujinchoelangdy** [comment]
@TkDodo 
I have reviewed everything you mentioned, and I can confirm that it works as you described. 
However, it doesn't match my original intention, and even after going through the [official documentation](https://tanstack.com/query/latest/docs/framework/react/reference/useInfiniteQuery) again, 
I still can't fully understand it.

>your reproduction doesn’t set gcTime anywhere. If I set gcTime: 3000, the application behaves as expected

I did not intend for gcTime to be set to 3000 everywhere. I specifically wanted to reduce the gcTime setting on a particular webpage.

Also, why does gcTime always appear as 30 minutes in devtools, no matter what value I pass to gcTime in useInfiniteQuery()?

Of course, as you mentioned, I confirmed that setting gcTime to 3000 in the default options does set it to 3000. However, I specifically set gcTime to 3000 in useInfiniteQuery() because I wanted it to apply only to a specific page, not everywhere.

**Comment by developer-choi** [comment]
@TkDodo
I have reviewed everything you mentioned, and I can confirm that it works as you described.
However, it doesn't match my original intention, and even after going through the [official documentation](https://tanstack.com/query/latest/docs/framework/react/reference/useInfiniteQuery) again,
I still can't fully understand it.

>your reproduction doesn’t set gcTime anywhere. If I set gcTime: 3000, the application behaves as expected

I did not intend for gcTime to be set to 3000 everywhere. I specifically wanted to reduce the gcTime setting on a particular webpage.

Also, why does gcTime always appear as 30 minutes in devtools, no matter what value I pass to gcTime in useInfiniteQuery()?

Of course, as you mentioned, I confirmed that setting gcTime to 3000 in the default options does set it to 3000. However, I specifically set gcTime to 3000 in useInfiniteQuery() because I wanted it to apply only to a specific page, not everywhere.

**Comment by TkDodo** [comment]
> I did not intend for gcTime to be set to 3000 everywhere. I specifically wanted to reduce the gcTime setting on a particular webpage.

oh, I somehow missed [this line of code](https://github.com/developer-choi/react-query-bug-report-1/blob/e42ccbe87167e250ed45c162d9c219a7180de270/src/others/ClientListPage.tsx#L42). It technically doesn’t matter if you set it globally on or on `useInfiniteQuery`. They should get merged.

> Also, why does gcTime always appear as 30 minutes in devtools, no matter what value I pass to gcTime in useInfiniteQuery()?

It should show up as 5 minutes per default, not 30.

Please add the devtools to your reproduction and make a dedicated back link that I can click instead of browser back, then I will take another look.

**Comment by developer-choi** [comment]
@TkDodo 
I've written the content you mentioned at https://github.com/developer-choi/react-query-bug-report-1/tree/test/try-1. Please make sure to check the test/try-1 branch.

![Image](https://github.com/user-attachments/assets/16a428c6-bc03-4d81-914c-ce5533db999f)

I clicked the 'More' button twice, and three pages of data are stored in the cache. Although gcTime is set to 0, it still shows 300000 in the devtools.

Even after clicking the 'Move next page' link and immediately returning by clicking the 'Go back' link, the data for the three pages remains intact.

**Comment by TkDodo** [comment]
right, I see what’s going on. When you “send” a query from the server to the client via the `HydrationBounary`, it is “created” in the client cache if it doesn’t exist. For that, it uses the default options, unless you specify them on the `HydrationBoundary`.

Usually, options can be overwritten by passing them to `useQuery`, but `gcTime` is a bit special because  it will take the “longest” time from all the times it has gotten. So in your case, the longest time is 5 minutes (the default).

That’s also why specifying it globally works because the HydrationBoundary merges with the defaults too when creating a query.

**Comment by developer-choi** [comment]
@TkDodo 
Is this an intended behavior? If so, could you please let me know the official way to implement it according to my intent?

If not, could this be an unintended bug? If that's the case, I'll wait for it to be fixed.

![Image](https://github.com/user-attachments/assets/875e01df-96c7-4a18-b38f-73299f72db4d)

I don't think this will work, but I tried it anyway, and as expected, it didn't.

**Comment by TkDodo** [comment]
this is the intended behaviour, yes.
Your solution doesn’t work because options aren’t serialized. You need to set hydrateOption on the HydrationBoundary, or set the gcTime option globally on the queryClient created on the client (either with `defaultOptions` or with `queryClient.setQueryDefaults`) to only target a sub-set of queries.

```
<HydrationBoundary
  state={dehydrate(queryClient)}
  options={{ defaultOptions: { queries: { gcTime: 0 } } }}
>
```

**Comment by yujinchoelangdy** [comment]
@TkDodo 
Thank you so much! It works absolutely perfectly. I really appreciate your help!

**Comment by developer-choi** [comment]
@TkDodo 
Thank you so much! It works absolutely perfectly. I really appreciate your help!
