### ISSUE TITLE
[react-query] type error for infinity query defaults in QueryClient

### ISSUE THREAD

**Issue by aizerin** [TanStack/query#8218]
### Describe the bug

I recently migrated from react-query v4 and this code now reports typescript error.

It does not accept values for infinite query.

```
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      getNextPageParam: (lastPage: any) => lastPage?.nextCursor ?? undefined,
    },
  },
});
```

```
Type '{ getNextPageParam: (lastPage: any) => any; }' is not assignable to type 'OmitKeyof<QueryObserverOptions<unknown, Error, unknown, unknown, QueryKey, never>, "suspense" | "queryKey", "strictly">'.
```

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/jtqm8f

### Steps to reproduce

Just write this code

```
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      getNextPageParam: (lastPage: any) => lastPage?.nextCursor ?? undefined,
    },
  },
});
```

### Expected behavior

Typescript should be happy

### How often does this bug happen?

Every time

### Platform

Any

### Tanstack Query adapter

react-query

### TanStack Query version

5.59.16

### TypeScript version

5.6.3

**Comment by pawel-twardziak** [comment]
Hi @aizerin as far as I can see, `getNextPageParam` is not an option for `QueryClient` -> https://tanstack.com/query/latest/docs/reference/QueryClient.

You might wanna use one of these:
1. https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-react-query-3#infinitequeryobserver
2. https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-react-query-3#useinfinitequery-is-now-bi-directional

**Comment by aizerin** [comment]
I know, and I think this is wrong. Defaults for infinity query should be included in types (as they were in react-query v4). 

It also works at runtime. `getNextPageParam` is used as the default for useInfinityQuery.

**Comment by pawel-twardziak** [comment]
Ok, then it is kinda inconsistency because the implementation differs from its typings.

**Comment by TkDodo** [comment]
we moved infinite query types into their own interface because `getNextPageParam` is now required for those:

https://github.com/TanStack/query/blob/18953be6f61553f4ed3dd888945dfa1683aa6e40/packages/query-core/src/types.ts#L410-L425

It therefore doesn’t really make sense to set it globally (you’ll get an error on `useInfiniteQuery` if you don’t provide it) - same as for `initialPageParam`.

We could add it as `Partial` to the `defaultOptions` but how do you intend to use it on `useInfiniteQuery` then ?

**Comment by aizerin** [comment]
I have several infinity queries with the same `getNextPageParam` function. So I don't want to repeat it each time and just set it as default.

**Comment by TkDodo** [comment]
> So I don't want to repeat it each time and just set it as default.

I mean, even if we add these types for the default on the QueryClient, you would still get a type error on `useInfiniteQuery`. I don’t want to make them optional there as well because they are important for type-inference.

Your best option is to just create a sharable object that contains `getNextPageParam` and spread that into your `useInfiniteQuery` calls:

```
const myDefaults = {
  getNextPageParam: () => ...,
  initialPageParam: 0,
} as const

useInfiniteQuery({
  queryKey,
  queryFn,
  ...myDefaults
}
```
