### ISSUE TITLE
MutationFn not getting called on specific Scenario

### ISSUE THREAD

**Issue by MiltonAkash** [TanStack/query#8221]
### Describe the bug

This seems a little weird for me too. I observed below when working with tanstack-start

```ts
const resp = await mut.mutateAsync(data);
```
The above is not calling the function. but 
```ts
 await mut.mutateAsync(data);
```
is working fine. 

### Your minimal, reproducible example

I don't have any

### Steps to reproduce

1. Add const resp = before muation

### Expected behavior

Function should be called

### How often does this bug happen?

None

### Platform

- OS: Macos
- browser: ArcBrowser

### Tanstack Query adapter

None

### TanStack Query version

Lateste

**Comment by MiltonAkash** [comment]
It happens only if the variable `resp` is not used.

**Comment by TkDodo** [comment]
Thank you for filing this issue, but we need more information before looking into this.

Specifically, a minimal, standalone, runnable reproduction is needed - preferably with [codesandbox](https://codesandbox.io/new) or [stackblitz](https://stackblitz.com/). If your issue is TypeScript related, prefer a [TypeScript playground](https://www.typescriptlang.org/play).

We'll close this issue for now, but we'll certainly re-open it if there is a proper reproduction.

**Comment by MiltonAkash** [comment]
Tanstack start. Unused variables are not executing. Nothing to do with query I guess. You can close the issue
