### ISSUE TITLE
isFetching is always true when useQueries have duplicate query

### ISSUE THREAD

**Issue by tychenjiajun** [TanStack/query#8224]
### Describe the bug

`isFetching`, `isLoading` is always true when useQueries have duplicate query

```js
  const { data, isFetching, isLoading, isFetched } = useQueries({
    queries: [query, query, query2],
    // queries: [query],
    combine: useCallback((result) => {
      return {
        data: result[0].data,

        isFetching: result.some((r) => r.isFetching),
        isLoading: result.some((r) => r.isLoading),
        isFetched: result.every((r) => r.isFetched),
      };
    }, []),
  });
```

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/elegant-kapitsa-c3c357

### Steps to reproduce

```jsx
import "./styles.css";
import { useCallback } from "react";

import {
  useQueries,
  queryOptions,
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query";

const query = queryOptions({
  queryKey: ["users"],
  async queryFn() {
    const result = await fetch("https://jsonplaceholder.typicode.com/users");
    return await result.json();
  },
});

const query2 = queryOptions({
  queryKey: ["posts"],
  async queryFn() {
    const result = await fetch("https://jsonplaceholder.typicode.com/posts");
    return await result.json();
  },
});

const client = new QueryClient();

const Example = () => {
  const { data, isFetching, isLoading, isFetched } = useQueries({
    queries: [query, query, query2],
    // queries: [query],
    combine: useCallback((result) => {
      return {
        data: result[0].data,

        isFetching: result.some((r) => r.isFetching),
        isLoading: result.some((r) => r.isLoading),
        isFetched: result.every((r) => r.isFetched),
      };
    }, []),
  });

  return (
    <div>
      {isFetching && "isFetching"}
      {isLoading && "isLoading"}
      {isFetched && "isFetched"}
      {data?.length}
    </div>
  );
};

export default function App() {
  return (
    <QueryClientProvider client={client}>
      <div className="App">
        <h1>Hello CodeSandbox</h1>
        <h2>Start editing to see some magic happen!</h2>
        <Example />
      </div>
    </QueryClientProvider>
  );
}
```

### Expected behavior

expect `isFetching` and `isLoading` to be false

### How often does this bug happen?

Every time

### Platform

macOs 15.0.1

### Tanstack Query adapter

react-query

### TanStack Query version

5.59.16

**Comment by tychenjiajun** [comment]
Maybe duplicated https://github.com/TanStack/query/pull/4303 

It might be better if we have runtime warning in development

**Comment by olivierbeaulieu** [comment]
Would you mind explaining what's going on in this one? It sounds somewhat different from https://github.com/TanStack/query/issues/4187, where `placeholderData` causes the issue?

The codesandbox reproduction of this issue has no `placeholderData` involved, so I'm a bit puzzled by what the cause is?

**Comment by TkDodo** [comment]
we don’t support same keys in the array because a) it doesn’t achieve anything - why would you do that, it’s just redundant and b) we use the keys to keep track of where a query is in the array to support detection of changed keys, and it just doesn’t work if there are items that have the same key hash.

**Comment by jbblanchet** [comment]
@TkDodo Sorry to comment on a closed issue, but you were asking (perhaps rhetorically) "why would you do that, it’s just redundant", and I believe I have a use case that could answer your question. We need to support an arbitrary number of columns, each representing an object that needs to be loaded. We still need to run all these queries in a single component, because the ordering of the rows might depend on multiple columns. And lastly, adding the same column twice is in our case a valid use case.

Because of how hooks work, I need to combine all of these queries in a single `useQueries`. And because some of them have the same key (they're actually the same object, and I don't want to run the query twice), then my whole screen stops working, because it keeps the isFetching state.

I understand this is an edge case, and I'm built my own helper to combine and re-spread the queries and their results in the right way. I just wanted to document this use case if anyone ever ask why would someone do that in the future.

Oh and I also believe that your documentation is out of date. In the useQueries documentation, the warning simply says:

> Having the same query key more than once in the array of query objects may cause some data to be shared between queries. To avoid this, consider de-duplicating the queries and map the results back to the desired structure.

I believe this should be re-worded to make clear that having duplicate keys is NOT supported at all.

**Comment by olivierbeaulieu** [comment]
@TkDodo I just realized that I never answered you question:

>  why would you do that, it’s just redundant

A few details about our codebase:
1. We use suspense a lot, which means we use useSuspenseQueries a lot to prevent waterfalls.
2. We codegen `{ queryKey, queryFn }` objects from an OpenAPI spec, where the querykey reflects the OpenAPI OperationID.

Developers write wrappers around common operations, often to add `select` properties to queries, usually around queries for endpoints that return a lot of data. Fictional example, an endpoint that returns user data:

```
GET /userdata
{ enabledFeatures: string[], permissions: string[] } 
```

We would codegen a function that returns queryOptions like this:
```
function getUserData() {
  return {
    queryKey: ['/userdata'],
    queryFn: () => fetch('/userdata')
  }
}
```

Now this gets used all over the place, so developers want an abstraction:
```
function getEnabledFeaturesQuery() {
  return {
    ...getUserData(),
    select: (data) => data.enabledFeatures
  }
}

function getUserPermissions() {
  return {
    ...getUserData(),
    select: (data) => data.permissions
  }
}
```

If you don't use suspense, you'd simply do two `useQuery` calls and call it a day, but if you prefer suspense to handle your loading state, you'll have to do this:
```
useSuspenseQueries({
  queries: [getEnabledFeaturesQuery(), getUserPermissions()]
})
```

This has a nice benefit of abstracting the underlying endpoint from consumers. If we wanted to split the endpoint in two, we can do that with minimal lift. Developers can think of data coming from a queryOptions function, rather than an endpoint+selector pair their need to import everywhere.

Although this does give a warning of duplicate query keys, it works just fine because no `placeholderData` is involved. I just noticed a regression in that behavior though in [v5.69.2](https://github.com/TanStack/query/releases/tag/v5.69.2) - have duplicate keys with a `select` function now causes an infinite re-render.

I get that we use queryKeys to identify the position in the array. What would enable our pattern would be an alternative way to identify queries (and maybe make DX a bit nicer than destructing an array when assigning variables): using an object instead?

Something like this:
```
const { enabledFeatures, permissions } = useSuspenseQueries({
  queries: {
    enabledFeatures: getEnabledFeaturesQuery(),
    permissions: getUserPermissions()
  }
})
```

Queries as an array makes sense for useQueries' main use case of mapping over a source object, but useSuspenseQueries supports the use case of preventing waterfalls too - an object would be pretty great for that purpose, and allow keeping track of where a query is in the array to support detection of changed keys

**Comment by Katli95** [comment]
@TkDodo, sorry to bring this back up, but I've got a similar use case: multiple queries with the same key but different `select`'s.

I think @olivierbeaulieu had a good idea here:
> I get that we use queryKeys to identify the position in the array. What would enable our pattern would be an alternative way to identify queries (and maybe make DX a bit nicer than destructing an array when assigning variables): using an object instead?
> 
> Something like this:
> 
> ```
> const { enabledFeatures, permissions } = useSuspenseQueries({
>   queries: {
>     enabledFeatures: getEnabledFeaturesQuery(),
>     permissions: getUserPermissions()
>   }
> })
> ```

Also, I think it would be awesome if the lib did what the docs suggest out of the box.
> "_To avoid this, consider de-duplicating the queries and map the results back to the desired structure."_

I'm interested in trying my hand at this, but I'd prefer to do it with some guidance from the team as I'm not too familiar with the internal workings of the lib, but have been using it for a long time.

**Comment by TkDodo** [comment]
> multiple queries with the same key but different select's

this should probably just be one compound select on one key 🤔

**Comment by Katli95** [comment]
@TkDodo 
> this should probably just be one compound select on one key 🤔

I get where your coming from, esp. from the point of view of `react-query`, and I agree in a way. I guess my point is simply (& rather lazily): _"It'd be nice if this was handled by the library"_ 😅

My main proposal is that as a consumer I think it'd be nice to just interface with `useQueries` as an accessor to (& orchestrator of) the cache in a way. I'm mapping over a collection of things and want to get/refresh their latest respective data from the cache and `map/select/manipulate` the resulting query data in a particular way dependent on my `original/query-key-able` object. 

_Kinda like firing off two separate `useQuery` invocations on the same key and doing something different with the result from each._ 

Rather than what you're suggesting which I feel is more akin to batching requests by `deduping/contracting` and then `expanding/flatMapping` to get the desired result, if you follow? 


If I've convinced you that there might be something there, I can open a proper "Discussion", otherwise I won't push it further (maybe reserving the right to if I run into it again tho). I just wanted to field the idea here since I found the issue relevant.
