### ISSUE TITLE
Reset query cannot reset a particullar query but it resetting everything

### ISSUE THREAD

**Issue by bloodykheeng** [TanStack/query#8243]
### Describe the bug

i wanted eg on delete to reset a query such that isloading is triggered but i notted its just reseting everything
i wanted to reset  this

```
 queryClient.resetQueries(["users"]);
```

i want something that can do what invalidate query does on a particular query but with isLoading set to true 
invalidate doesnt set isLoading true on a particular query

### Your minimal, reproducible example

i have no link currently

### Steps to reproduce

put this in onSuccess call back of a particular mutation eg users
 queryClient.resetQueries(["users"]);

### Expected behavior

i  expected only users query to be reset and isLoading true

### How often does this bug happen?

None

### Platform

Os windows
chrome
react js

### Tanstack Query adapter

react-query

### TanStack Query version

5.45.1

**Comment by TkDodo** [comment]
Thank you for filing this issue, but we need more information before looking into this.

Specifically, a minimal, standalone, runnable reproduction is needed - preferably with [codesandbox](https://codesandbox.io/new) or [stackblitz](https://stackblitz.com/). If your issue is TypeScript related, prefer a [TypeScript playground](https://www.typescriptlang.org/play).

We'll close this issue for now, but we'll certainly re-open it if there is a proper reproduction.
