### ISSUE TITLE
Suspense causes application to hang in SSR context when query is disabled

### ISSUE THREAD

**Issue by genu** [TanStack/query#8345]
### Describe the bug

When a query is disabled, calling `suspense()` in SSR context causes hang.

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-query-5ck7qt?file=app.vue
### Steps to reproduce

```ts
const fetcher = async () =>
  await fetch('https://jsonplaceholder.typicode.com/posts').then((response) =>
    response.json()
  );

const { data, suspense } = useQuery({
  queryKey: ['test'],
  queryFn: fetcher,
  enabled: false,
});

onServerPrefetch(async () => {
  await suspense(); // <-- Causes hang
});
```

### Expected behavior

When query is disabled, I expect `suspense()` not to hang the application

### How often does this bug happen?

Every time

### Platform

Universal

### Tanstack Query adapter

vue-query

### TanStack Query version

5.61.3

**Comment by TkDodo** [comment]
I’m not sure - I think with this, you’re awaiting a promise that never resolves. But what would you expect to happen?

- We can’t resolve with `undefined`, because that doesn’t match the shape of what `fetcher` returns
- We could throw an error, but that would trigger retries and get the query into error state. Not sure if that’s better

**Comment by DamianOsipiuk** [comment]
@genu This is expected behavior as mentioned multiple times before - https://github.com/TanStack/query/issues/7609

If we would want to change this it would be a breaking change, so the earliest we could change it is the next `major`.

However, current behavior can work in two cases, when:
- you want to actually wait for `enabled` to become `true` on the server
- skip `suspense` if it's disabled, by conditionally calling `suspense`

**Comment by genu** [comment]
Thanks for the explanation @TkDodo and @DamianOsipiuk It makes sense.

The issue though is that it isn't consistent with the non-SSR behavior. If we move the suspense outside of the `onServerPrefetch` it doesn't cause a hang.

At the very least maybe indicate with a console warning that query is disabled? 🤔 The application simply hanging due to this makes problem obscure.
